### ISSUE TITLE
setuptools_scm does not get the latest git tag

### ISSUE THREAD

**Issue by ramnarayan-code** [pypa/setuptools-scm#1009]
Hi,

I am using "python -m build" utility to build the project. 
The project contains the below pyproject.toml 
```
[build-system]
requires = ["setuptools>=64", "setuptools_scm[toml]>=8.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "test-pkg"
description="test"
dynamic = ["version"]
requires-python = ">=3.8.10"
dependencies = [
    "matplotlib>=3.4.2,<=3.5.2",
    "numpy>=1.19.2,<=1.21.5",
    "pandas>=1.2.4,<=1.4.4",
    "scikit-learn>=0.24.1,<=1.1.1"
]


[tool.setuptools_scm]
version_scheme = "only-version"
local_scheme = "no-local-version"
git_describe_command = "git describe --tags --long $(git rev-list --tags --max-count=1)"

[tool.setuptools.packages.find]
where = ["src"]
include = ["pkg"]
namespaces = false

```

When I set version_scheme  as "python-simplified-semver", it generates the built package with the version "0.0.1.dev115" instead of fetching the latest git tag "3.0.0"
When I set version_scheme  as "only-version", it ends up in an exception below:
```
Traceback (most recent call last):
  File "/home/vsts/.local/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/home/vsts/.local/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/home/vsts/.local/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 287, in get_requires_for_build_sdist
    return hook(config_settings)
  File "/tmp/build-env-7ccaqf5q/lib/python3.10/site-packages/setuptools/build_meta.py", line 328, in get_requires_for_build_sdist
    return self._get_build_requires(config_settings, requirements=[])
  File "/tmp/build-env-7ccaqf5q/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
    self.run_setup()
  File "/tmp/build-env-7ccaqf5q/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 14, in <module>
  File "/tmp/build-env-7ccaqf5q/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/tmp/build-env-7ccaqf5q/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 147, in setup
    _setup_distribution = dist = klass(attrs)
  File "/tmp/build-env-7ccaqf5q/lib/python3.10/site-packages/setuptools/dist.py", line 303, in __init__
    _Distribution.__init__(self, dist_attrs)
  File "/tmp/build-env-7ccaqf5q/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
    self.finalize_options()
  File "/tmp/build-env-7ccaqf5q/lib/python3.10/site-packages/setuptools/dist.py", line 654, in finalize_options
    ep(self)
  File "/tmp/build-env-7ccaqf5q/lib/python3.10/site-packages/setuptools_scm/_integration/setuptools.py", line 121, in infer_version
    _assign_version(dist, config)
  File "/tmp/build-env-7ccaqf5q/lib/python3.10/site-packages/setuptools_scm/_integration/setuptools.py", line 53, in _assign_version
    maybe_version = _get_version(config, force_write_version_files=True)
  File "/tmp/build-env-7ccaqf5q/lib/python3.10/site-packages/setuptools_scm/_get_version_impl.py", line 96, in _get_version
    version_string = _format_version(parsed_version)
  File "/tmp/build-env-7ccaqf5q/lib/python3.10/site-packages/setuptools_scm/version.py", line 435, in format_version
    assert main_version is not None
AssertionError
```

Looking forward to your suggestions!

**Comment by RonnyPfannschmidt** [comment]
Is this a shallow clone or are tags missing in your clone?

**Comment by RonnyPfannschmidt** [comment]
Oh, the describe command will not work, it's completely broken

Arbitrary shell is not supported

**Comment by ramnarayan-code** [comment]
> Is this a shallow clone or are tags missing in your clone?

It is a full clone and tags exist in the clone

What I observed just now was it worked with the repo comprising annotated tags 
setuptools_scm does not work with the repos comprising lightweight tags.

Can setuptools_scm recognize only annotated tags?

**Comment by ramnarayan-code** [comment]
One more additional info: I use Azure DevOps Git repo

**Comment by RonnyPfannschmidt** [comment]
Closing as user error, arbitrary shell can't be supported in the describe command
