### ISSUE TITLE
`AssertionError: assert main_version is not None` when `pyproject.toml` defines its own `version_schema` and provides its own callable.

### ISSUE THREAD

**Issue by Henddher** [pypa/setuptools-scm#1010]
Hello!

I am running into an strange problem. But maybe it's expected?

If I define `version_scheme` in `[tool.setuptools_scm]`, `AssertionError` happens whenever I try `pip install -e .`[1]. Strangely enough, `local_scheme` does not prevent installation and works fine at runtime. 

If I comment out `version_scheme`, `pip install -e .` works and `python -m setuptools_scm` returns the expected version.

[1]: w/wo `-e` makes no difference.

### Is this the expected behavior?

It seems that a package A cannot use its own `version_scheme` callable. Instead, it seems that another package, package B, with a `version_scheme` callable needs to be installed so package A can use it?

----

### pyproject.toml

```ini
[build-system]
requires = ["setuptools>=61", "setuptools_scm[toml]", "wheel"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version"]

name = "setuptools-experiments"
requires-python = ">= 3.8"
description = "Experiments with setuptools."
readme = "README.md"
license = {file = "LICENSE"}
dependencies = [
]

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false

[project.entry-points."setuptools_scm.local_scheme"]
"local" = "setuptools_experiments.version_schema:get_local"

[project.entry-points."setuptools_scm.version_scheme"]
"version" = "setuptools_experiments.version_schema:get_version"

[tool.setuptools_scm]
version_file = "src/setuptools_experiments/_version.py"
# TODO: Adding version_scheme makes `pip install  .` fail.
# But when commented out, it installs and `python -m setuptools_scm` uses both custom schemes.
version_scheme = "version"
local_scheme = "local"

```

### src/setuptools_experiments/version_schema.py

```python
def get_version(*args) -> str:
    print(args)
    return "my-version"


def get_local(*args) -> str:
    print(args)
    return "my-local-version"

```

### Traceback
```
❯ pip install -e .
Obtaining file:///Users/henddher/Documents/github/setuptools-experiments
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      Traceback (most recent call last):
        File "/Users/henddher/Documents/github/setuptools-experiments/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/henddher/Documents/github/setuptools-experiments/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/henddher/Documents/github/setuptools-experiments/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "/private/var/folders/z_/21jkgpns4z911sf0mdl3w0j00000gn/T/pip-build-env-4hk_54pp/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 441, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/private/var/folders/z_/21jkgpns4z911sf0mdl3w0j00000gn/T/pip-build-env-4hk_54pp/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/z_/21jkgpns4z911sf0mdl3w0j00000gn/T/pip-build-env-4hk_54pp/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/z_/21jkgpns4z911sf0mdl3w0j00000gn/T/pip-build-env-4hk_54pp/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/private/var/folders/z_/21jkgpns4z911sf0mdl3w0j00000gn/T/pip-build-env-4hk_54pp/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/z_/21jkgpns4z911sf0mdl3w0j00000gn/T/pip-build-env-4hk_54pp/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/private/var/folders/z_/21jkgpns4z911sf0mdl3w0j00000gn/T/pip-build-env-4hk_54pp/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 303, in __init__
          _Distribution.__init__(self, dist_attrs)
        File "/private/var/folders/z_/21jkgpns4z911sf0mdl3w0j00000gn/T/pip-build-env-4hk_54pp/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
          self.finalize_options()
        File "/private/var/folders/z_/21jkgpns4z911sf0mdl3w0j00000gn/T/pip-build-env-4hk_54pp/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 654, in finalize_options
          ep(self)
        File "/private/var/folders/z_/21jkgpns4z911sf0mdl3w0j00000gn/T/pip-build-env-4hk_54pp/overlay/lib/python3.10/site-packages/setuptools_scm/_integration/setuptools.py", line 121, in infer_version
          _assign_version(dist, config)
        File "/private/var/folders/z_/21jkgpns4z911sf0mdl3w0j00000gn/T/pip-build-env-4hk_54pp/overlay/lib/python3.10/site-packages/setuptools_scm/_integration/setuptools.py", line 53, in _assign_version
          maybe_version = _get_version(config, force_write_version_files=True)
        File "/private/var/folders/z_/21jkgpns4z911sf0mdl3w0j00000gn/T/pip-build-env-4hk_54pp/overlay/lib/python3.10/site-packages/setuptools_scm/_get_version_impl.py", line 96, in _get_version
          version_string = _format_version(parsed_version)
        File "/private/var/folders/z_/21jkgpns4z911sf0mdl3w0j00000gn/T/pip-build-env-4hk_54pp/overlay/lib/python3.10/site-packages/setuptools_scm/version.py", line 435, in format_version
          assert main_version is not None
      AssertionError
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### pip freeze --all

```
packaging==23.2
pip==23.3.2
setuptools==69.0.3
# Editable Git install with no remote (setuptools-experiments==0.1.dev10+unknown)
-e /Users/henddher/Documents/github/setuptools-experiments
setuptools-scm==8.0.4
tomli==2.0.1
typing_extensions==4.9.0
```

---- 

Debugging through `setuptools_scm` code shows that `importlib.metadata.entry_points(group="local")` and `group="version"` fail to find the `version_scheme` entry point correctly (I presume it's expected because `pip install -e .` fails?). It does find the `local_scheme` (but maybe from an earlier successful installation?).

Naturally, when the package installs, `entry_points` are found.

### python

```
❯ python
Python 3.10.4 (main, Apr 16 2023, 09:35:54) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib.metadata as m
>>> m.entry_points(name="version")
[EntryPoint(name='version', value='setuptools_experiments.version_schema:get_version', group='setuptools_scm.version_scheme'), EntryPoint(name='version', value='setuptools_experiments.version_schema:get_version', group='setuptools_scm.version_scheme')]
>>> m.entry_points(name="local")
[EntryPoint(name='local', value='setuptools_experiments.version_schema:get_local', group='setuptools_scm.local_scheme'), EntryPoint(name='local', value='setuptools_experiments.version_schema:get_local', group='setuptools_scm.local_scheme')]
```

**Comment by RonnyPfannschmidt** [comment]
At install Time the own points are not available

That's a thing upstreams would need to provide

**Comment by Henddher** [comment]
Thank you @RonnyPfannschmidt 
That settles it 👍
