### ISSUE TITLE
8.0.4 fails to install with Python 3.8/3.9 (but works fine with Python 3.10+)

### ISSUE THREAD

**Issue by barracuda156** [pypa/setuptools-scm#1013]
Is it even supported for Python <= 3.9?

It fails for me:
```
--->  Configuring py38-setuptools_scm
--->  Building py38-setuptools_scm
Executing:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_python_py-setuptools_scm/py38-setuptools_scm/work/setuptools-scm-8.0.4" && /opt/local/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -m build --no-isolation --wheel --outdir /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_python_py-setuptools_scm/py38-setuptools_scm/work 
* Getting build dependencies for wheel...
running egg_info
writing src/setuptools_scm.egg-info/PKG-INFO
writing dependency_links to src/setuptools_scm.egg-info/dependency_links.txt
writing entry points to src/setuptools_scm.egg-info/entry_points.txt
writing requirements to src/setuptools_scm.egg-info/requires.txt
writing top-level names to src/setuptools_scm.egg-info/top_level.txt
ERROR setuptools_scm._file_finders.git listing git files failed - pretending there aren't any
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
    self.run_setup()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in run_setup
    exec(code, locals())
  File "<string>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 318, in run
    self.find_sources()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 326, in find_sources
    mm.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 548, in run
    self.add_defaults()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
    rcfiles = list(walk_revctrl())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/command/sdist.py", line 18, in walk_revctrl
    for item in ep.load()(dirname):
  File "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_python_py-setuptools_scm/py38-setuptools_scm/work/setuptools-scm-8.0.4/src/setuptools_scm/_file_finders/__init__.py", line 102, in find_files
    command: Callable[[_t.PathT], list[str]] = ep.load()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 208, in load
    module = import_module(match.group('module'))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'setuptools_scm.file_finder_git'

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
Command failed:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_python_py-setuptools_scm/py38-setuptools_scm/work/setuptools-scm-8.0.4" && /opt/local/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -m build --no-isolation --wheel --outdir /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_python_py-setuptools_scm/py38-setuptools_scm/work 
Exit code: 1
```
But `py310-setuptools_scm` installs fine.

**Comment by RonnyPfannschmidt** [comment]
This looks like the effect of having multiple incompatible versions active

The entry point referred is used in a older incompatible version,

**Comment by RonnyPfannschmidt** [comment]
Reading the top of the output, the build process is complete wrong and using legacy setuptools

This is a broken build pipeline

**Comment by RonnyPfannschmidt** [comment]
Basically without build isolation, if a older version of setuptools-scm is installed,things Just break

**Comment by barracuda156** [comment]
> Basically without build isolation, if a older version of setuptools-scm is installed,things Just break 

@RonnyPfannschmidt Thank you for responding. What would you recommend? Deactivating preciously installed version? That is doable, we can declare a build conflict for the port with itself, that will have an effect of the user being in need to deactivate it, if an earlier version is installed.

The installation process is as it is set in Macports (I mean, I did not tweak it locally). If something is wrong besides an earlier version active, we will be happy to fix it.

**Comment by RonnyPfannschmidt** [comment]
I'm not familiar with ports, but my guess is, the proposed mechanism should work

**Comment by RonnyPfannschmidt** [comment]
closing this one as downstream bug in handling build dependencies

**Comment by schwabe** [comment]
Using 7.1.0 instead of 8.x fixed the bug for me. Seems like setuptool-scam is not really compatible with python 3.9 anymore.

**Comment by RonnyPfannschmidt** [comment]
The assessment is incorrect 

Multiple versions of setuptools_scm had been put on the pythonpath 

The major version changed imports 

However all metadata versions are discoverable 

So entrypoints break

**Comment by schwabe** [comment]
it might be good to detect that condition and give users a more understandable error. The observed error of 

`ModuleNotFoundError: No module named 'setuptools_scm.file_finder_git'` 

does not really help finding out this condition.

**Comment by RonnyPfannschmidt** [comment]
Im inclined to say  no just stop creating broken overlapping build envs

The specific condition only happens if the python environment for buil is strictly broken

**Comment by fourtysixand2** [comment]
I'm going to have to disagree with that assertion.  In my case I can replicate the issue and the problem is related to setuptools-scm not honoring PYTHONPATH.  8.0.2 is the only version >=8.0 that does build and work properly.  This is on Slackware 15.0 with python3.9.

I'm the maintainer of python3-setuptools-scm-opt on slackbuilds.org.  As a workaround for newer versions for some python packages that ship with 15.0 we install them to /opt and use PYTHONPATH in the slackbuilds that require it.  

This has worked well except for upgrading setuptools-scm to the versions stated above.  With 8.2.1 installed and PYTHONPATH set it should, imho, find that version first and ignore the system installed version (6.3.2) but it does not and one gets the same `ModuleNotFoundError: No module named 'setuptools_scm.file_finder_git'` error.  Note that everything does work fine if the 6.3.2 version is uninstalled from the system, but our policy is to not mess with the base operating system.

I hope that helps narrow down the issue so that it can be fixed.  Let me know if you have any questions or testing I can do to help.

**Comment by RonnyPfannschmidt** [comment]
@fourtysixand2 that is a broken layered environment

python respects the python path, thus when asked to import a package from the 6.3.2 metadata which is rightfully no longer in the 8.x version its going to blow up as it goes by the python path, imports from the 8.x package, which then is the anchor for sub-modules as setuptools_scm is not a namespace - then in turn no file in the 6.2. data is accessible

as for why all metadatas in all python-paths are found - the python standard for dist-info has a fatal flaw - version numbers in the dist-info paths, so its impossible for the 8.x dist-info to shadow the 6.x dist-info - however the 8.x. python package will shadow  the 6.x python package just fine

all of that is a result of a broken python setup

a change to importlib.metadata would have to be proposed to change this status quo

if someone provides a alternative to importlib metadata that accounts for broken python in a manageable manner im happy to consume it

i will not invent it

**Comment by fourtysixand2** [comment]
That doesn't seem to explain why setuptools-scm-8.0.2 works while all of the other 8.x versions do not?

**Comment by RonnyPfannschmidt** [comment]
that needs some debugging as to why it works - based on my current Information it shouldnt

**Comment by fourtysixand2** [comment]
I think I figured out what is going on. Given the following:
```
# PYTHONPATH=/opt/python3.9/site-packages/ python3 -c "import sys; print(sys.path)"
['', '/opt/python3.9/site-packages', '/usr/lib64/python39.zip', '/usr/lib64/python3.9', '/usr/lib64/python3.9/lib-dynload', '/usr/lib64/python3.9/site-packages']

# python3 -c "import setuptools_scm as i; print(i.__file__)"
/usr/lib64/python3.9/site-packages/setuptools_scm/__init__.py

# PYTHONPATH=/opt/python3.9/site-packages/  python3 -c "import setuptools_scm as i; print(i.__file__)"
/opt/python3.9/site-packages/setuptools_scm/__init__.py

```

Deleting `/usr/lib64/python3.9/site-packages/setuptools_scm-6.3.2-py3.9.egg-info/entry_points.txt` fixes the problem.  So that made me wonder why is it finding that?  Maybe because egg-info is now deprecated (doesn't explain 8.0.2 working).  

So I reinstalled the 6.3.2 package and did the following.
`mkdir /opt/python3.9/site-packages/setuptools_scm-8.2.1-py3.9.egg-info`

That also fixes it.

I can see why that would happen, and why I thought it wasn't honoring PYTHONPATH, but should that happen?  I would think no?

**Comment by RonnyPfannschmidt** [comment]
basically any install wit a .egg or a .egg-info is a broken legacy install waiting to break something

phasing it out is a very slow process 

setuptools has extra support for those builtin and adds it

i

**Comment by barracuda156** [comment]
> The assessment is incorrect 
> 
> Multiple versions of setuptools_scm had been put on the pythonpath 

Normally if a port requires its earlier version to be uninstalled prior to upgrading to a newer version, it is fault of that port and not of the build system. It can be insisted it is not a bug but a requirement, however when nearly everything does not have such a requirement while select versions of a single port do, I am inclined to classify that as a bug in a sense of creating unexpected trouble while being fixable.

**Comment by FFY00** [comment]
This *should* not happen when using `importlib.metadata.entry_points`, as we filter out the duplicated distributions.

setuptools, though, seems to be walking `sys.path` directly and looking for entrypoints. It does seem to attempt to de-duplicate something, at least, given a new `.egg-info` shadows the previous one, but it might be considering `.egg-info` and `.dist-info` different distributions.

@jaraco would know better.

**Comment by jaraco** [comment]
Here's where [setuptools loads the entry points for file finders](https://github.com/pypa/setuptools/blob/8e4868a036b7fae3208d16cb4e5fe6d63c3752df/setuptools/command/sdist.py#L19-L22). It's simply consuming the entry points returned by `importlib metadata`. Of course, it uses `importlib_metadata` version 8 on Python 3.9 and earlier, so perhaps that's implicated. But [importlib_metadata 3.5](https://importlib-metadata.readthedocs.io/en/latest/history.html#v3-5-0) introduced the support for the unique entry points by distribution, so I'm a little surprised that it would find entry points for two different installations of setuptools-scm. Perhaps it has something to do with the rename (from `setuptools_scm` to `setuptools-scm`).

I suspect the issue can be reproduced without setuptools by running this command:

```
python -c "import importlib_metadata as metadata; eps = [ep.load() for ep in metadata.entry_points(group='setuptools.file_finders')]"
```

However, when I use pip-run in an attempt to replicate the issue, I'm unable to do so:

```
 🐚 py -3.9 -m pip-run importlib_metadata setuptools-scm==8.0.4 -- -m pip-run setuptools-scm==6.3.2 -- -c "import importlib_metadata as metadata; eps = [ep.load() for ep in metadata.entry_points(group='setuptools.file_finders')]; print(metadata.version('setuptools-scm'))"
6.3.2
 🐚 py -3.9 -m pip-run importlib_metadata setuptools-scm==6.3.2 -- -m pip-run setuptools-scm==8.0.4 -- -c "import importlib_metadata as metadata; eps = [ep.load() for ep in metadata.entry_points(group='setuptools.file_finders')]; print(metadata.version('setuptools-scm'))"
8.0.4
```

In the first invocation, I install setuptools-scm 8.0.4 and then over that install setuptools-scm 6.3.2 over it (such that the older version appears first on the PYTHONPATH). In the second invocation, I switch the order, giving 8.0.4 precedence. But in both cases, there are two versions of setuptools-scm on sys.path, each with their own metadata, and in both cases, importlib_metadata is able to load the entry points and resolve the version of the metadata from the first copy of setuptools-scm found on the path.

Can you try running the Python command above in an affected environment to confirm my suspicion that it captures the issue? If so, can you then distill some commands that will accurately replicate that environment (in Docker if platform-specific concerns are relevant)?

**Comment by RonnyPfannschmidt** [comment]
@jaraco i believe https://github.com/python/importlib_metadata/pull/281 is the solution as long as the order of found distributions follows the sys.path order 

am i understanding i correct that this is in python 3.10+ but is missing in older versions?

**Comment by fourtysixand2** [comment]
Thanks! setuptools-scm 8.3.0 builds and appears to be working as intended now on python3.9.  Will report back if I find any other issues with my testing.

**Comment by fourtysixand2** [comment]
I believe we have a partial regression of this issue with 9.2.0 with python-3.9 on Slackware 15.0.  

Only removing the older package "python-setuptools_scm-6.3.2-x86_64-1" or just the "/usr/lib64/python3.9/site-packages/setuptools_scm-6.3.2-py3.9.egg-info/entry_points.txt" file allows 9.2.0 to build and install this time.

Here's the traceback
```
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
    main()
  File "/usr/lib64/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in main
    json_out["return_val"] = hook(**hook_input["kwargs"])
  File "/usr/lib64/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 317, in get_requires_for_build_sdist
    return hook(config_settings)
  File "/opt/python3.9/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_sdist
    return self._get_build_requires(config_settings, requirements=[])
  File "/opt/python3.9/site-packages/setuptools/build_meta.py", line 301, in _get_build_requires
    self.run_setup()
  File "/opt/python3.9/site-packages/setuptools/build_meta.py", line 317, in run_setup
    exec(code, locals())
  File "<string>", line 1, in <module>
  File "/opt/python3.9/site-packages/setuptools/__init__.py", line 115, in setup
    return distutils.core.setup(**attrs)
  File "/opt/python3.9/site-packages/setuptools/_distutils/core.py", line 186, in setup
    return run_commands(dist)
  File "/opt/python3.9/site-packages/setuptools/_distutils/core.py", line 202, in run_commands
    dist.run_commands()
  File "/opt/python3.9/site-packages/setuptools/_distutils/dist.py", line 1002, in run_commands
    self.run_command(cmd)
  File "/opt/python3.9/site-packages/setuptools/dist.py", line 1102, in run_command
    super().run_command(command)
  File "/opt/python3.9/site-packages/setuptools/_distutils/dist.py", line 1021, in run_command
    cmd_obj.run()
  File "/opt/python3.9/site-packages/setuptools/command/egg_info.py", line 312, in run
    self.find_sources()
  File "/opt/python3.9/site-packages/setuptools/command/egg_info.py", line 320, in find_sources
    mm.run()
  File "/opt/python3.9/site-packages/setuptools/command/egg_info.py", line 543, in run
    self.add_defaults()
  File "/opt/python3.9/site-packages/setuptools/command/egg_info.py", line 584, in add_defaults
    rcfiles = list(walk_revctrl())
  File "/opt/python3.9/site-packages/setuptools/command/sdist.py", line 22, in walk_revctrl
    yield from ep.load()(dirname)
  File "/tmp/SBo/setuptools_scm-9.2.0/src/setuptools_scm/_file_finders/__init__.py", line 109, in find_files
    command: Callable[[_t.PathT], list[str]] = ep.load()
  File "/usr/lib64/python3.9/site-packages/importlib_metadata/__init__.py", line 221, in load
    module = import_module(self.module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'setuptools_scm.file_finder_git'

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_sdist
```

**Comment by RonnyPfannschmidt** [comment]
That's not a regression That's a broken python 

Its been multiple major releases since that module moved into a private namespace

**Comment by fourtysixand2** [comment]
The only thing that fails to build is setuptools_scm in this so-called "broken python".  I can't do anything about the system installed packages other than using PYTHONPATH to point to newer versions.  

9.2.0 doesn't build with 8.3.1 or 9.2.0 installed and PYTHONPATH used.  6.3.2 should not be in play at all in those cases.  Shouldn't setuptools_scm be smarter about not using older versions of itself?  Not everything is an ideal greenfield environment or a venv.

**Comment by RonnyPfannschmidt** [comment]
Python entrypoints are not aware of multi version packages in various setups 

So they report old locations 

This has beed fixed in newer versions of python/importlib-metadata
