### ISSUE TITLE
8.0.4 fails to build wheel on python 3.10 with gpep517 v15

### ISSUE THREAD

**Issue by rmackinnon** [pypa/setuptools-scm#1014]
Greetings, hit this today while setting up a new box.  I tried dropping python 3.10 and building for python 3.11 and found it build fine.

```
>>> Emerging (1 of 1) dev-python/setuptools-scm-8.0.4::gentoo
 * setuptools-scm-8.0.4.tar.gz BLAKE2B SHA512 size ;-) ...  [ ok ]
>>> Unpacking source...
>>> Unpacking setuptools-scm-8.0.4.tar.gz to /var/tmp/portage/dev-python/setuptools-scm-8.0.4/work
>>> Source unpacked in /var/tmp/portage/dev-python/setuptools-scm-8.0.4/work
>>> Preparing source in /var/tmp/portage/dev-python/setuptools-scm-8.0.4/work/setuptools-scm-8.0.4 ...
 * Build system packages:
 *   dev-python/gpep517            : 15
 *   dev-python/installer          : 0.7.0
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-python/setuptools-scm-8.0.4/work/setuptools-scm-8.0.4 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-python/setuptools-scm-8.0.4/work/setuptools-scm-8.0.4 ...
 * python3_10: running distutils-r1_run_phase distutils-r1_python_compile
 *   Building the wheel for setuptools-scm-8.0.4 via _own_version_helper:build_meta
python3.10 -m gpep517 build-wheel --prefix=/usr --backend _own_version_helper:build_meta --output-fd 3 --wheel-dir /var/tmp/portage/dev-python/setuptools-scm-8.0.4/work/setuptools-scm-8.0.4-python3_10/wheel
2024-02-13 01:18:37,941 gpep517 INFO Building wheel via backend _own_version_helper:build_meta
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/gpep517/__main__.py", line 429, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/gpep517/__main__.py", line 425, in main
    return func(args)
  File "/usr/lib/python3.10/site-packages/gpep517/__main__.py", line 215, in build_wheel
    print(build_wheel_impl(args, args.wheel_dir), file=out)
  File "/usr/lib/python3.10/site-packages/gpep517/__main__.py", line 207, in build_wheel_impl
    wheel_name = backend.build_wheel(str(wheel_dir), args.config_json)
  File "/usr/lib/python3.10/site-packages/setuptools/build_meta.py", line 404, in build_wheel
    return self._build_with_temp_dir(
  File "/usr/lib/python3.10/site-packages/setuptools/build_meta.py", line 389, in _build_with_temp_dir
    self.run_setup()
  File "/usr/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 147, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 303, in __init__
    _Distribution.__init__(self, dist_attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
    self.finalize_options()
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 653, in finalize_options
    for ep in sorted(loaded, key=by_order):
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 652, in <lambda>
    loaded = map(lambda e: e.load(), filtered)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 173, in load
    return functools.reduce(getattr, attrs, module)
AttributeError: module 'setuptools_scm.integration' has no attribute 'infer_version'
```
Some additional information:
- Tried rolling back gpep517 to version 14, and did not get any different result.
- This might be related to the custom build system stated in `pyproject.toml`. `README.md` states the build system should be `setuptools.build_meta` but set to the custom handler.

**Comment by RonnyPfannschmidt** [comment]
This happens when you leave a old incompatible version of setuptools-scm importable

**Comment by RonnyPfannschmidt** [comment]
I need more details on the build process

As far as I can tell its broken by your tooling diverging from standard expectations


Most likely related to expectations in path handling and metadata

**Comment by rmackinnon** [comment]
Gotcha, the version that was installed before was 7.0.x. You are not wrong. There is a chance the ebuild for this release has some issues handling the a custom build system definition. I'm using portage on a Gentoo system. 

I did try forcing the package manager to to use `setuptools.build_meta` as the build system by patching `pyproject.toml` to use the stated build system, but got a different but similar error.  That was the point where I just soft linked from the python 3.11 site packages tree to 3.10, since I just need to get over a hump and get things running so I can step everything up to 3.11/3.12.

So if nothing jumps out at you from the errors above, I'm cool with closing this for just documentation.  While I can reproduce this fairly easily, there isn't a discernible reason for spending more time trying to troubleshoot this.  If I can find a reason/fix I'll open this back up and see if I can get a PR together and/or push this upstream to the package manager bug list.
