### ISSUE TITLE
Unable to install setuptools-scm from source due to tomli project's pyproject.toml

### ISSUE THREAD

**Issue by safiyat** [pypa/setuptools-scm#1090]
While installing [bcrypt-4.0.1.tar.gz](https://pypi.org/project/bcrypt/4.0.1/) from source, the dependency chain includes setuptools-scm.

`setuptools-scm` requires tomli, whose pyproject.toml the pre-installed [toml](https://pypi.org/project/toml/) is unable to parse.

Logs:
```
    Collecting setuptools_scm
      Using cached setuptools_scm-8.1.0.tar.gz (76 kB)
      Installing build dependencies: started
      Installing build dependencies: finished with status 'error'
      ERROR: Command errored out with exit status 2:
       command: /home/ubuntu/taws/package/common/venv38/bin/python /home/ubuntu/taws/package/common/venv38/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-zty3bn41/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=61' 'tomli; python_version < "3.11"'
           cwd: None
      Complete output (45 lines):
      Collecting setuptools>=61
        Using cached setuptools-75.3.0.tar.gz (1.4 MB)
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
          Preparing wheel metadata: started
          Preparing wheel metadata: finished with status 'done'
      Collecting tomli
        Using cached tomli-2.2.1.tar.gz (17 kB)
      ERROR: Exception:
      Traceback (most recent call last):
        File "/home/ubuntu/taws/package/common/venv38/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
          status = self.run(options, args)
        File "/home/ubuntu/taws/package/common/venv38/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 357, in run
          resolver.resolve(requirement_set)
        File "/home/ubuntu/taws/package/common/venv38/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
          discovered_reqs.extend(self._resolve_one(requirement_set, req))
        File "/home/ubuntu/taws/package/common/venv38/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
          abstract_dist = self._get_abstract_dist_for(req_to_install)
        File "/home/ubuntu/taws/package/common/venv38/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
          abstract_dist = self.preparer.prepare_linked_requirement(req)
        File "/home/ubuntu/taws/package/common/venv38/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 515, in prepare_linked_requirement
          abstract_dist = _get_prepared_distribution(
        File "/home/ubuntu/taws/package/common/venv38/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
          abstract_dist.prepare_distribution_metadata(finder, build_isolation)
        File "/home/ubuntu/taws/package/common/venv38/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 33, in prepare_distribution_metadata
          self.req.load_pyproject_toml()
        File "/home/ubuntu/taws/package/common/venv38/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 512, in load_pyproject_toml
          pyproject_toml_data = load_pyproject_toml(
        File "/home/ubuntu/taws/package/common/venv38/lib/python3.8/site-packages/pip/_internal/pyproject.py", line 77, in load_pyproject_toml
          pp_toml = toml.load(f)
        File "/usr/share/python-wheels/toml-0.10.0-py2.py3-none-any.whl/toml/decoder.py", line 134, in load
          return loads(f.read(), _dict, decoder)
        File "/usr/share/python-wheels/toml-0.10.0-py2.py3-none-any.whl/toml/decoder.py", line 455, in loads
          ret = decoder.load_line(line, currentlevel, multikey,
        File "/usr/share/python-wheels/toml-0.10.0-py2.py3-none-any.whl/toml/decoder.py", line 725, in load_line
          value, vtype = self.load_value(pair[1], strictly_valid)
        File "/usr/share/python-wheels/toml-0.10.0-py2.py3-none-any.whl/toml/decoder.py", line 802, in load_value
          return (self.load_array(v), "array")
        File "/usr/share/python-wheels/toml-0.10.0-py2.py3-none-any.whl/toml/decoder.py", line 938, in load_array
          nval, ntype = self.load_value(a[i])
        File "/usr/share/python-wheels/toml-0.10.0-py2.py3-none-any.whl/toml/decoder.py", line 802, in load_value
          return (self.load_array(v), "array")
        File "/usr/share/python-wheels/toml-0.10.0-py2.py3-none-any.whl/toml/decoder.py", line 914, in load_array
          a[b] = a[b] + ',' + a[b + 1]
      IndexError: list index out of range
```

**Comment by FliegendeWurst** [comment]
Which pip version do you use? And how come you are using toml 0.10.0, when the newest version is 0.10.2?

**Comment by RonnyPfannschmidt** [comment]
reopening this as the version got yanked due to a regression

**Comment by RonnyPfannschmidt** [comment]
Closed after the last release

**Comment by jhgit** [comment]
@anchal39 @RonnyPfannschmidt 

Testing with python39, I can build and install setuptools-scm 9.2.0 without any problems when tomli 2.2.1 is installed.

Why does this commit pin to tomli <= 2.0.2?

**Comment by RonnyPfannschmidt** [comment]
Potentially a missed exclude pin

**Comment by jhgit** [comment]
> Potentially a missed exclude pin

@RonnyPfannschmidt , I'm not clear what you're thinking.  Do you mean there was a specific version of tomli that was/is a problem, and only that version should be excluded (instead of requiring <= 2.0.2)?  The OP was originally using tomli 2.2.1 according to the error messages.  tomli 2.2.1 worked fine for me, although the OP was using py38, and I used py39.

Maybe you're positing that it was the toml version not the tomli version that should have been isolated as the problem?  FWIW, I have toml 0.10.2

**Comment by RonnyPfannschmidt** [comment]
The pin was done in a way that disallows newer fixed versions i need to sort that

**Comment by safiyat** [comment]
Which newer versions have fixed this issue?

**Comment by RonnyPfannschmidt** [comment]
i haventdone the investigation yet as it wasnt on my radar, lets create a new issue

**Comment by jhgit** [comment]
@RonnyPfannschmidt wrote:
> lets create a new issue

I don't have the big picture.  If I create an issue it would be something like "the version restriction on tomli is probably / maybe wrong".  That doesn't sound like a well defined issue.  I don't understand why this change was committed in the first place (the reproduction steps are a bit lacking - I can't reproduce it), so someone else could probably create a better new issue.
