### ISSUE TITLE
cant parse version None

### ISSUE THREAD

**Issue by jaraco** [pypa/setuptools-scm#150]
With a repo on an oddly-tagged commit,

```
$ git describe --all
23.46.2post210+gbe48adfpost3+g0cc25f2
```

I get an odd error message for `setuptools_scm.get_version()`:

```
$ rwt -q setuptools_scm==1.15.0 -- -c "import setuptools_scm; setuptools_scm.get_version()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-d1ylkuc8/setuptools_scm/__init__.py", line 117, in get_version
    parsed_version = _do_parse(root, parse)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-d1ylkuc8/setuptools_scm/__init__.py", line 82, in _do_parse
    version = version_from_scm(root)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-d1ylkuc8/setuptools_scm/__init__.py", line 31, in version_from_scm
    return _version_from_entrypoint(root, 'setuptools_scm.parse_scm')
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-d1ylkuc8/setuptools_scm/__init__.py", line 37, in _version_from_entrypoint
    return ep.load()(root)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-d1ylkuc8/setuptools_scm/git.py", line 103, in parse
    return meta(tag, node=node, dirty=dirty)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-d1ylkuc8/setuptools_scm/version.py", line 86, in meta
    assert tag is not None, 'cant parse version %s' % tag
AssertionError: cant parse version None
```

I would expect the tag it couldn't parse to be `23.46.2post210+gbe48adfpost3+g0cc25f2` and not `None`.

**Comment by RonnyPfannschmidt** [comment]
@jaraco please the output when SETUPTOOLS_SCM_DEBUG is set

**Comment by jaraco** [comment]
In the setuptools_scm repo (for simplicity):

```
$ git tag 23.46.2post210+gbe48adfpost3+g0cc25f2
$ python setup.py egg_info
important note:

the setup of setuptools_scm is self-using,
the first execution of `python setup.py egg_info`
will generate partial data
its critical to run `python setup.py egg_info`
once before running sdist or easy_install on a fresh checkouts

pip usage is recommended

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'use_scm_version'
  warnings.warn(msg)
running egg_info
creating setuptools_scm.egg-info
writing setuptools_scm.egg-info/PKG-INFO
writing dependency_links to setuptools_scm.egg-info/dependency_links.txt
writing entry points to setuptools_scm.egg-info/entry_points.txt
writing top-level names to setuptools_scm.egg-info/top_level.txt
writing manifest file 'setuptools_scm.egg-info/SOURCES.txt'
reading manifest file 'setuptools_scm.egg-info/SOURCES.txt'
writing manifest file 'setuptools_scm.egg-info/SOURCES.txt'
$ SETUPTOOLS_SCM_DEBUG=1 python setup.py --version               
root '/Users/jaraco/Dropbox/code/public/setuptools_scm'
pkginfo /Users/jaraco/Dropbox/code/public/setuptools_scm/PKG-INFO
looking for ep setuptools_scm.parse_scm_fallback .
root '/Users/jaraco/Dropbox/code/public/setuptools_scm'
looking for ep setuptools_scm.parse_scm /Users/jaraco/Dropbox/code/public/setuptools_scm
found ep .git = setuptools_scm.git:parse
cmd 'git rev-parse --show-toplevel'
out b'/Users/jaraco/Dropbox/code/public/setuptools_scm\n'
real root /Users/jaraco/Dropbox/code/public/setuptools_scm
cmd 'git rev-parse --verify --quiet HEAD'
out b'905fe1ccddd2afde14f202ecf8f288679552b0c5\n'
cmd 'git status --porcelain --untracked-files=no'
cmd 'git describe --tags --long --match *.*'
out b'23.46.2post210+gbe48adfpost3+g0cc25f2-0-g905fe1c\n'
tag 23.46.2post210+gbe48adfpost3+g0cc25f2
version <LegacyVersion('23.46.2post210+gbe48adfpost3+g0cc25f2')>
version None
Traceback (most recent call last):
  File "setup.py", line 119, in <module>
    setuptools.setup(**arguments)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/dist.py", line 320, in __init__
    _Distribution.__init__(self, attrs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/dist.py", line 387, in finalize_options
    ep.load()(self, ep.name, value)
  File "/Users/jaraco/Dropbox/code/public/setuptools_scm/setuptools_scm/integration.py", line 21, in version_keyword
    dist.metadata.version = get_version(**value)
  File "/Users/jaraco/Dropbox/code/public/setuptools_scm/setuptools_scm/__init__.py", line 118, in get_version
    parsed_version = _do_parse(root, parse)
  File "/Users/jaraco/Dropbox/code/public/setuptools_scm/setuptools_scm/__init__.py", line 82, in _do_parse
    version = version_from_scm(root) or _version_from_entrypoint(
  File "/Users/jaraco/Dropbox/code/public/setuptools_scm/setuptools_scm/__init__.py", line 31, in version_from_scm
    return _version_from_entrypoint(root, 'setuptools_scm.parse_scm')
  File "/Users/jaraco/Dropbox/code/public/setuptools_scm/setuptools_scm/__init__.py", line 37, in _version_from_entrypoint
    return ep.load()(root)
  File "/Users/jaraco/Dropbox/code/public/setuptools_scm/setuptools_scm/git.py", line 106, in parse
    return meta(tag, node=node, dirty=dirty)
  File "/Users/jaraco/Dropbox/code/public/setuptools_scm/setuptools_scm/version.py", line 87, in meta
    assert tag is not None, 'cant parse version %s' % tag
AssertionError: cant parse version None
```

**Comment by RonnyPfannschmidt** [comment]
@jaraco thanks for the example, i believe unadvertised breaking away local components was broken 

i recall #127 added this

**Comment by RonnyPfannschmidt** [comment]
@jaraco i did some more analysis, and i believe i did break it when i started to pull the versions trough meta in all cases, i#ll try to fix it this weekend

**Comment by jaraco** [comment]
Excellent. Thanks!
