### ISSUE TITLE
setuptools_scm unable to compute distance?

### ISSUE THREAD

**Issue by dstufft** [pypa/setuptools-scm#167]
I have a tarball that was built with a previous version of setuptools_scm. The other day it started failing because the version number it was producing was ``1.None.0``. Nothing in the code base had changed, so I believe it to be a setuptools_scm regression.

This tarball is private, but the ``setup.py`` looks like:

```python
#!/usr/bin/env python
import setuptools


setuptools.setup(
    name="pypi-theme",
    version="15.0",

    packages=[
        "pypi_theme",
    ],

    include_package_data=True,

    use_scm_version={
        "local_scheme": "dirty-tag",
        "version_scheme": lambda v: "1.{.distance}.0".format(v),
    },

    install_requires=[
        "Pyramid",
    ],

    setup_requires=["setuptools_scm"],
)
```

I'm guessing that ``v.distance`` is returning ``None`` now when it previously didn't, but I don't know why.

**Comment by RonnyPfannschmidt** [comment]
@dstufft can you provide a anonymized output output with `SETUPTOOLS_SCM_DEBUG=1`

**Comment by RonnyPfannschmidt** [comment]
@dstufft after reviewing the code i beleive you are seeing expected behaviour, on a exact match distance is None, it has been that way since years and across multiple iterations of the version class 

for reference see https://github.com/pypa/setuptools_scm/blob/master/setuptools_scm/version.py#L69 and https://github.com/pypa/setuptools_scm/blob/master/setuptools_scm/version.py#L140

i would consider this a documentation bug

**Comment by dstufft** [comment]
@RonnyPfannschmidt On an exact match of what?

**Comment by RonnyPfannschmidt** [comment]
@dstufft no, wait, i just realized what detail got messed up, - its indeed a regression, but its certainly not introduced just now, a while back i changed how versions are passed trough

**Comment by RonnyPfannschmidt** [comment]
@dstufft setuptools_scm consider an exact match when it knows the exact version, but due to a mistake in fallback implementation the version even of fallbacks is passed trough version number formatting mechanism

the issue just never popped up because those are considered a exact match, however for custom versioning schemes just as the one your pointed out that detail simply does not hold true since they dont use the metadata in the same way

**Comment by dstufft** [comment]
To be clear, I don't actually tag any releases in this project, every commit is considered a release and it produces one of ``1.{distance}.0``. But here's the debug output:

```
SETUPTOOLS_SCM_DEBUG=1 pip install --no-cache-dir -r ~p/warehouse/requirements/theme.txt
Collecting pypi-theme==1.37 (from -r /Users/dstufft/projects/warehouse/requirements/theme.txt (line 1))
  Downloading https://.../pypi-theme-1.37.0.tar.gz (131kB)
    100% |████████████████████████████████| 133kB 1.9MB/s
  Requested pypi-theme==1.37 from https://.../pypi-theme-1.37.0.tar.gz (from -r /Users/dstufft/projects/warehouse/requirements/theme.txt (line 1)), but installing version None
Requirement already satisfied: Pyramid in ./lib/python3.5/site-packages (from pypi-theme==1.37->-r /Users/dstufft/projects/warehouse/requirements/theme.txt (line 1))
Requirement already satisfied: repoze.lru>=0.4 in ./lib/python3.5/site-packages (from Pyramid->pypi-theme==1.37->-r /Users/dstufft/projects/warehouse/requirements/theme.txt (line 1))
Requirement already satisfied: PasteDeploy>=1.5.0 in ./lib/python3.5/site-packages (from Pyramid->pypi-theme==1.37->-r /Users/dstufft/projects/warehouse/requirements/theme.txt (line 1))
Requirement already satisfied: translationstring>=0.4 in ./lib/python3.5/site-packages (from Pyramid->pypi-theme==1.37->-r /Users/dstufft/projects/warehouse/requirements/theme.txt (line 1))
Requirement already satisfied: venusian>=1.0a3 in ./lib/python3.5/site-packages (from Pyramid->pypi-theme==1.37->-r /Users/dstufft/projects/warehouse/requirements/theme.txt (line 1))
Requirement already satisfied: WebOb>=1.7.0rc2 in ./lib/python3.5/site-packages (from Pyramid->pypi-theme==1.37->-r /Users/dstufft/projects/warehouse/requirements/theme.txt (line 1))
Requirement already satisfied: hupper in ./lib/python3.5/site-packages (from Pyramid->pypi-theme==1.37->-r /Users/dstufft/projects/warehouse/requirements/theme.txt (line 1))
Requirement already satisfied: zope.deprecation>=3.5.0 in ./lib/python3.5/site-packages (from Pyramid->pypi-theme==1.37->-r /Users/dstufft/projects/warehouse/requirements/theme.txt (line 1))
Requirement already satisfied: setuptools in ./lib/python3.5/site-packages (from Pyramid->pypi-theme==1.37->-r /Users/dstufft/projects/warehouse/requirements/theme.txt (line 1))
Requirement already satisfied: zope.interface>=3.8.0 in ./lib/python3.5/site-packages (from Pyramid->pypi-theme==1.37->-r /Users/dstufft/projects/warehouse/requirements/theme.txt (line 1))
Requirement already satisfied: appdirs>=1.4.0 in ./lib/python3.5/site-packages (from setuptools->Pyramid->pypi-theme==1.37->-r /Users/dstufft/projects/warehouse/requirements/theme.txt (line 1))
Requirement already satisfied: six>=1.6.0 in ./lib/python3.5/site-packages (from setuptools->Pyramid->pypi-theme==1.37->-r /Users/dstufft/projects/warehouse/requirements/theme.txt (line 1))
Requirement already satisfied: packaging>=16.8 in ./lib/python3.5/site-packages (from setuptools->Pyramid->pypi-theme==1.37->-r /Users/dstufft/projects/warehouse/requirements/theme.txt (line 1))
Requirement already satisfied: pyparsing in ./lib/python3.5/site-packages (from packaging>=16.8->setuptools->Pyramid->pypi-theme==1.37->-r /Users/dstufft/projects/warehouse/requirements/theme.txt (line 1))
Installing collected packages: pypi-theme
  Running setup.py install for pypi-theme ... error
    Complete output from command /Users/dstufft/.virtualenvs/tmp-13d4c6e3ff2789/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/14/9jkprxq17f30vp_2wbfw79780000gn/T/pip-build-xddct4w0/pypi-theme/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/14/9jkprxq17f30vp_2wbfw79780000gn/T/pip-bfz_acz2-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/dstufft/.virtualenvs/tmp-13d4c6e3ff2789/include/site/python3.5/pypi-theme:
    looking for ep setuptools_scm.parse_scm_fallback .
    found ep pip-egg-info = setuptools_scm.hacks:parse_pip_egg_info
    root '/private/var/folders/14/9jkprxq17f30vp_2wbfw79780000gn/T/pip-build-xddct4w0/pypi-theme'
    looking for ep setuptools_scm.parse_scm /private/var/folders/14/9jkprxq17f30vp_2wbfw79780000gn/T/pip-build-xddct4w0/pypi-theme
    looking for ep setuptools_scm.parse_scm_fallback /private/var/folders/14/9jkprxq17f30vp_2wbfw79780000gn/T/pip-build-xddct4w0/pypi-theme
    found ep pip-egg-info = setuptools_scm.hacks:parse_pip_egg_info
    pip-egg-info /private/var/folders/14/9jkprxq17f30vp_2wbfw79780000gn/T/pip-build-xddct4w0/pypi-theme/pip-egg-info ['pypi_theme.egg-info']
    pkginfo /private/var/folders/14/9jkprxq17f30vp_2wbfw79780000gn/T/pip-build-xddct4w0/pypi-theme/pip-egg-info/pypi_theme.egg-info/PKG-INFO
    content 'Metadata-Version: 1.0\nName: pypi-theme\nVersion: 1.None.0\nSummary: UNKNOWN\nHome-page: UNKNOWN\nAuthor: UNKNOWN\nAuthor-email: UNKNOWN\nLicense: UNKNOWN\nDescription: UNKNOWN\nPlatform: UNKNOWN\n'
    data {'Description': 'UNKNOWN', 'Author': 'UNKNOWN', 'Author-email': 'UNKNOWN', 'Name': 'pypi-theme', 'License': 'UNKNOWN', 'Platform': 'UNKNOWN', 'Metadata-Version': '1.0', 'Summary': 'UNKNOWN', 'Home-page': 'UNKNOWN', 'Version': '1.None.0'}
    tag 1.None.0
    version <LegacyVersion('1.None.0')>
    version None
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/14/9jkprxq17f30vp_2wbfw79780000gn/T/pip-build-xddct4w0/pypi-theme/setup.py", line 24, in <module>
        setup_requires=["setuptools_scm"],
      File "/Users/dstufft/.pyenv/versions/3.5.2/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/dstufft/.virtualenvs/tmp-13d4c6e3ff2789/lib/python3.5/site-packages/setuptools/dist.py", line 321, in __init__
        _Distribution.__init__(self, attrs)
      File "/Users/dstufft/.pyenv/versions/3.5.2/lib/python3.5/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/Users/dstufft/.virtualenvs/tmp-13d4c6e3ff2789/lib/python3.5/site-packages/setuptools/dist.py", line 390, in finalize_options
        ep.load()(self, ep.name, value)
      File "/private/var/folders/14/9jkprxq17f30vp_2wbfw79780000gn/T/pip-build-xddct4w0/pypi-theme/.eggs/setuptools_scm-1.15.4-py3.5.egg/setuptools_scm/integration.py", line 22, in version_keyword
      File "/private/var/folders/14/9jkprxq17f30vp_2wbfw79780000gn/T/pip-build-xddct4w0/pypi-theme/.eggs/setuptools_scm-1.15.4-py3.5.egg/setuptools_scm/__init__.py", line 119, in get_version
      File "/private/var/folders/14/9jkprxq17f30vp_2wbfw79780000gn/T/pip-build-xddct4w0/pypi-theme/.eggs/setuptools_scm-1.15.4-py3.5.egg/setuptools_scm/__init__.py", line 84, in _do_parse
      File "/private/var/folders/14/9jkprxq17f30vp_2wbfw79780000gn/T/pip-build-xddct4w0/pypi-theme/.eggs/setuptools_scm-1.15.4-py3.5.egg/setuptools_scm/__init__.py", line 36, in _version_from_entrypoint
      File "/private/var/folders/14/9jkprxq17f30vp_2wbfw79780000gn/T/pip-build-xddct4w0/pypi-theme/.eggs/setuptools_scm-1.15.4-py3.5.egg/setuptools_scm/hacks.py", line 24, in parse_pip_egg_info
      File "/private/var/folders/14/9jkprxq17f30vp_2wbfw79780000gn/T/pip-build-xddct4w0/pypi-theme/.eggs/setuptools_scm-1.15.4-py3.5.egg/setuptools_scm/hacks.py", line 13, in parse_pkginfo
      File "/private/var/folders/14/9jkprxq17f30vp_2wbfw79780000gn/T/pip-build-xddct4w0/pypi-theme/.eggs/setuptools_scm-1.15.4-py3.5.egg/setuptools_scm/version.py", line 92, in meta
    AssertionError: cant parse version None

    ----------------------------------------
Command "/Users/dstufft/.virtualenvs/tmp-13d4c6e3ff2789/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/14/9jkprxq17f30vp_2wbfw79780000gn/T/pip-build-xddct4w0/pypi-theme/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/14/9jkprxq17f30vp_2wbfw79780000gn/T/pip-bfz_acz2-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/dstufft/.virtualenvs/tmp-13d4c6e3ff2789/include/site/python3.5/pypi-theme" failed with error code 1 in /private/var/folders/14/9jkprxq17f30vp_2wbfw79780000gn/T/pip-build-xddct4w0/pypi-theme/
```

What's interesting is it only actually raises an error with ``pip install -r`` not if I pass the requirement to pip itself (in that case it just whines about the version being non PEP 440), but I suspect that particular nuance is a pip problem.
