### ISSUE TITLE
Options specified as `unicode` strings break

### ISSUE THREAD

**Issue by andrewmwhite** [pypa/setuptools-scm#179]
Under 2.7 but using `unicode_literals` in `setup.py`, I get:

```
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/amw/Projects/stethoscope/stethoscope/setup.py", line 221, in <module>
        setuptools.setup(**setup_params)
      File "/Users/amw/.pyenv/versions/2.7.13/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/amw/.pyenv/versions/2.7.13/envs/scope-oss/lib/python2.7/site-packages/setuptools/dist.py", line 328, in __init__
        _Distribution.__init__(self, attrs)
      File "/Users/amw/.pyenv/versions/2.7.13/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/Users/amw/.pyenv/versions/2.7.13/envs/scope-oss/lib/python2.7/site-packages/setuptools/dist.py", line 461, in finalize_options
        ep.load()(self, ep.name, value)
      File "/Users/amw/.pyenv/versions/2.7.13/envs/scope-oss/lib/python2.7/site-packages/setuptools_scm/integration.py", line 22, in version_keyword
        dist.metadata.version = get_version(**value)
      File "/Users/amw/.pyenv/versions/2.7.13/envs/scope-oss/lib/python2.7/site-packages/setuptools_scm/__init__.py", line 125, in get_version
        local_scheme=local_scheme)
      File "/Users/amw/.pyenv/versions/2.7.13/envs/scope-oss/lib/python2.7/site-packages/setuptools_scm/version.py", line 166, in format_version
        main_version = version_scheme(version)
    TypeError: 'unicode' object is not callable
```

I believe this check is responsible since it's only looking for `str` and not `unicode`, as well:
https://github.com/pypa/setuptools_scm/blob/75897ba511010efaabf628217d34b589d9299c8f/setuptools_scm/version.py#L25

**Comment by RonnyPfannschmidt** [comment]
main reason this isn't fixed is that `unicode_literals` tends to break things badly on python2 and so its under the radar
