### ISSUE TITLE
git not found, but worked yesterday??

### ISSUE THREAD

**Issue by maphew** [pypa/setuptools-scm#182]
On Windows 7 I'm getting a git not found error, yet just yesterday I successfully built a wheel using setuptools_scm on this machine.

~~~
b:\apps\leo-editor>python setup.py check
b:\osgeo\apps\Python27\lib\site-packages\setuptools_scm\utils.py:108: UserWarning: 'git' was not fou
nd
  warnings.warn("%r was not found" % name)
Traceback (most recent call last):
  File "setup.py", line 79, in <module>
    'gui_scripts' : ['leo = leo.core.runLeo:run']
  File "b:\osgeo\apps\Python27\lib\distutils\core.py", line 112, in setup
    _setup_distribution = dist = klass(attrs)
  File "b:\osgeo\apps\Python27\lib\site-packages\setuptools\dist.py", line 269, in __init__
    _Distribution.__init__(self,attrs)
  File "b:\osgeo\apps\Python27\lib\distutils\dist.py", line 287, in __init__
    self.finalize_options()
  File "b:\osgeo\apps\Python27\lib\site-packages\setuptools\dist.py", line 324, in finalize_options
    ep.load()(self, ep.name, value)
  File "b:\osgeo\apps\Python27\lib\site-packages\setuptools_scm\integration.py", line 22, in version
_keyword
    dist.metadata.version = get_version(**value)
  File "b:\osgeo\apps\Python27\lib\site-packages\setuptools_scm\__init__.py", line 119, in get_versi
on
    parsed_version = _do_parse(root, parse)
  File "b:\osgeo\apps\Python27\lib\site-packages\setuptools_scm\__init__.py", line 97, in _do_parse
    "use git+https://github.com/user/proj.git#egg=proj" % root)
LookupError: setuptools-scm was unable to detect version for 'b:\\apps\\leo-editor'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sou
rces (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary
 metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git
+https://github.com/user/proj.git#egg=proj
~~~

but git is available:

~~~
b:\apps\leo-editor>git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   setup.py

no changes added to commit (use "git add" and/or "git commit -a")
~~~

**Comment by maphew** [comment]
Huh. Curious. The native win command `where` doesn't locate it either.

~~~
b:\apps\leo-editor>where python
b:\osgeo\bin\python.exe

b:\apps\leo-editor>where git
INFO: Could not find files for the given pattern(s).

b:\apps\leo-editor>path
PATH=b:\osgeo\bin;C:\Windows\system32;C:\Windows;C:\Windows\WBem;b:\osgeo\apps\msys\bin;b:\osgeo\apps\Python27\Scripts;"c:\Program Files\Git\cmd"

b:\apps\leo-editor>dir "c:\Program Files\Git\cmd"
 Volume in drive C is Programs
 Volume Serial Number is 02B4-627F

 Directory of c:\Program Files\Git\cmd

09/23/2016  12:15 PM    <DIR>          .
09/23/2016  12:15 PM    <DIR>          ..
09/03/2016  09:26 AM           150,760 git-gui.exe
09/03/2016  09:26 AM           150,760 git.exe
09/03/2016  09:26 AM           150,760 gitk.exe
09/03/2016  09:26 AM             3,052 start-ssh-agent.cmd
09/03/2016  09:26 AM             2,723 start-ssh-pageant.cmd
               5 File(s)        458,055 bytes
               2 Dir(s)  89,624,006,656 bytes free
~~~

**Comment by maphew** [comment]
Git Windows is working black magic. Not all .exe's in path are .exe's, or something. Adding `mingw64\bin` to PATH instead of the _other_ folders which also contain git.exe make it work:

    path=%path%;C:\Program Files\Git\mingw64\bin

Closing as invalid, upstream problem.

**Comment by RonnyPfannschmidt** [comment]
thanks for following up with all the details 👍
