### ISSUE TITLE
How to use `write_to_template` parameter?

### ISSUE THREAD

**Issue by maphew** [pypa/setuptools-scm#184]
Would someone please show an example or two of how to use the `write_to_template` parameter? 

I've tried using some of the patterns listed in https://github.com/pypa/setuptools_scm#default-versioning-scheme but they exit with KeyError

~~~
scm_version_options = {
    'write_to_template': '{tag}+dYYYMMMDD',
    'write_to' : 'version.py'
    }
setup(
    name = 'leo',
    use_scm_version = scm_version_options,
    setup_requires=['setuptools_scm'],
    ...snip...
    )
~~~

~~~
>python setup.py check
Traceback (most recent call last):
  File "setup.py", line 81, in <module>
    'gui_scripts' : ['leo = leo.core.runLeo:run']
  File "C:\apps\Miniconda3\lib\distutils\core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "C:\apps\Miniconda3\lib\site-packages\setuptools\dist.py", line 338, in __init__
    _Distribution.__init__(self, attrs)
  File "C:\apps\Miniconda3\lib\distutils\dist.py", line 281, in __init__
    self.finalize_options()
  File "C:\apps\Miniconda3\lib\site-packages\setuptools\dist.py", line 471, in finalize_options
    ep.load()(self, ep.name, value)
  File "C:\apps\Miniconda3\lib\site-packages\setuptools_scm\integration.py", line 22, in version_keyword
    dist.metadata.version = get_version(**value)
  File "C:\apps\Miniconda3\lib\site-packages\setuptools_scm\__init__.py", line 130, in get_version
    template=write_to_template)
  File "C:\apps\Miniconda3\lib\site-packages\setuptools_scm\__init__.py", line 50, in dump_version
    dump = template.format(version=version)
KeyError: 'tag'
~~~

**Comment by RonnyPfannschmidt** [comment]
thanks for noting the documentation issue - the write_to template currently only supports the variable `version` which is a string

its being carried out in https://github.com/pypa/setuptools_scm/blob/master/setuptools_scm/__init__.py#L41
