### ISSUE TITLE
tags with dashes get mangled

### ISSUE THREAD

**Issue by twall** [pypa/setuptools-scm#266]
I want to be able to tag my git repo with "1.0.0-rc1".  That version should be acceptable to setuptools_scm independently of "distance", "hash", and "dirty" suffixes.

Doing so results in an error (sample tag is "3.3.1-rc26"):

```
looking for ep setuptools_scm.parse_scm_fallback .
root '/Users/twall/plex/rd'
looking for ep setuptools_scm.parse_scm /Users/twall/plex/rd
found ep .git = setuptools_scm.git:parse
cmd 'git rev-parse --show-toplevel'
out b'/Users/twall/plex/rd\n'
real root /Users/twall/plex/rd
cmd 'git describe --dirty --tags --long --match *.*'
out b'3.3.1-rc26-0-g9df187b\n'
cmd 'git rev-parse --abbrev-ref HEAD'
out b'pyplex\n'
tag 3.3.1-rc26
version <LegacyVersion('rc26')>
version None
Traceback (most recent call last):
  File "setup.py", line 46, in <module>
    entry_points = {
  File "/Users/twall/plex/rd/search/.venv-3.6/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/anaconda3/lib/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/Users/twall/plex/rd/search/.venv-3.6/lib/python3.6/site-packages/setuptools/dist.py", line 370, in __init__
    k: v for k, v in attrs.items()
  File "/anaconda3/lib/python3.6/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/Users/twall/plex/rd/search/.venv-3.6/lib/python3.6/site-packages/setuptools/dist.py", line 529, in finalize_options
    ep.load()(self, ep.name, value)
  File "/Users/twall/plex/rd/search/.venv-3.6/lib/python3.6/site-packages/setuptools_scm/integration.py", line 22, in version_keyword
    dist.metadata.version = get_version(**value)
  File "/Users/twall/plex/rd/search/.venv-3.6/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 119, in get_version
    parsed_version = _do_parse(root, parse)
  File "/Users/twall/plex/rd/search/.venv-3.6/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 83, in _do_parse
    version = version_from_scm(root) or _version_from_entrypoint(
  File "/Users/twall/plex/rd/search/.venv-3.6/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 31, in version_from_scm
    return _version_from_entrypoint(root, 'setuptools_scm.parse_scm')
  File "/Users/twall/plex/rd/search/.venv-3.6/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 36, in _version_from_entrypoint
    version = ep.load()(root)
  File "/Users/twall/plex/rd/search/.venv-3.6/lib/python3.6/site-packages/setuptools_scm/git.py", line 128, in parse
    return meta(tag, node=node, dirty=dirty, branch=branch)
  File "/Users/twall/plex/rd/search/.venv-3.6/lib/python3.6/site-packages/setuptools_scm/version.py", line 135, in meta
    assert tag is not None, 'cant parse version %s' % tag
AssertionError: cant parse version None
```

The `SemVer` description seems to allow nearly arbitrary strings for `www` in `x.y.z-www`, so I would expect such tags to work.

Note that "3.3.1.rc26" sort of works, resulting in a modified version of "3.3.1rc26".

**Comment by RonnyPfannschmidt** [comment]
https://www.python.org/dev/peps/pep-0440/ is the standard for python versions - a dash is not permissible
https://www.python.org/dev/peps/pep-0440/#semantic-versioning declares them invalid for the version field

**Comment by RonnyPfannschmidt** [comment]
but i do note that the git version spiting is indeed broken in the face of dashes and i shall rectify that issue by using a dash using version that is permissible according to the pep

**Comment by RonnyPfannschmidt** [comment]
while debugging i noted that all versions of setuptools i tested on python3 normalize `3.3.1-rc26` to the correct dash-free one - my misstake in understanding based on prior comments in the old issue, i'd like to appologize

**Comment by RonnyPfannschmidt** [comment]
the origin is https://github.com/pypa/setuptools_scm/commit/dd1b36a804d939e3fd178c6f46e9003aecfb06e1 - when the pep440 support came in i did not correctly verify the prefix matching feature

**Comment by RonnyPfannschmidt** [comment]
initial feature was implemented in https://github.com/pypa/setuptools_scm/commit/8472332f6bccb317164feed7daeed0b6bd88aefb

arbitrary text prefixes should be correctly tested against digits,
the requirement for the 'v' stripping should be re-evaluated as setuptools now uses packaging
