### ISSUE TITLE
errors with conda build

### ISSUE THREAD

**Issue by marcelotrevisani** [pypa/setuptools-scm#280]
Hello, I created a recipe for a project and I'm using ``setuptools_scm``. For this project my ``source`` section of my recipe is like:
```
source:
  git_tag: my-branch
  git_url: PATH-to-git.git
```

my ``script`` section is:

```
  script:
    - python -m pip install --no-deps --ignore-installed src/pythonKarabo
```

where is located my ``setup.py``

When I try to build that using ``conda build`` I'm facing this error:

```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-mmcl8gq4-build/setup.py", line 72, in <module>
        'TestDevice=karabo.middlelayer_api.tests.bounddevice:TestDevice'
      File "/home/trevisan/miniconda3/conda-bld/python-karabo_1531408265571/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.6/site-packages/setuptools/__init__.py", line 131, in setup
        return distutils.core.setup(**attrs)
      File "/home/trevisan/miniconda3/conda-bld/python-karabo_1531408265571/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/trevisan/miniconda3/conda-bld/python-karabo_1531408265571/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.6/site-packages/setuptools/dist.py", line 370, in __init__
        k: v for k, v in attrs.items()
      File "/home/trevisan/miniconda3/conda-bld/python-karabo_1531408265571/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.6/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/home/trevisan/miniconda3/conda-bld/python-karabo_1531408265571/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.6/site-packages/setuptools/dist.py", line 529, in finalize_options
        ep.load()(self, ep.name, value)
      File "/home/trevisan/miniconda3/conda-bld/python-karabo_1531408265571/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.6/site-packages/setuptools_scm/integration.py", line 22, in version_keyword
        dist.metadata.version = get_version(**value)
      File "/home/trevisan/miniconda3/conda-bld/python-karabo_1531408265571/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 119, in get_version
        parsed_version = _do_parse(root, parse)
      File "/home/trevisan/miniconda3/conda-bld/python-karabo_1531408265571/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 97, in _do_parse
        "use git+https://github.com/user/proj.git#egg=proj" % root)

   LookupError: setuptools-scm was unable to detect version for '/tmp/pip-mmcl8gq4-build'.
    
    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
    
    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

```

**Comment by RonnyPfannschmidt** [comment]
@marcelotrevisani its not clear to me how you are building (im clueless about conda), but its clear that the build mechanism killed the metadata setuptools_scm neeeds

i believe @nicoddemus handles the conda builds for pytest, perhaps he an provide some insight

**Comment by nicoddemus** [comment]
@marcelotrevisani try using `git_rev` instead, that's how we do in [conda-devenv](https://github.com/conda-forge/conda-devenv-feedstock/blob/master/recipe/meta.yaml#L8-L10).

Are you tagging the repository?

**Comment by marcelotrevisani** [comment]
Yes, we are tagging the repository. But, I need to checkout from a branch. I also tried to use ``git_rev`` but I got the same error

**Comment by marcelotrevisani** [comment]
It strange because if I execute:

```
python -m pip install --no-deps --ignore-installed .
```

locally it will return to me the same error

**Comment by nicoddemus** [comment]
> It strange because if I execute

Why is that strange? You are getting the same behavior, that's what I would expect...

**Comment by marcelotrevisani** [comment]
Indeed, I agree with you, haha

**Comment by marcelotrevisani** [comment]
I found the problem

I'm using:
```
use_scm_version={'root': '../..', 'write_to': path_version}
```
and this variable ``path_version`` I get using the ``pathlib`` library
So I do:
```
current_folder = Path(__file__).parent
path_version = current_folder.joinpath('project', '_version.py')
```

If I execute using 
```
python -m pip install --no-deps --ignore-installed .
```

It will return to me a temporary folder, if I use 
```
python setup.py install
```

It will get the correct one

**Comment by marcelotrevisani** [comment]
Does anyone have a clue why this happened?

**Comment by RonnyPfannschmidt** [comment]
pip does make a copy to a random place it seems

**Comment by nicoddemus** [comment]
Are you using which pip version? Try <10, pip 10 introduced a new build isolation feature which I'm not sure works with conda quite yet.

**Comment by RonnyPfannschmidt** [comment]
pip does currently not correctly support python projects in subdirs of git repos, i pinged @dstufft on irc and will take a look at working details out

**Comment by marcelotrevisani** [comment]
> Are you using which pip version?

I used ``pip 9.0.3``

**Comment by marcelotrevisani** [comment]
Thanks for the explanation @RonnyPfannschmidt . So, it will not be possible to install that using pip. But, I also having some problems when I tried to use

```
  script:
    - cd src/pythonKarabo
    - python setup.py dist_egg
    - python setup.py install
```
and I'm having this error
```
Traceback (most recent call last):
  File "/home/trevisan/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/trevisan/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/home/trevisan/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/home/trevisan/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 200, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/trevisan/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 2177, in build_tree
    notest=notest,
  File "/home/trevisan/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1417, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir, stats=build_stats)
  File "/home/trevisan/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 310, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/home/trevisan/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 290, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/home/trevisan/miniconda3/conda-bld/python-karabo_1531471865705/work/conda_build.sh']' returned non-zero exit status 1.
```

**Comment by marcelotrevisani** [comment]
@RonnyPfannschmidt thanks for the explanation. So, it will not be possible to use ``pip`` to install that, right!?

The workaround was to use
```
- cd src/pythonKarabo
- python setup.py bdist_egg
- python setup.py install
```
inside of my build script recipe

Can I close this @RonnyPfannschmidt ?

**Comment by RonnyPfannschmidt** [comment]
@marcelotrevisani i would advise to do a bdist_wheel and pip installing the wheel

else you get a really broken metadata setup due to easy_install being in the install command

**Comment by nicoddemus** [comment]
Also, would be better then to use a `pip` to install the wheel or doesn't matter @RonnyPfannschmidt?

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus pip is currently the only sound installer for wheels im aware of

**Comment by marcelotrevisani** [comment]
@RonnyPfannschmidt , Just to be sure, do you mean:

```
- python setup.py bdist_wheel
- pip install -e .
```
?

**Comment by RonnyPfannschmidt** [comment]
@marcelotrevisani no - `pip install dist/*.whl`

**Comment by marcelotrevisani** [comment]
@RonnyPfannschmidt Can I close this?

**Comment by RonnyPfannschmidt** [comment]
@marcelotrevisani if the issue is sorted out for you and everything works now please do so ^^

**Comment by marcelotrevisani** [comment]
The problem is with ``pip`` and not with ``setuptools_scm``. Thanks for help me!

The discussion helped me to do an workaround, so, it's working now. :)

**Comment by willirath** [comment]
For reference, this issue was the essential hint for solving setuptools_scm, setuptools_scm_git_archive from a Gitub-release for conda-forge.  To capture Windows builds, the wildcard `dist/*whl` won't do:

https://github.com/conda-forge/parcels-feedstock/blob/a57c414d5213415e442048b6ade683015ca3c951/recipe/meta.yaml#L17_L18

**Comment by marcelotrevisani** [comment]
I'm happy that helped! :)
