### ISSUE TITLE
AttributeError: 'str' object has no attribute 'absolute_root'

### ISSUE THREAD

**Issue by pitrou** [pypa/setuptools-scm#281]
It seems that our Appveyor builds have started failing with the newly-released 3.0.0:
```
(arrow) C:\projects\arrow\python>python setup.py build_ext     install -q --single-version-externally-managed --record=record.text     bdist_wheel -q   || exit /B 
Traceback (most recent call last):
  File "setup.py", line 545, in <module>
    url="https://arrow.apache.org/"
  File "C:\Miniconda36-x64\envs\arrow\lib\site-packages\setuptools\__init__.py", line 131, in setup
    return distutils.core.setup(**attrs)
  File "C:\Miniconda36-x64\envs\arrow\lib\distutils\core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "C:\Miniconda36-x64\envs\arrow\lib\site-packages\setuptools\dist.py", line 370, in __init__
    k: v for k, v in attrs.items()
  File "C:\Miniconda36-x64\envs\arrow\lib\distutils\dist.py", line 281, in __init__
    self.finalize_options()
  File "C:\Miniconda36-x64\envs\arrow\lib\site-packages\setuptools\dist.py", line 529, in finalize_options
    ep.load()(self, ep.name, value)
  File "c:\projects\arrow\python\.eggs\setuptools_scm-3.0.0-py3.6.egg\setuptools_scm\integration.py", line 23, in version_keyword
    dist.metadata.version = get_version(**value)
  File "c:\projects\arrow\python\.eggs\setuptools_scm-3.0.0-py3.6.egg\setuptools_scm\__init__.py", line 128, in get_version
    parsed_version = _do_parse(config)
  File "c:\projects\arrow\python\.eggs\setuptools_scm-3.0.0-py3.6.egg\setuptools_scm\__init__.py", line 73, in _do_parse
    parse_result = _call_entrypoint_fn(config, config.parse)
  File "c:\projects\arrow\python\.eggs\setuptools_scm-3.0.0-py3.6.egg\setuptools_scm\__init__.py", line 36, in _call_entrypoint_fn
    return fn(config.absolute_root)
  File "setup.py", line 496, in parse_version
    version = setuptools_scm.git.parse(root, describe)
  File "c:\projects\arrow\python\.eggs\setuptools_scm-3.0.0-py3.6.egg\setuptools_scm\git.py", line 96, in parse
    wd = GitWorkdir.from_potential_worktree(config.absolute_root)
AttributeError: 'str' object has no attribute 'absolute_root'
```

**Comment by RonnyPfannschmidt** [comment]
@pitrou thanks for the note, its a breakage i missed but one that can be sorted out quickly

**Comment by pitrou** [comment]
Thanks for the quick notice :-)

**Comment by RonnyPfannschmidt** [comment]
fix implemented, preparing the next release

**Comment by RonnyPfannschmidt** [comment]
waiting for ci, afterwards i will tag

**Comment by RonnyPfannschmidt** [comment]
merged, release triggerd

@pitrou please check if it works in about 10-15 depending on pypi delay

**Comment by pitrou** [comment]
Seems fixed in https://ci.appveyor.com/project/pitrou/arrow/build/1.0.543
Thanks @RonnyPfannschmidt !
