### ISSUE TITLE
AssertionError: cant parse version apache-arrow-0.9.0

### ISSUE THREAD

**Issue by pitrou** [pypa/setuptools-scm#284]
I'm getting the following error with 3.0.1:
```
/home/antoine/miniconda3/envs/pyarrow27/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
/home/antoine/miniconda3/envs/pyarrow27/lib/python2.7/site-packages/setuptools_scm/version.py:92: UserWarning: tag 'apache-arrow-0.9.0' no version found
  warnings.warn("tag %r no version found" % (tag,))
Traceback (most recent call last):
  File "setup.py", line 545, in <module>
    url="https://arrow.apache.org/"
  File "/home/antoine/miniconda3/envs/pyarrow27/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/home/antoine/miniconda3/envs/pyarrow27/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/antoine/miniconda3/envs/pyarrow27/lib/python2.7/site-packages/setuptools/dist.py", line 372, in __init__
    _Distribution.__init__(self, attrs)
  File "/home/antoine/miniconda3/envs/pyarrow27/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/home/antoine/miniconda3/envs/pyarrow27/lib/python2.7/site-packages/setuptools/dist.py", line 528, in finalize_options
    ep.load()(self, ep.name, value)
  File "/home/antoine/miniconda3/envs/pyarrow27/lib/python2.7/site-packages/setuptools_scm/integration.py", line 23, in version_keyword
    dist.metadata.version = get_version(**value)
  File "/home/antoine/miniconda3/envs/pyarrow27/lib/python2.7/site-packages/setuptools_scm/__init__.py", line 128, in get_version
    parsed_version = _do_parse(config)
  File "/home/antoine/miniconda3/envs/pyarrow27/lib/python2.7/site-packages/setuptools_scm/__init__.py", line 73, in _do_parse
    parse_result = _call_entrypoint_fn(config, config.parse)
  File "/home/antoine/miniconda3/envs/pyarrow27/lib/python2.7/site-packages/setuptools_scm/__init__.py", line 36, in _call_entrypoint_fn
    return fn(config.absolute_root)
  File "setup.py", line 496, in parse_version
    version = setuptools_scm.git.parse(root, describe)
  File "/home/antoine/miniconda3/envs/pyarrow27/lib/python2.7/site-packages/setuptools_scm/git.py", line 131, in parse
    branch=branch,
  File "/home/antoine/miniconda3/envs/pyarrow27/lib/python2.7/site-packages/setuptools_scm/version.py", line 184, in meta
    assert parsed_version is not None, "cant parse version %s" % tag
AssertionError: cant parse version apache-arrow-0.9.0
```

**Comment by RonnyPfannschmidt** [comment]
@pitrou please provide the output while the env var `SETUPTOOLS_SCM_DEBUG=1` is set id like to get more detail

based on output it seems to be a second regression based on the version regex no longer correctly dropping the complete prefix, which i can probably fix just as quickly

this indicates that i need to be more trough on the tests for features that come in

**Comment by pitrou** [comment]
Here you are:
```
/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
looking for ep setuptools_scm.parse_scm_fallback .
root '/home/antoine/arrow/python'
root '/home/antoine/arrow'
root '/home/antoine/arrow'
root '/home/antoine/arrow'
cmd 'git rev-parse --show-toplevel'
out b'/home/antoine/arrow\n'
real root /home/antoine/arrow
cmd "git describe --dirty --tags --long  --match 'apache-arrow-[0-9]*'"
out b'apache-arrow-0.9.0-401-g859ca93\n'
cmd 'git rev-parse --abbrev-ref HEAD'
out b'ARROW-2711-infer-empty-list\n'
tag apache-arrow-0.9.0
tag 'apache-arrow-0.9.0' parsed to None
/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/site-packages/setuptools_scm/version.py:92: UserWarning: tag 'apache-arrow-0.9.0' no version found
  warnings.warn("tag %r no version found" % (tag,))
version apache-arrow-0.9.0 -> None
Traceback (most recent call last):
  File "setup.py", line 545, in <module>
    url="https://arrow.apache.org/"
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/site-packages/setuptools/dist.py", line 333, in __init__
    _Distribution.__init__(self, attrs)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/site-packages/setuptools/dist.py", line 476, in finalize_options
    ep.load()(self, ep.name, value)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/site-packages/setuptools_scm/integration.py", line 23, in version_keyword
    dist.metadata.version = get_version(**value)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 128, in get_version
    parsed_version = _do_parse(config)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 73, in _do_parse
    parse_result = _call_entrypoint_fn(config, config.parse)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 36, in _call_entrypoint_fn
    return fn(config.absolute_root)
  File "setup.py", line 496, in parse_version
    version = setuptools_scm.git.parse(root, describe)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/site-packages/setuptools_scm/git.py", line 131, in parse
    branch=branch,
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.6/site-packages/setuptools_scm/version.py", line 184, in meta
    assert parsed_version is not None, "cant parse version %s" % tag
AssertionError: cant parse version apache-arrow-0.9.0
```

**Comment by RonnyPfannschmidt** [comment]
thanks, it seems its indeed the regex, test and patch incoming

**Comment by RonnyPfannschmidt** [comment]
#285 should fix, waiting for ci, will follow up with merge and release
