### ISSUE TITLE
in version 3 tags_to_versions returns a iterator instead of a list

### ISSUE THREAD

**Issue by chrisphilip322** [pypa/setuptools-scm#286]
I get this issue when using `setuptools>=3` and `<=3.0.2`

```
(venv) macbeth $ pip install --no-binary :all: cheroot
Looking in indexes: http://artifactory.factset.com/artifactory/api/pypi/python/simple/
Collecting cheroot
  Downloading http://artifactory.factset.com/artifactory/api/pypi/python/packages/a3/fe/60797128186577348abc612fdd1011e737d7f01137c0c927dba489360fc3/cheroot-6.3.3.tar.gz (73kB)
    100% |████████████████████████████████| 81kB 65.5MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-otm5evwb/cheroot/setup.py", line 113, in <module>
        setuptools.setup(**params)
      File "/REDACTED_DIR/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 131, in setup
        return distutils.core.setup(**attrs)
      File "/home/user/macbeth/.local/share/pyenv/versions/3.6.4/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/REDACTED_DIR/venv/lib/python3.6/site-packages/setuptools/dist.py", line 370, in __init__
        k: v for k, v in attrs.items()
      File "/home/user/macbeth/.local/share/pyenv/versions/3.6.4/lib/python3.6/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/REDACTED_DIR/venv/lib/python3.6/site-packages/setuptools/dist.py", line 529, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/pip-install-otm5evwb/cheroot/.eggs/setuptools_scm-3.0.2-py3.6.egg/setuptools_scm/integration.py", line 23, in version_keyword
        dist.metadata.version = get_version(**value)
      File "/tmp/pip-install-otm5evwb/cheroot/.eggs/setuptools_scm-3.0.2-py3.6.egg/setuptools_scm/__init__.py", line 135, in get_version
        parsed_version = _do_parse(config)
      File "/tmp/pip-install-otm5evwb/cheroot/.eggs/setuptools_scm-3.0.2-py3.6.egg/setuptools_scm/__init__.py", line 88, in _do_parse
        config, "setuptools_scm.parse_scm"
      File "/tmp/pip-install-otm5evwb/cheroot/.eggs/setuptools_scm-3.0.2-py3.6.egg/setuptools_scm/__init__.py", line 45, in _version_from_entrypoint
        version = _call_entrypoint_fn(config, ep.load())
      File "/tmp/pip-install-otm5evwb/cheroot/.eggs/setuptools_scm-3.0.2-py3.6.egg/setuptools_scm/__init__.py", line 40, in _call_entrypoint_fn
        return fn(config.absolute_root)
      File "/tmp/pip-install-otm5evwb/cheroot/.eggs/setuptools_scm_git_archive-1.0-py3.6.egg/setuptools_scm_git_archive/__init__.py", line 21, in parse
        return archival_to_version(data)
      File "/tmp/pip-install-otm5evwb/cheroot/.eggs/setuptools_scm_git_archive-1.0-py3.6.egg/setuptools_scm_git_archive/__init__.py", line 15, in archival_to_version
        return meta(versions[0])
    TypeError: 'filter' object is not subscriptable

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-otm5evwb/cheroot/
(venv) macbeth $ pip freeze --all
pip==18.0
setuptools==40.0.0
(venv) macbeth $ python --version
Python 3.6.4
```

**Comment by RonnyPfannschmidt** [comment]
found the issue - i missed the turning of a expression into a generator, will release a fix including a test soon

**Comment by chrisphilip322** [comment]
Any chance we can reopen this issue until you release the fixes @RonnyPfannschmidt ? My build at work still can't build anything that uses `setuptools_scm`

**Comment by RonnyPfannschmidt** [comment]
@macbeth322 sure, the plan was to do a release earlier, but i botched the release process while doing that - im going to fix it this weekend

**Comment by RonnyPfannschmidt** [comment]
closing as 3.0.4 got released
