### ISSUE TITLE
3.0.3 does not have wheels on pypi

### ISSUE THREAD

**Issue by sbidoul** [pypa/setuptools-scm#289]
Hi @RonnyPfannschmidt 

Release 3.0.3 only has the sdist release on pypi. This is apparently breaking builds that place requirements on setuptools_scm version (such as >= 2.1) because the sdist build does not know it's own version.

```
    Installed /home/gitlab-runner/builds/24ed0041/0/acsone/project/src/odoo-addons-enterprise/setup/.eggs/setuptools_odoo-2.3.0-py3.5.egg
    Searching for setuptools_scm>=2.1
    Reading https://pypi.python.org/simple/setuptools_scm/
    Downloading https://files.pythonhosted.org/packages/7c/a5/abe6f737d4220cbfd47db23e1d3e67f5a30e0ba153a61a3f9497a93e5183/setuptools_scm-3.0.3.tar.gz#sha256=9def056f01597086ea9d1a6eb50da67682162132b7300f437707070be8a18a60
    Best match: setuptools-scm 3.0.3
    Processing setuptools_scm-3.0.3.tar.gz
    Writing /tmp/easy_install-0b3nyngs/setuptools_scm-3.0.3/setup.cfg
    Running setuptools_scm-3.0.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-0b3nyngs/setuptools_scm-3.0.3/egg-dist-tmp-7238unuu
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'use_scm_version'
      warnings.warn(msg)
    warning: no previously-included files found matching '*.nix'
    warning: no previously-included files found matching 'appveyor.yml'
    warning: no previously-included files found matching '.travis.yaml'
    warning: no previously-included files found matching '.pre-commit-config.yaml'
    Moving setuptools_scm-0.0.0-py3.5.egg to /home/gitlab-runner/builds/24ed0041/0/acsone/project/src/odoo-addons-enterprise/setup/.eggs
    
    Installed /home/gitlab-runner/builds/24ed0041/0/acsone/project/src/odoo-addons-enterprise/setup/.eggs/setuptools_scm-0.0.0-py3.5.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/gitlab-runner/builds/24ed0041/0/acsone/project/src/odoo-addons-enterprise/setup/setup.py", line 10, in <module>
        'OpenSSL': 'pyOpenSSL>=17.5.0',
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/gitlab-runner/builds/24ed0041/0/acsone/project/venv-acsoo/lib/python3.5/site-packages/setuptools/dist.py", line 316, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/gitlab-runner/builds/24ed0041/0/acsone/project/venv-acsoo/lib/python3.5/site-packages/setuptools/dist.py", line 371, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/gitlab-runner/builds/24ed0041/0/acsone/prfoject/venv-acsoo/lib/python3.5/site-packages/pkg_resources/__init__.py", line 849, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'setuptools_scm>=2.1' distribution was not found and is required by setuptools-odoo
```

**Comment by RonnyPfannschmidt** [comment]
the release will be pulled, i made a structural error on travis and all builds did the wrong thing

**Comment by RonnyPfannschmidt** [comment]
release 3.0.3 is deleted - i will follow up with 3.0.4 sometime today after im sure travis is no longer a mess

**Comment by sbidoul** [comment]
Thanks a lot for the quick reaction!
