### ISSUE TITLE
prevent building archives when no VCS repo is there

### ISSUE THREAD

**Issue by hpk42** [pypa/setuptools-scm#31]
When using setuptools_scm it should bail out if it can't find any VCS repo.  Instead it currently creates version numbers such as "0.0.0", not telling the user it failed to get the repo.

**Comment by StephanErb** [comment]
Link to a related issue in devpi: https://bitbucket.org/hpk42/devpi/issues/246/import-error-when-importing-with-devpi

**Comment by RonnyPfannschmidt** [comment]
could you check if the refereed pr is roughly what you'd expect?

**Comment by StephanErb** [comment]
From reading the code, the patch looks good. However, I cannot test:

```
→ python setup.py egg_info
important note:

the setup of setuptools_scm is self-using,
the first execution of `python setup.py egg_info`
will generate partial data
its critical to run `python setup.py egg_info`
once before running sdist or easy_install on a fresh checkouts

pip usage is recommended

Traceback (most recent call last):
  File "setup.py", line 113, in <module>
    setuptools.setup(**arguments)
  File "/usr/lib/python2.7/distutils/core.py", line 112, in setup
    _setup_distribution = dist = klass(attrs)
  File "/tmp/pawesome/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 272, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/tmp/pawesome/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 327, in finalize_options
    ep.load()(self, ep.name, value)
  File "/tmp/pawesome/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/tmp/pawesome/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2365, in resolve
    raise ImportError(str(exc))
ImportError: 'module' object has no attribute 'setuptools_version_keyword'

```

**Comment by RonnyPfannschmidt** [comment]
please uninstall the previously installed version

**Comment by StephanErb** [comment]
Pull request works as expected. Thanks!
