### ISSUE TITLE
LookupError: setuptools-scm was unable to detect version

### ISSUE THREAD

**Issue by vezeli** [pypa/setuptools-scm#354]
Hey, I am trying to setup `setuptools_scm` to work properly for my project but I am having problems with LookupError.

```
Traceback (most recent call last):
  File "/home/vezeli/python/test_maillinter/testvenv/bin/maillinter", line 11, in <module>
    load_entry_point('maillinter==0.4.1.dev10+gfa3dc1a.d20190808', 'console_scripts', 'maillinter')()
  File "/home/vezeli/python/test_maillinter/testvenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/vezeli/python/test_maillinter/testvenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/home/vezeli/python/test_maillinter/testvenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/home/vezeli/python/test_maillinter/testvenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/vezeli/python/test_maillinter/testvenv/lib/python3.6/site-packages/maillinter-0.4.1.dev10+gfa3dc1a.d20190808-py3.6.egg/maillinter/__init__.py", line 3, in <module>
    __version__ = get_version(root="../..", relative_to=__file__)
  File "/home/vezeli/python/test_maillinter/.eggs/setuptools_scm-3.3.3-py3.6.egg/setuptools_scm/__init__.py", line 150, in get_version
    parsed_version = _do_parse(config)
  File "/home/vezeli/python/test_maillinter/.eggs/setuptools_scm-3.3.3-py3.6.egg/setuptools_scm/__init__.py", line 113, in _do_parse
    "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
LookupError: setuptools-scm was unable to detect version for '/home/vezeli/python/test_maillinter/testvenv/lib/python3.6/site-packages'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```

I am following the documentation and in setup.py I have 
```
setuptools.setup(...
    use_scm_version=True,
    setup_requires=["setuptools_scm"],
)
```

The project has src structure and src/projectname/\_\_init\_\_.py contains 
```
 from setuptools_scm import get_version                                          

__version__ = get_version(root="../..", relative_to=__file__)
```

Result of `git tag`:
```
0.2.0
0.3.0
0.4.0
```

I use also `SETUPTOOLS_SCM_DEBUG=1 python setup.py --version` and the result is 
```
root '/home/vezeli/python/test_maillinter'
root '/home/vezeli/python/test_maillinter'
root '/home/vezeli/python/test_maillinter'
looking for ep setuptools_scm.parse_scm /home/vezeli/python/test_maillinter
found ep .git = setuptools_scm.git:parse
cmd 'git rev-parse --show-toplevel'
out b'/home/vezeli/python/test_maillinter\n'
real root /home/vezeli/python/test_maillinter
cmd 'git describe --dirty --tags --long --match *.*'
out b'0.4.0-10-gfa3dc1a-dirty\n'
cmd 'git rev-parse --abbrev-ref HEAD'
out b'master\n'
tag 0.4.0
tag '0.4.0' parsed to {'version': '0.4.0', 'prefix': '', 'suffix': ''}
version pre parse 0.4.0
version <Version('0.4.0')>
version 0.4.0 -> 0.4.0
scm version <ScmVersion 0.4.0 d=10 n=gfa3dc1a d=True b=master>
config {'version_scheme': 'guess-next-dev', 'local_scheme': 'node-and-date'}
ep ('setuptools_scm.version_scheme', 'guess-next-dev')
ep found: guess-next-dev
ep ('setuptools_scm.local_scheme', 'node-and-date')
ep found: node-and-date
version 0.4.1.dev10
local_version +gfa3dc1a.d20190808
0.4.1.dev10+gfa3dc1a.d20190808
```

I am sorry if I am missing something obvious and I would really appreciate your help to make the get_version running.

**Comment by RonnyPfannschmidt** [comment]
its discouraged to have get_version as part of the normal source code,
as it will practically completely break as soon as you do a normal install of the project

and the trace-back is indeed the thing falling apart from a installed location

also note that using `setup.py install` is superseded since a while now, please use `pip install` or `pip install -e`

**Comment by vezeli** [comment]
OK, now it is clear. Thanks so much for your help. 

So the proper way to get the version in the package is to use something like:

```
from pkg_resources import get_distribution, DistributionNotFound
try:
    __version__ = get_distribution(__name__).version
except DistributionNotFound:
    # package is not installed
    pass
```

just like documentation specifies.  I included the solution to the issue for the sake of completeness in case anyone else reads it.
