### ISSUE TITLE
_bump_regex fails with invalid version tag

### ISSUE THREAD

**Issue by EricSt-Amand-opalrt** [pypa/setuptools-scm#362]
Basically, I have a tag in my git repo which is `1.0.z` and setuptools_scm seems to not like it.  It fails because the tag does not end with a number.  I think this should be relaxed somehow ... ? or I miss something ?

```
python setup.py build
Traceback (most recent call last):
  File "setup.py", line 47, in <module>
    main()
  File "setup.py", line 42, in main
    setup_requires=SETUP_REQUIRES,
  File "C:\PYTHON2714X32\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "C:\PYTHON2714X32\lib\distutils\core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "C:\PYTHON2714X32\lib\site-packages\setuptools\dist.py", line 447, in __init__
    k: v for k, v in attrs.items()
  File "C:\PYTHON2714X32\lib\distutils\dist.py", line 287, in __init__
    self.finalize_options()
  File "C:\PYTHON2714X32\lib\site-packages\setuptools\dist.py", line 735, in finalize_options
    ep.load()(self, ep.name, value)
  File "C:\PYTHON2714X32\lib\site-packages\setuptools_scm\integration.py", line 17, in version_keyword
    dist.metadata.version = get_version(**value)
  File "C:\PYTHON2714X32\lib\site-packages\setuptools_scm\__init__.py", line 154, in get_version
    parsed_version, version_scheme=version_scheme, local_scheme=local_scheme
  File "C:\PYTHON2714X32\lib\site-packages\setuptools_scm\version.py", line 304, in format_version
    main_version = version_scheme(version)
  File "C:\PYTHON2714X32\lib\site-packages\setuptools_scm\version.py", line 236, in guess_next_dev_version
    return version.format_next_version(guess_next_version)
  File "C:\PYTHON2714X32\lib\site-packages\setuptools_scm\version.py", line 182, in format_next_version
    guessed = guess_next(self.tag, **kw)
  File "C:\PYTHON2714X32\lib\site-packages\setuptools_scm\version.py", line 210, in guess_next_version
    return _bump_dev(version) or _bump_regex(version)
  File "C:\PYTHON2714X32\lib\site-packages\setuptools_scm\version.py", line 228, in _bump_regex
    prefix, tail = re.match(r"(.*?)(\d+)$", version).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```

I tried `use_scm_version={'fallback_version':'0.0.0'}` in setup.py, but seems to have no effect.
Any advice ?

**Comment by RonnyPfannschmidt** [comment]
i believe you can use the post_release version scheme to work around it

its not going to loosen - its impossible to guess a good next version for a bad tag,
however the error could be better

**Comment by EricSt-Amand-opalrt** [comment]
Well, if a bad tag is used, why not try to use the next found tag ?  It always uses the latest found.  Maybe what I am saying is related to #338 ?

**Comment by RonnyPfannschmidt** [comment]
if you find a way to do that in git describe, i'm happy to add it, else not

**Comment by EricSt-Amand-opalrt** [comment]
OK I have 2 comments:

1. Using `git describe --tags --exclude *z` I get another tag selected.  The tag is `1.0.0-rc.1` and git describe returns this to me `1.0.0-rc.1-6-ge314434`.  So if I can stick that command in setuptools_scm that could help.
1. Using the workaround you suggested: `use_scm_version={'version_scheme': 'post-release'}` I can make it work and the version boils down to `1.0.z.post6+ge314434.d20191017`.  A UserWarning is thrown at me `UserWarning: The version specified ('1.0.z.post6+ge314434.d20191017') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.` but I am ok with it (it's only a warning heh ? ;) )

**Comment by EricSt-Amand-opalrt** [comment]
Indeed, using `use_scm_version={'git_describe_command': 'git describe --tags --exclude *z'}` works without any warning.

**Comment by EricSt-Amand-opalrt** [comment]
Closing the issue, I have a suitable workaround for now, thanks for the support!

**Comment by RonnyPfannschmidt** [comment]
thanks for the followup
