### ISSUE TITLE
setuptools-scm does not function when installing as part of a git hook while working inside of a submodule

### ISSUE THREAD

**Issue by asottile** [pypa/setuptools-scm#381]
this issue is oddly specific but here's the reproduction:

```bash
#!/usr/bin/env bash
set -euxo pipefail

rm -rf y z home black venv

git clone https://github.com/psf/black

export PRE_COMMIT_HOME="$PWD/home"
git init y
git init z
git -C z commit --allow-empty -m 'commit!'
git -C y submodule add "$PWD/z"
cat > "$PWD/y/.git/modules/z/hooks/pre-commit" <<EOF
#!/usr/bin/env bash
virtualenv "$PWD/venv"
"$PWD/venv/bin/pip" install "$PWD/black"
EOF
chmod +x "$PWD/y/.git/modules/z/hooks/pre-commit"
cd y/z
git commit -m "test"
```

this currently ends as:

```console
$ bash t.sh 
+ rm -rf y z home black venv
+ git clone https://github.com/psf/black
Cloning into 'black'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 3284 (delta 7), reused 2 (delta 1), pack-reused 3270
Receiving objects: 100% (3284/3284), 3.72 MiB | 2.15 MiB/s, done.
Resolving deltas: 100% (2223/2223), done.
+ export PRE_COMMIT_HOME=/tmp/z/home
+ PRE_COMMIT_HOME=/tmp/z/home
+ git init y
Initialized empty Git repository in /tmp/z/y/.git/
+ git init z
Initialized empty Git repository in /tmp/z/z/.git/
+ git -C z commit --allow-empty -m 'commit!'
[master (root-commit) 4f0b4dc] commit!
+ git -C y submodule add /tmp/z/z
Cloning into '/tmp/z/y/z'...
done.
+ cat
+ chmod +x /tmp/z/y/.git/modules/z/hooks/pre-commit
+ cd y/z
+ git commit -m test
Using real prefix '/usr'
Path not in prefix '/home/asottile/opt/venv/include/python3.6m' '/usr'
New python executable in /tmp/z/venv/bin/python3
Also creating executable in /tmp/z/venv/bin/python
Installing setuptools, pip, wheel...
done.
Processing /tmp/z/black
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /tmp/z/venv/bin/python3 /tmp/z/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp33fojq8s
         cwd: /tmp/pip-req-build-6b2fw0yg
    Complete output (36 lines):
    Traceback (most recent call last):
      File "/tmp/z/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
        main()
      File "/tmp/z/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/tmp/z/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 110, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-ydhjt6g5/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 156, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-ydhjt6g5/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 97, in <module>
        "blackd=blackd:patched_main [d]",
      File "/tmp/pip-build-env-ydhjt6g5/overlay/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/tmp/pip-build-env-ydhjt6g5/overlay/lib/python3.6/site-packages/setuptools/dist.py", line 448, in __init__
        k: v for k, v in attrs.items()
      File "/usr/lib/python3.6/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/tmp/pip-build-env-ydhjt6g5/overlay/lib/python3.6/site-packages/setuptools/dist.py", line 740, in finalize_options
        ep.load()(self)
      File "/tmp/pip-build-env-ydhjt6g5/overlay/lib/python3.6/site-packages/setuptools/dist.py", line 747, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/tmp/pip-build-env-ydhjt6g5/overlay/lib/python3.6/site-packages/setuptools_scm/integration.py", line 17, in version_keyword
        dist.metadata.version = get_version(**value)
      File "/tmp/pip-build-env-ydhjt6g5/overlay/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 150, in get_version
        parsed_version = _do_parse(config)
      File "/tmp/pip-build-env-ydhjt6g5/overlay/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 113, in _do_parse
        "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
    LookupError: setuptools-scm was unable to detect version for '/tmp/pip-req-build-6b2fw0yg'.
    
    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
    
    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
    ----------------------------------------
ERROR: Command errored out with exit status 1: /tmp/z/venv/bin/python3 /tmp/z/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp33fojq8s Check the logs for full command output.
```

___

**guess at a fix**

I don't know much about setuptools-scm, but I suspect a patch with functionality similar [to this](https://github.com/pre-commit/pre-commit/blob/6850c27dd68dbd118c037e5cdb70957508827f67/pre_commit/git.py#L22-L36) would fix the problem

Original issue: https://github.com/psf/black/issues/1180

**Comment by RonnyPfannschmidt** [comment]
it will be obscenely interesting to set this up to in a regression test against the current version

**Comment by RonnyPfannschmidt** [comment]
i suspect a pip interaction issue that i have been hunting since a while - aka - pip makes a metadata free copy and breaks our back
#345 seems potentially related

**Comment by RonnyPfannschmidt** [comment]
ruled that theory out by using `pip --no-clean`

**Comment by asottile** [comment]
nah it's very much not that -- I triaged it above, this is the environment variables that `git` puts into the environment interfering with whatever `git` commands `setuptools-scm` is running

for instance if you take the above reproduction and instead call the script directly it works fine:

```diff
$ diff -u t.sh.old t.sh
--- t.sh.old	2019-12-13 13:20:06.431135823 -0800
+++ t.sh	2019-12-13 13:20:09.219017427 -0800
@@ -16,5 +16,4 @@
 "$PWD/venv/bin/pip" install "$PWD/black"
 EOF
 chmod +x "$PWD/y/.git/modules/z/hooks/pre-commit"
-cd y/z
-git commit -m "test"
+"$PWD/y/.git/modules/z/hooks/pre-commit"
```

**Comment by RonnyPfannschmidt** [comment]
thanks. it seems to be the git env vars indeed
ill rework the scripts a bit more to use setuptools_scm from its own folder and copy over the clean env helpers

**Comment by RonnyPfannschmidt** [comment]
@asottile i  can  confirm that the helper fixes the issue

im not sure if i can build up a sound regression test from the example, i'll try to build a minimal regression test the other way around

**Comment by asottile** [comment]
yeah you can probably narrow it to a 2-repository reproduction: set `GIT_INDEX` to an unrelated git repo and attempt to install repo 2

**Comment by RonnyPfannschmidt** [comment]
setting `GIT_DIR` to `__file__` was already enough, thanks for the pointers

**Comment by RonnyPfannschmidt** [comment]
pr upcoming - @asottile thanks for providing extensive analysis and the solution

**Comment by blueyed** [comment]
JFI: `bash testing/play_out_381.bash $PWD` still fails on master (cdb09b1).  From what I can tell the issue is that `git rev-parse --show-toplevel` gets called from the submodule - and unsetting `GIT_` env vars does not really help with that.

**Comment by asottile** [comment]
not sure what you're referring to -- this fix definitely fixes the problem:

```bash
#!/usr/bin/env bash
set -euxo pipefail

rm -rf y z home black venv

git clone https://github.com/psf/black

export PRE_COMMIT_HOME="$PWD/home"
git init y
git init z
git -C z commit --allow-empty -m 'commit!'
git -C y submodule add "$PWD/z"
cat > "$PWD/y/.git/modules/z/hooks/pre-commit" <<EOF
#!/usr/bin/env bash
virtualenv "$PWD/venv"
# BROKEN: "$PWD/venv/bin/pip" install setuptools-scm
"$PWD/venv/bin/pip" install git+https://github.com/pypa/setuptools_scm
"$PWD/venv/bin/pip" install "$PWD/black" --no-build-isolation
EOF
chmod +x "$PWD/y/.git/modules/z/hooks/pre-commit"
cd y/z
git commit -m "test"
```

if you comment toggle the `BROKEN` and line below it you can see it fixes the issue

**Comment by blueyed** [comment]
@asottile 
I was referring to the script that has been commited for this issue (although not being used anywhere, e.g. for regression tests).
Your script also differs with the original reproducer by at least using `--no-build-isolation` now.

Also it would be better to compare/check the actual commit, and not a version that had many other changes already.

Anyway, I'm not going to investigate further - just wanted to let you know, but it might be that I've missed something, of course, and/or the "play" scrupt needs updating.

**Comment by asottile** [comment]
the play script will work once the changeset is released

**Comment by blueyed** [comment]
I've used the play script with `$1 = $PWD` which should have installed the master version, no?

**Comment by asottile** [comment]
I don't think so, due to pip's build isolation

**Comment by RonnyPfannschmidt** [comment]
ah, that tricky issue - the build isolation did bite me in that script as well (which is why i did the minimal test @asottile indicated as practical)

i'll do a "incomplete" release on the weekend (no fix/solution for the windows path condition) but the rest should work fine
