### ISSUE TITLE
LookupError despite fallback_version set

### ISSUE THREAD

**Issue by MuellerSeb** [pypa/setuptools-scm#409]
Hey there,

I know a lot of these issues exist and that it is a pip related problem, when installing from archive like in our case:

    pip install -U https://github.com/steven-murray/hankel/archive/6e88724e0dae245288d1b58656d307961a7111ea.zip

gives:

    Collecting https://github.com/steven-murray/hankel/archive/6e88724e0dae245288d1b58656d307961a7111ea.zip
      Downloading https://github.com/steven-murray/hankel/archive/6e88724e0dae245288d1b58656d307961a7111ea.zip
         / 7.9MB 1.8MB/s
      Installing build dependencies ... done
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-req-build-n8mzotky/setup.py", line 68, in <module>
            url="https://github.com/steven-murray/hankel",
          File "/tmp/pip-build-env-zkffa_82/lib/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
            _install_setup_requires(attrs)
          File "/tmp/pip-build-env-zkffa_82/lib/python3.6/site-packages/setuptools/__init__.py", line 132, in _install_setup_requires
            (k, v) for k, v in attrs.items()
          File "/tmp/pip-build-env-zkffa_82/lib/python3.6/site-packages/setuptools/dist.py", line 425, in __init__
            k: v for k, v in attrs.items()
          File "/usr/lib/python3.6/distutils/dist.py", line 281, in __init__
            self.finalize_options()
          File "/tmp/pip-build-env-zkffa_82/lib/python3.6/site-packages/setuptools/dist.py", line 706, in finalize_options
            ep.load()(self)
          File "/tmp/pip-build-env-zkffa_82/lib/python3.6/site-packages/setuptools_scm/integration.py", line 48, in infer_version
            dist.metadata.version = _get_version(config)
          File "/tmp/pip-build-env-zkffa_82/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 147, in _get_version
            parsed_version = _do_parse(config)
          File "/tmp/pip-build-env-zkffa_82/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 118, in _do_parse
            "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
        LookupError: setuptools-scm was unable to detect version for '/tmp/pip-req-build-n8mzotky'.
        
        Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
        
        For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

What bothers me is the fact, that a `fallback_version` was set in setup.py and I would expect `setuptools_scm` to use this version in case of a LookupError.

Or am I doing something wrong?

Cheers, Sebastian

**Comment by RonnyPfannschmidt** [comment]
unfortunately i cant take a closer look before the weekend at best due to covid related changes in personal life (nothing gruesome, just no time for opensource much)

**Comment by MuellerSeb** [comment]
Anything new here?

**Comment by RonnyPfannschmidt** [comment]
thanks for reminding me, a number of things has gone down for me, i believe i may be able to take a look this weekend

**Comment by chrisjbillington** [comment]
I'm seeing this also. It seems to depend on my current working directory. If my current working directory is a (unrelated) git repository, then setuptools_scm returns the fallback version, and if the current directory is not a git repository, then it errors.

The version check is happening inside an installed package that is using its own `__file__`, so it doesn't seem right that the current working directory should have anything to do with it:

```python
import os
from setuptools_scm import get_version
try:
    import importlib.metadata as importlib_metadata
except ImportError:
    import importlib_metadata

VERSION_SCHEME = {
    "version_scheme": os.getenv("SCM_VERSION_SCHEME", "guess-next-dev"),
    "local_scheme": os.getenv("SCM_LOCAL_SCHEME", "node-and-date"),
}

try:
    __version__ = importlib_metadata.version(__package__)
except importlib_metadata.PackageNotFoundError:
    __version__ = None


__version__ = get_version(
    '..', relative_to=__file__, fallback_version=__version__, **VERSION_SCHEME
)
        

```

**Comment by chrisjbillington** [comment]
Realised that importing `setuptools_scm` unconditionally at run time was a bad idea anyway due to `pkg_resources` ending up getting imported. So I've switched this up to the following to avoid both problems:
```python
import os
from pathlib import Path
try:
    import importlib.metadata as importlib_metadata
except ImportError:
    import importlib_metadata

VERSION_SCHEME = {
    "version_scheme": os.getenv("SCM_VERSION_SCHEME", "guess-next-dev"),
    "local_scheme": os.getenv("SCM_LOCAL_SCHEME", "node-and-date"),
}

root = Path(__file__).parent.parent
if (root / '.git').is_dir():
    from setuptools_scm import get_version
    __version__ = get_version(root, **VERSION_SCHEME)
else:
    try:
        __version__ = importlib_metadata.version(__package__)
    except importlib_metadata.PackageNotFoundError:
        __version__ = None
```

**Comment by MindTooth** [comment]
I now have the same issue.  I tried putting `fallback_version = 1.0.0` into `pyproject.toml` and/or `setup.cfg`.  Keeps complaining about the missing version.  I've downloaded an archive from GitHub.

Do in fact `fallback_version` work in the latest PyPi version?

**Comment by zerothi** [comment]
I also have this problem:

`pyproject.toml`
```
[tool.setuptools_scm]
write_to = "sisl/_version.py"
fallback_version = "$Format:%H$"
```

`setup.py`:
```
setup(use_scm_version=True, ...)
```

Then extracting to archive `git archive --output test.tar.gz HEAD` and running pip with this results in:

`python3 -m pip --log=foo.bar test.tar.gz`

```shell
2021-12-03T12:44:26,421   version keyword {'name': None, 'version': None, 'author': None, 'author_email': None, 'maintainer': None, 'maintainer_email': None, 'url': None, 'license': None, 'description': None, 'long_description': None, 'keywords': None, 'platforms': 'any', 'classifiers': None, 'download_url': None, 'provides': None, 'requires': None, 'obsoletes': None}
2021-12-03T12:44:26,422   l {'root': '.', 'relative_to': None}
2021-12-03T12:44:26,422   root '/tmp/pip-req-build-91c9cxij'
2021-12-03T12:44:26,422   relative_to None
2021-12-03T12:44:26,422   dist name: sisl
2021-12-03T12:44:26,422   looking for ep setuptools_scm.parse_scm /tmp/pip-req-build-91c9cxij
2021-12-03T12:44:26,425   looking for ep setuptools_scm.parse_scm_fallback /tmp/pip-req-build-91c9cxij
2021-12-03T12:44:26,429   found ep EntryPoint(name='setup.py', value='setuptools_scm.hacks:fallback_version', group='setuptools_scm.parse_scm_fallback') in /tmp/pip-req-build-91c9cxij
2021-12-03T12:44:26,429   EntryPoint(name='setup.py', value='setuptools_scm.hacks:fallback_version', group='setuptools_scm.parse_scm_fallback') None
2021-12-03T12:44:26,430   Traceback (most recent call last):
2021-12-03T12:44:26,430     File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
2021-12-03T12:44:26,430       main()
2021-12-03T12:44:26,430     File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
2021-12-03T12:44:26,430       json_out['return_val'] = hook(**hook_input['kwargs'])
2021-12-03T12:44:26,430     File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
2021-12-03T12:44:26,430       return hook(metadata_directory, config_settings)
2021-12-03T12:44:26,430     File "/tmp/pip-build-env-ddvkkj6m/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in prepare_metadata_for_build_wheel
2021-12-03T12:44:26,430       self.run_setup()
2021-12-03T12:44:26,430     File "/tmp/pip-build-env-ddvkkj6m/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 158, in run_setup
2021-12-03T12:44:26,430       exec(compile(code, __file__, 'exec'), locals())
2021-12-03T12:44:26,430     File "setup.py", line 391, in <module>
2021-12-03T12:44:26,430       setup(**metadata)
2021-12-03T12:44:26,430     File "/tmp/pip-build-env-ddvkkj6m/overlay/lib/python3.9/site-packages/numpy/distutils/core.py", line 169, in setup
2021-12-03T12:44:26,430       return old_setup(**new_attr)
2021-12-03T12:44:26,430     File "/tmp/pip-build-env-ddvkkj6m/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
2021-12-03T12:44:26,430       return distutils.core.setup(**attrs)
2021-12-03T12:44:26,430     File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/distutils/core.py", line 108, in setup
2021-12-03T12:44:26,430       _setup_distribution = dist = klass(attrs)
2021-12-03T12:44:26,430     File "/tmp/pip-build-env-ddvkkj6m/overlay/lib/python3.9/site-packages/numpy/distutils/numpy_distribution.py", line 14, in __init__
2021-12-03T12:44:26,430       Distribution.__init__(self, attrs)
2021-12-03T12:44:26,430     File "/tmp/pip-build-env-ddvkkj6m/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 453, in __init__
2021-12-03T12:44:26,430       _Distribution.__init__(
2021-12-03T12:44:26,430     File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/distutils/dist.py", line 292, in __init__
2021-12-03T12:44:26,430       self.finalize_options()
2021-12-03T12:44:26,431     File "/tmp/pip-build-env-ddvkkj6m/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 831, in finalize_options
2021-12-03T12:44:26,431       ep(self)
2021-12-03T12:44:26,431     File "/tmp/pip-build-env-ddvkkj6m/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 852, in _finalize_setup_keywords
2021-12-03T12:44:26,431       ep.load()(self, ep.name, value)
2021-12-03T12:44:26,431     File "/tmp/pip-build-env-ddvkkj6m/overlay/lib/python3.9/site-packages/setuptools_scm/integration.py", line 65, in version_keyword
2021-12-03T12:44:26,431       dist.metadata.version = _get_version(config)
2021-12-03T12:44:26,431     File "/tmp/pip-build-env-ddvkkj6m/overlay/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 177, in _get_version
2021-12-03T12:44:26,431       parsed_version = _do_parse(config)
2021-12-03T12:44:26,431     File "/tmp/pip-build-env-ddvkkj6m/overlay/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 135, in _do_parse
2021-12-03T12:44:26,431       raise LookupError(
2021-12-03T12:44:26,431   LookupError: setuptools-scm was unable to detect version for '/tmp/pip-req-build-91c9cxij'.
```

**Comment by zerothi** [comment]
I can bypass this problem by doing something like this:

```
[tool.setuptools_scm]
write_to = "sisl/_version.py"
fallback_version = "0.0.0.dev+$Format:%H$"
```

I would recommend a fallback version _never_ needs to adhere to any formatting rules. It seems a simple `fallback_version ='wvhatever weird stuff'` does not match the Version specification (`tag_regex`). However, for fallback versions I think it would be the package maintainers freedom to choose any version name they wish.

Could this be an idea?

**Comment by RonnyPfannschmidt** [comment]
Invalid versions create broken packages

Git archives are not yet supported and need extra work

**Comment by zerothi** [comment]
> Invalid versions create broken packages
> 
> Git archives are not yet supported and need extra work

Agreed that this is not a good practice for pypi uploads. But for local testing? Hmm.. I can see it is sort of a gray area, since once it is in people will abuse it... Perhaps just making the error message better, i.e. that the `fallback_version` does not conform to the format requirements of a version. It was quite mysterious to me what actually caused this.

**Comment by RonnyPfannschmidt** [comment]
@zerothi even for local testing - use a actual sdist, git archives require fixes in modern git + a pr i havent been able to work on for a while to actually work

indeed, a better error for fall-back version is required

**Comment by RonnyPfannschmidt** [comment]
closing this off as the original issue is the order problem between declarative and imperative testing that differs between early pyproject support and modern pyproject support

theres still some issues with setup.py vs pyproject.toml that need a extra resolution, however we now always load the config - its strongly recommended to put all static data in pyproject.toml these days (this was not a safe suggestion in 2020)
