### ISSUE TITLE
during relpath, ValueError: path is on mount...

### ISSUE THREAD

**Issue by jaraco** [pypa/setuptools-scm#436]
Attempting to run tests cross-platform, I've set up the following environment:

- on macOS host, checked out (and develop) code
- on Windows VM guest, mount the home directory of the host `\\vmware-host\shared folders\home`
- in the home directory on the guest, create a symbolic link `~/code -> \\vmware-host\shared folders\home\code` (plus some other symlinks like `~/m -> code\main`)

Then, I want to run tests on a project in `~/m/path`, but I don't want `tox` to re-use the same environments, and writing to the shared volumes mount is slow, so I update the `tox.ini` to override toxworkdir to indicate a guest-local path.

```
diff --git a/tox.ini b/tox.ini
index 171ef1c..4212469 100644
--- a/tox.ini
+++ b/tox.ini
@@ -3,6 +3,7 @@ envlist = python
 minversion = 3.2
 # https://github.com/jaraco/skeleton/issues/6
 tox_pip_extensions_ext_venv_update = true
+toxworkdir = /Users/jaraco/temp/.tox
 
 
 [testenv]
```

When I run tox, however, the tests fail when `setuptools_scm` attempts to resolve relative paths from the project checkout (on the shared mount) to the virtualenv, because they're on different mount points.

```
path master # tox
python create: \Users\jaraco\temp\.tox\python
python develop-inst: C:\Users\jaraco\m\path
ERROR: invocation failed (exit code 1), logfile: \Users\jaraco\temp\.tox\python\log\python-1.log
============================================================================== log start ===============================================================================
Obtaining file:///C:/Users/jaraco/m/path
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\jaraco\temp\.tox\python\Scripts\python.EXE' 'C:\Users\jaraco\temp\.tox\python\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\jaraco\AppData\Local\Temp\tmpklt44h0k'
         cwd: C:\Users\jaraco\m\path
    Complete output (49 lines):
    running dist_info
    creating C:\Users\jaraco\m\path\pip-wheel-metadata\path.egg-info
    writing C:\Users\jaraco\m\path\pip-wheel-metadata\path.egg-info\PKG-INFO
    writing dependency_links to C:\Users\jaraco\m\path\pip-wheel-metadata\path.egg-info\dependency_links.txt
    writing requirements to C:\Users\jaraco\m\path\pip-wheel-metadata\path.egg-info\requires.txt
    writing top-level names to C:\Users\jaraco\m\path\pip-wheel-metadata\path.egg-info\top_level.txt
    writing manifest file 'C:\Users\jaraco\m\path\pip-wheel-metadata\path.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "C:\Users\jaraco\temp\.tox\python\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 207, in <module>
        main()
      File "C:\Users\jaraco\temp\.tox\python\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 197, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "C:\Users\jaraco\temp\.tox\python\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 69, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "C:\Users\jaraco\AppData\Local\Temp\pip-build-env-j4re0lro\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in prepare_metadata_for_build_wheel 
        self.run_setup()
      File "C:\Users\jaraco\AppData\Local\Temp\pip-build-env-j4re0lro\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 6, in <module>
        setuptools.setup()
      File "C:\Users\jaraco\AppData\Local\Temp\pip-build-env-j4re0lro\overlay\Lib\site-packages\setuptools\__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "c:\program files\python38\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\program files\python38\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\program files\python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\jaraco\AppData\Local\Temp\pip-build-env-j4re0lro\overlay\Lib\site-packages\setuptools\command\dist_info.py", line 31, in run
        egg_info.run()
      File "C:\Users\jaraco\AppData\Local\Temp\pip-build-env-j4re0lro\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 297, in run
        self.find_sources()
      File "C:\Users\jaraco\AppData\Local\Temp\pip-build-env-j4re0lro\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 304, in find_sources
        mm.run()
      File "C:\Users\jaraco\AppData\Local\Temp\pip-build-env-j4re0lro\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 535, in run
        self.add_defaults()
      File "C:\Users\jaraco\AppData\Local\Temp\pip-build-env-j4re0lro\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 575, in add_defaults
        rcfiles = list(walk_revctrl())
      File "C:\Users\jaraco\AppData\Local\Temp\pip-build-env-j4re0lro\overlay\Lib\site-packages\setuptools\command\sdist.py", line 20, in walk_revctrl
        for item in ep.load()(dirname):
      File "C:\Users\jaraco\AppData\Local\Temp\pip-build-env-j4re0lro\overlay\Lib\site-packages\setuptools_scm\integration.py", line 27, in find_files
        res = command(path)
      File "C:\Users\jaraco\AppData\Local\Temp\pip-build-env-j4re0lro\overlay\Lib\site-packages\setuptools_scm\file_finder_git.py", line 66, in git_find_files
        return scm_find_files(path, git_files, git_dirs)
      File "C:\Users\jaraco\AppData\Local\Temp\pip-build-env-j4re0lro\overlay\Lib\site-packages\setuptools_scm\file_finder.py", line 53, in scm_find_files
        res.append(os.path.join(path, os.path.relpath(fullfilename, path)))
      File "c:\program files\python38\lib\ntpath.py", line 703, in relpath
        raise ValueError("path is on mount %r, start on mount %r" % (
    ValueError: path is on mount '\\\\vmware-host\\shared folders', start on mount 'C:'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\jaraco\temp\.tox\python\Scripts\python.EXE' 'C:\Users\jaraco\temp\.tox\python\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\jaraco\AppData\Local\Temp\tmpklt44h0k' Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

=============================================================================== log end ================================================================================ 
_______________________________________________________________________________ summary ________________________________________________________________________________ 
ERROR:   python: InvocationError for command 'C:\Users\jaraco\temp\.tox\python\Scripts\python.EXE' -m pip install --exists-action w -e 'C:\Users\jaraco\m\path[testing]' 
(exited with code 1)
```

I can probably distill the issue more, but I wanted to capture these details first.

**Comment by jaraco** [comment]
On further consideration, the `toxworkdir` seems to be irrelevant. I assumed it was relevant because it was a recent change, but eliminating that variable and going back to standard tox installation (after `git clean`), the develop install is still failing where it was passing earlier in the week. I'm now suspecting something has changed in setuptools_scm.

**Comment by jaraco** [comment]
I see the [code implicated in the traceback](https://github.com/pypa/setuptools_scm/blob/d7c122e14c9eaca96574dec0ea530ad7204965a9/src/setuptools_scm/file_finder.py#L52) hasn't changed in years, so perhaps I'm questioning that running these tox tests has ever worked.

**Comment by jaraco** [comment]
I was able to replicate the issue without tox by simply:

```
path master # python -m venv .tox/python
path master # .tox/python/Scripts/python setup.py develop
```

**Comment by jaraco** [comment]
Breaking into a debugger during the crash, I see this:

```
> \\vmware-host\shared folders\home\code\main\path\.eggs\setuptools_scm-3.5.0-py3.8.egg\setuptools_scm\file_finder.py(53)scm_find_files()
-> res.append(os.path.join(path, os.path.relpath(fullfilename, path)))
(Pdb) fullfilename
'\\\\vmware-host\\shared folders\\home\\code\\main\\path\\.flake8'
(Pdb) path
''
```

**Comment by jaraco** [comment]
Aha! I figured out how I was running the tests earlier this week. I was using `tox -e py37` in order to have a different on the guest than on the host.

Turns out, the tests run fine on Python 3.7, so the issue is likely related to the changes to `readlink` and `realpath` on Windows for Python 3.8, perhaps related to the issues discussed in [bpo-40654](https://bugs.python.org/issue40654).

**Comment by jaraco** [comment]
I've filed [bpo-40732](https://bugs.python.org/issue40732) to track the issue upstream.

**Comment by RonnyPfannschmidt** [comment]
Interesting find, i believe that pytest also has a affected code path

**Comment by jaraco** [comment]
I've confirmed that the issue happens without the `~/m` symlink; the issue happens just when running tox in `~/code/main/path`, such that `~/code` is the only symlink implicated.

**Comment by jaraco** [comment]
In 340b235 (bugfix/436-realpath-everywhere branch), I've pushed a commit that I believe may address the issue. Confirmed it on a Windows box that was affected:

```
path master # pip-run git+https://github.com/pypa/setuptools_scm@340b235 -q -- setup.py egg_info
WARNING: You are using pip version 20.1; however, version 20.1.1 is available.
You should consider upgrading via the 'c:\program files\python38\python.exe -m pip install --upgrade pip' command.
running egg_info
writing path.egg-info\PKG-INFO
writing dependency_links to path.egg-info\dependency_links.txt
writing requirements to path.egg-info\requires.txt
writing top-level names to path.egg-info\top_level.txt
reading manifest template 'MANIFEST.in'
writing manifest file 'path.egg-info\SOURCES.txt'
```

**Comment by RonnyPfannschmidt** [comment]
good find, i wonder if there is a way to put that into automation
