### ISSUE TITLE
The 'jaraco.windows' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by aaronkvanmeerten** [pypa/setuptools-scm#440]
While trying to install the pubnub python library, I ran into this issue: pubnub depends on setuptools_scm, which in turns seems to need this jaraco.windows package.  However, even when I did a `pip install jaraco.windows setuptools_scm pubnub` I got this error.  I eventually had to install jaraco.windows in a separate command to fulfill the dependency before I installed setuptools_scm and pubnub.

The full error message is something like this (sorry for ansible escaping):

`"/usr/local/lib/python2.7/dist-packages/setuptools/dist.py\", line 739, in finalize_options\n        for ep in sorted(eps, key=by_order):\n      File \"/usr/local/lib/python2.7/dist-packages/setuptools/dist.py\", line 738, in <lambda>\n        eps = map(lambda e: e.load(), pkg_resources.iter_entry_points(group))\n      File \"/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 2442, in load\n        self.require(*args, **kwargs)\n      File \"/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 2465, in require\n        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n      File \"/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 786, in resolve\n        raise DistributionNotFound(req, requirers)\n    pkg_resources.DistributionNotFound: The 'jaraco.windows' distribution was not found and is required by the application\n    \n    ----------------------------------------\n\n:stderr: Command \"python setup.py egg_info\" failed with error code 1 in /tmp/pip-build-FfPU4A/setuptools-scm/\n"`

I'm opening this issue here in case anyone else runs into this problem.  I wonder if there's some way to explicitly define this as a requirement to avoid needing to do this manually?

**Comment by r1prakash** [comment]
Getting same error at my end:-

`    <pkg_resources.WorkingSet object at 0x7f24aef02b90>
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-CDBOV8/setuptools-scm/setup.py", line 53, in <module>
        setuptools.setup(**scm_config())
      File "/opt/rh/python27/root/usr/lib64/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/opt/app-root/lib/python2.7/site-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/opt/rh/python27/root/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/opt/app-root/lib/python2.7/site-packages/setuptools/dist.py", line 326, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/opt/app-root/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2371, in require
        items = working_set.resolve(reqs, env, installer)
      File "/opt/app-root/lib/python2.7/site-packages/pkg_resources/__init__.py", line 836, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/opt/app-root/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1081, in best_match
        return self.obtain(req, installer)
      File "/opt/app-root/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1093, in obtain
        return installer(requirement)
      File "/opt/app-root/lib/python2.7/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/opt/app-root/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 629, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/opt/app-root/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 659, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/opt/app-root/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 842, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/opt/app-root/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1070, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/opt/app-root/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1056, in run_setup
        run_setup(setup_script, args)
      File "/opt/app-root/lib/python2.7/site-packages/setuptools/sandbox.py", line 240, in run_setup
        raise
      File "/opt/rh/python27/root/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/opt/app-root/lib/python2.7/site-packages/setuptools/sandbox.py", line 193, in setup_context
        yield
      File "/opt/rh/python27/root/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/opt/app-root/lib/python2.7/site-packages/setuptools/sandbox.py", line 164, in save_modules
        saved_exc.resume()
      File "/opt/app-root/lib/python2.7/site-packages/setuptools/sandbox.py", line 139, in resume
        compat.reraise(type, exc, self._tb)
      File "/opt/app-root/lib/python2.7/site-packages/setuptools/sandbox.py", line 152, in save_modules
        yield saved
      File "/opt/app-root/lib/python2.7/site-packages/setuptools/sandbox.py", line 193, in setup_context
        yield
      File "/opt/app-root/lib/python2.7/site-packages/setuptools/sandbox.py", line 237, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/opt/app-root/lib/python2.7/site-packages/setuptools/sandbox.py", line 267, in run
        return func()
      File "/opt/app-root/lib/python2.7/site-packages/setuptools/sandbox.py", line 236, in runner
        _execfile(setup_script, ns)
      File "/opt/app-root/lib/python2.7/site-packages/setuptools/sandbox.py", line 46, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-rljUvK/jaraco.windows-5.0.0/setup.py", line 6, in <module>
        will generate partial data
      File "/opt/rh/python27/root/usr/lib64/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/opt/rh/python27/root/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/opt/rh/python27/root/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/opt/app-root/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 151, in run
        self.run_command("egg_info")
      File "/opt/rh/python27/root/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/opt/rh/python27/root/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/opt/app-root/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 180, in run
        self.find_sources()
      File "/opt/app-root/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 207, in find_sources
        mm.run()
      File "/opt/app-root/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 291, in run
        self.add_defaults()
      File "/opt/app-root/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 323, in add_defaults
        rcfiles = list(walk_revctrl())
      File "/opt/app-root/lib/python2.7/site-packages/setuptools/command/sdist.py", line 19, in walk_revctrl
        for item in ep.load()(dirname):
      File "/opt/app-root/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2354, in load
        self.require(*args, **kwargs)
      File "/opt/app-root/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2371, in require
        items = working_set.resolve(reqs, env, installer)
      File "/opt/app-root/lib/python2.7/site-packages/pkg_resources/__init__.py", line 839, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'path.py>=6.2' distribution was not found and is required by jaraco.windows`

**Comment by RonnyPfannschmidt** [comment]
That's a unexpected packaging issue, I will undo the devendoring of the helpers as it seems we need a few more years to get this to work well for everyone

**Comment by mgorny** [comment]
Is `jaraco.windows` actually used? I've tried hard to grep it in the code but it doesn't seem to be referenced anywhere, and judging from README it doesn't monkey-patch anything automatically. Furthermore, even if it were used, shouldn't it be needed on windows only?

**Comment by sbidoul** [comment]
I'm also seeing `The 'path.py>=6.2' distribution was not found and is required by jaraco.windows` with setuptools_scm 4.0.0 and python 2 on Linux.

**Comment by RonnyPfannschmidt** [comment]
thanks to @henryiii suggesting the universal wheel upload in #445, i quickly did that - please crosscheck if that's already a relief

**Comment by faudebert** [comment]
FYI, still got a similar issue installing `ddtrace` package on stock Python 2.7 from Debian Stretch which also depends on `setuptools_scm`. AFAIK, it was working properly few days ago. Here are few steps to reproduce using a Docker container:

```sh
$ docker run --rm -it debian:stretch-slim /bin/bash
$ apt update
$ apt install python-pip build-essential
$ pip install cython ddtrace
[...]
pkg_resources.DistributionNotFound: The 'path.py>=6.2' distribution was not found and is required by jaraco.windows
```

**Comment by henryiii** [comment]
4.1.0 is out and should have fixed this problem too.

**Comment by dsoprea** [comment]
Sorry for activating an old topic, but this suddenly came up for me in a payment system after a routine build to release a bugfix. Nothing has changed for months:
```
2025-08-29T14:56:45 Traceback (most recent call last):
2025-08-29T14:56:45   File "/usr/local/bin/waw_payment_request_fulfill_batch", line 4, in <module>
2025-08-29T14:56:45     __import__('pkg_resources').require('workflow-api-website==0.0.1')
2025-08-29T14:56:45   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3267, in <module>
2025-08-29T14:56:45     def _initialize_master_working_set():
2025-08-29T14:56:45   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3241, in _call_aside
2025-08-29T14:56:45     f(*args, **kwargs)
2025-08-29T14:56:45   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3279, in _initialize_master_working_set
2025-08-29T14:56:45     working_set = WorkingSet._build_master()
2025-08-29T14:56:45   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 573, in _build_master
2025-08-29T14:56:45     ws.require(__requires__)
2025-08-29T14:56:45   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 891, in require
2025-08-29T14:56:45     needed = self.resolve(parse_requirements(requirements))
2025-08-29T14:56:45   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 777, in resolve
2025-08-29T14:56:45     raise DistributionNotFound(req, requirers)
2025-08-29T14:56:45 pkg_resources.DistributionNotFound: The 'jaraco.functools' distribution was not found and is required by keyring
```

The tool that we use (which shares some of the same libraries) to post logs had a different error:
```
2025-08-29T14:56:45 + isl_task_put_metadata a4b0382c704c436ab8868de025e3c036 --metadata console_tail_output -
2025-08-29T14:56:46 Traceback (most recent call last):
2025-08-29T14:56:46   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 573, in _build_master
2025-08-29T14:56:46     ws.require(__requires__)
2025-08-29T14:56:46   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 891, in require
2025-08-29T14:56:46     needed = self.resolve(parse_requirements(requirements))
2025-08-29T14:56:46   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 782, in resolve
2025-08-29T14:56:46     raise VersionConflict(dist, req).with_context(dependent_req)
2025-08-29T14:56:46 pkg_resources.ContextualVersionConflict: (tqdm 4.66.5 (/usr/local/lib/python3.10/dist-packages), Requirement.parse('tqdm==4.64.1'), {'infrastructure-storage-layer'})
```

The interesting thing is that this conflict has probably been there for a very long time, and hasn't cause any issues before now. Once we fixed this issue, the top one (the topic of this ticket) went away. 

Just mentioning it for posterity for anyone else that lands here. It was truly mystifying.

This was running in an image with Ubuntu 22.04 and a setuptools release from 2021. It's not clear what the fix in 2020 was, but something induced this and the conditions underlying its occurrence are murky.

**Comment by RonnyPfannschmidt** [comment]
Wrong project

**Comment by dsoprea** [comment]
Similar error to the original. Moot point. Not trying to dirty this thread, but this does mention a solution for the not-completely-irrelevant reason that I ended-up here.

**Comment by RonnyPfannschmidt** [comment]
We no longer depend on the relevant paclages
