### ISSUE TITLE
LookupError when running pip install on multiple packages

### ISSUE THREAD

**Issue by velovix** [pypa/setuptools-scm#454]
I've recently started using `setuptools_scm` for an open source library composed of two closely related packages. These packages are called `vcap` and `vcap_utils`. I used to recommend users install both of them from source by running:

```bash
pip install -e ./vcap ./vcap_utils
```

However, that seems to interfere with setuptools_scm's ability to see the SCM information. I get the following exception:

```bash
Processing ./vcap_utils
    ERROR: Command errored out with exit status 1:
     command: /home/velovix/.virtualenvs/open_vision_capsules_test/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-yrw2ix0d/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-yrw2ix0d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-31yqgf6j
         cwd: /tmp/pip-req-build-yrw2ix0d/
    Complete output (27 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-yrw2ix0d/setup.py", line 41, in <module>
        python_requires='>=3.6',
      File "/home/velovix/.virtualenvs/open_vision_capsules_test/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/velovix/.virtualenvs/open_vision_capsules_test/lib/python3.6/site-packages/setuptools/dist.py", line 426, in __init__
        k: v for k, v in attrs.items()
      File "/usr/lib/python3.6/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/home/velovix/.virtualenvs/open_vision_capsules_test/lib/python3.6/site-packages/setuptools/dist.py", line 717, in finalize_options
        ep(self)
      File "/home/velovix/.virtualenvs/open_vision_capsules_test/lib/python3.6/site-packages/setuptools/dist.py", line 724, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/tmp/pip-req-build-yrw2ix0d/.eggs/setuptools_scm-4.1.2-py3.6.egg/setuptools_scm/integration.py", line 17, in version_keyword
        dist.metadata.version = _get_version(config)
      File "/tmp/pip-req-build-yrw2ix0d/.eggs/setuptools_scm-4.1.2-py3.6.egg/setuptools_scm/__init__.py", line 148, in _get_version
        parsed_version = _do_parse(config)
      File "/tmp/pip-req-build-yrw2ix0d/.eggs/setuptools_scm-4.1.2-py3.6.egg/setuptools_scm/__init__.py", line 118, in _do_parse
        "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
    LookupError: setuptools-scm was unable to detect version for '/tmp'.
    
    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
    
    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

If instead I install the two one-by-one, it works just fine.

```bash
pip install -e "./vcap"
pip install -e "./vcap_utils"
```

The source is available here on the `add-github-actions` branch: https://github.com/opencv/open_vision_capsules/tree/add-github-actions

Is installing multiple packages this way expected to work with setuptools_scm?

**Version information:**
Python: 3.6.10
Pip: 20.1.1

**Comment by RonnyPfannschmidt** [comment]
i believe you meant to invoke `pip install -e ./vcap -e ./vcap_utils` - unfortunately regular pip install triggers build isolation and copies away the folder without git metadata, thus rendering setuptools_scm helpless in that case

**Comment by velovix** [comment]
@RonnyPfannschmidt You're right, thanks.

Are there any workarounds available right now for projects with multiple packages?

**Comment by velovix** [comment]
Sorry, just realized I misunderstood why your fix worked. Using `-e` _is_ the workaround! For this local installation use case, that solves it for me. I'll go ahead and close this issue.
