### ISSUE TITLE
AssertionError: Can't parse version default/fix/fluidsim-core-0.4.1

### ISSUE THREAD

**Issue by paugier** [pypa/setuptools-scm#530]
I can't install a package (https://github.com/exabl/snek5000) because of a setuptools_scm error (AssertionError: Can't parse version default/fix/fluidsim-core-0.4.1). What can I do?

Note: I cloned the Github package with hg.

```
pierre@gre ~/Dev/snek5000 master $ hg sum                                       
parent: 285:7def824c6333 default/master tip
 Merge pull request #20 from exabl/docs/material
branch: default
bookmarks: *master
lib/Nek5000/run/.gitignore: unsupported ignore pattern '!.gitignore'
lib/Nek5000/3rd_party/.gitignore: unsupported ignore pattern '!.gitignore'
commit: (clean)
update: 13 new changesets, 4 branch heads (merge)
phases: 286 draft

pierre@gre ~/Dev/snek5000 master $ hg book                                      
   enh/fluidsim-core         274:a10bc6086557
   enh/paraview              208:762b250ebd1e
   enh/pytest-cov            236:00c4e8d71fa0
   enh/snake-nek             261:b6d48d986176
   enh/templates             196:f7b720daaa31
   enh/upgrade-v19           213:1a195421e67e
   fix/activate_paths        201:589c961eac38
   fix/ci                    169:eca44820047d
   fix/fluidsim-0.3.3        243:a3d69ea3e94f
   fix/fluidsim-core-0.4.1   281:7bcf2618917b
   gh-pages                  191:5c5fd8465ac0
 * master                    285:7def824c6333

pierre@gre ~/Dev/snek5000 master $ pip install -e .                             
Obtaining file:///home/pierre/Dev/snek5000
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/pierre/.pyenv/versions/3.8.2/bin/python3.8 /home/pierre/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmplbof4igl
       cwd: /home/pierre/Dev/snek5000
  Complete output (50 lines):
  /tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools/dist.py:634: UserWarning: Usage of dash-separated 'project-urls' will not be supported in future versions. Please use the underscore name 'project_urls' instead
    warnings.warn(
  /tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools/dist.py:634: UserWarning: Usage of dash-separated 'max-line-length' will not be supported in future versions. Please use the underscore name 'max_line_length' instead
    warnings.warn(
  /tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools_scm/version.py:88: UserWarning: tag 'default/master' no version found
    warnings.warn("tag {!r} no version found".format(tag))
  /tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools_scm/version.py:88: UserWarning: tag 'default/fix/fluidsim-core-0.4.1' no version found
    warnings.warn("tag {!r} no version found".format(tag))
  Traceback (most recent call last):
    File "/home/pierre/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/pierre/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/pierre/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 149, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 10, in <module>
      setup()
    File "/tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/pierre/.pyenv/versions/3.8.2/lib/python3.8/distutils/core.py", line 108, in setup
      _setup_distribution = dist = klass(attrs)
    File "/tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 432, in __init__
      _Distribution.__init__(self, {
    File "/home/pierre/.pyenv/versions/3.8.2/lib/python3.8/distutils/dist.py", line 292, in __init__
      self.finalize_options()
    File "/tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 735, in finalize_options
      ep(self)
    File "/tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools_scm/integration.py", line 61, in infer_version
      dist.metadata.version = _get_version(config)
    File "/tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 173, in _get_version
      parsed_version = _do_parse(config)
    File "/tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 127, in _do_parse
      version = _version_from_entrypoints(config) or _version_from_entrypoints(
    File "/tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 65, in _version_from_entrypoints
      version = _call_entrypoint_fn(root, config, ep.load())
    File "/tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 46, in _call_entrypoint_fn
      return fn(root, config=config)
    File "/tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools_scm/hg.py", line 63, in parse
      return _hg_tagdist_normalize_tagcommit(config, tag, dist, node, branch)
    File "/tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools_scm/hg.py", line 28, in _hg_tagdist_normalize_tagcommit
      return meta(
    File "/tmp/pip-build-env-4fhq9xco/overlay/lib/python3.8/site-packages/setuptools_scm/version.py", line 212, in meta
      assert parsed_version is not None, "Can't parse version %s" % tag
  AssertionError: Can't parse version default/fix/fluidsim-core-0.4.1
  ----------------------------------------
WARNING: Discarding file:///home/pierre/Dev/snek5000. Command errored out with exit status 1: /home/pierre/.pyenv/versions/3.8.2/bin/python3.8 /home/pierre/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmplbof4igl Check the logs for full command output.
ERROR: Command errored out with exit status 1: /home/pierre/.pyenv/versions/3.8.2/bin/python3.8 /home/pierre/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmplbof4igl Check the logs for full command output.
```

**Comment by paugier** [comment]
See https://github.com/exabl/snek5000/issues/23

**Comment by RonnyPfannschmidt** [comment]
@paugier it seems setuptools_scm needs better help in keeping appart hg bookmarks and hg tags

im not yet sure which bit is responsible and unfortunately may not be able to look into this before next week

**Comment by RonnyPfannschmidt** [comment]
@paugier calling that back, for some reason it determines hg as root scm instead of git, i gotta crosschekc whats confusing it in your env

@paugier do you perhaps have ~ under hg control?

**Comment by RonnyPfannschmidt** [comment]
ok, we currently don't correctly handle hg as a git client and mistake bookmarks as tags

**Comment by ashwinvis** [comment]
I believe @paugier used `hg clone git@github.com/exabl/snek5000` using the `hg-git` extension which fetches all git branch as hg bookmarks. I suggested a [workaround](https://github.com/exabl/snek5000/issues/23#issuecomment-800153793) which uses an intermediate `git clone`, followed by a `hg clone` which does not trigger this error by only cloning the `master` branch and tags.

From my end, I can delete the git branches to avoid this error, but I can keep it for a while as @RonnyPfannschmidt debugs the problem.

**Comment by RonnyPfannschmidt** [comment]
thanks ofr the update, i'll try to make a small reproducer later on (im currently over capacity on the time for opensource front)
