### ISSUE TITLE
Build failure with setuptools_scm-6.0.1 with Python 3.5 on Mac

### ISSUE THREAD

**Issue by jcwchen** [pypa/setuptools-scm#542]
I bumped into an issue with the setuptools_scm-6.0.1 (just released recently). While I use `python setup.py bdist_wheel` on Mac, it relies on `setuptools` and `setuptools_scm`. While installing `setuptools_scm`, it encounters an issue as below:
```
2021-03-18T02:05:21.7658910Z /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/easy_install-qtqq5oq7/pytest-runner-5.3.0/temp/easy_install-ck5s79al/setuptools_scm-6.0.1/src
2021-03-18T02:05:21.7669380Z <pkg_resources.WorkingSet object at 0x10f6ba518>
2021-03-18T02:05:21.7845230Z Traceback (most recent call last):
2021-03-18T02:05:21.7849110Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/sandbox.py", line 157, in save_modules
2021-03-18T02:05:21.7850370Z     yield saved
2021-03-18T02:05:21.7852120Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/sandbox.py", line 198, in setup_context
2021-03-18T02:05:21.7853280Z     yield
2021-03-18T02:05:21.7854860Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/sandbox.py", line 248, in run_setup
2021-03-18T02:05:21.7856200Z     DirectorySandbox(setup_dir).run(runner)
2021-03-18T02:05:21.7857860Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/sandbox.py", line 278, in run
2021-03-18T02:05:21.7859040Z     return func()
2021-03-18T02:05:21.7860640Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/sandbox.py", line 246, in runner
2021-03-18T02:05:21.7861810Z     _execfile(setup_script, ns)
2021-03-18T02:05:21.7863480Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/sandbox.py", line 47, in _execfile
2021-03-18T02:05:21.7864670Z     exec(code, globals, locals)
2021-03-18T02:05:21.7866600Z   File "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/easy_install-qtqq5oq7/pytest-runner-5.3.0/temp/easy_install-ck5s79al/setuptools_scm-6.0.1/setup.py", line 52, in <module>
2021-03-18T02:05:21.7869340Z     ONNX_BUILD_TESTS = bool(os.getenv('ONNX_BUILD_TESTS') == '1')
2021-03-18T02:05:21.7871430Z   File "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/easy_install-qtqq5oq7/pytest-runner-5.3.0/temp/easy_install-ck5s79al/setuptools_scm-6.0.1/setup.py", line 29, in scm_config
2021-03-18T02:05:21.7873290Z     TP_DIR = os.path.join(TOP_DIR, 'third_party')
2021-03-18T02:05:21.7875380Z   File "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/easy_install-qtqq5oq7/pytest-runner-5.3.0/temp/easy_install-ck5s79al/setuptools_scm-6.0.1/src/setuptools_scm/__init__.py", line 15, in <module>
2021-03-18T02:05:21.7878180Z   File "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/easy_install-qtqq5oq7/pytest-runner-5.3.0/temp/easy_install-ck5s79al/setuptools_scm-6.0.1/src/setuptools_scm/version.py", line 42
2021-03-18T02:05:21.7880010Z     trace(f"tag '{tag}' parsed to {result}")
2021-03-18T02:05:21.7880800Z                                           ^
2021-03-18T02:05:21.7881550Z SyntaxError: invalid syntax
2021-03-18T02:05:21.7882120Z 
2021-03-18T02:05:21.7883030Z During handling of the above exception, another exception occurred:
2021-03-18T02:05:21.7883770Z 
2021-03-18T02:05:21.7884440Z Traceback (most recent call last):
2021-03-18T02:05:21.7886950Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/sandbox.py", line 157, in save_modules
2021-03-18T02:05:21.7888160Z     yield saved
2021-03-18T02:05:21.7889840Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/sandbox.py", line 198, in setup_context
2021-03-18T02:05:21.7890950Z     yield
2021-03-18T02:05:21.7892570Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/sandbox.py", line 248, in run_setup
2021-03-18T02:05:21.7893850Z     DirectorySandbox(setup_dir).run(runner)
2021-03-18T02:05:21.7895580Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/sandbox.py", line 278, in run
2021-03-18T02:05:21.7896740Z     return func()
2021-03-18T02:05:21.7898300Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/sandbox.py", line 246, in runner
2021-03-18T02:05:21.7899510Z     _execfile(setup_script, ns)
2021-03-18T02:05:21.7901160Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/sandbox.py", line 47, in _execfile
2021-03-18T02:05:21.7902400Z     exec(code, globals, locals)
2021-03-18T02:05:21.7904130Z   File "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/easy_install-qtqq5oq7/pytest-runner-5.3.0/setup.py", line 21, in <module>
2021-03-18T02:05:21.7905380Z     import sys
2021-03-18T02:05:21.7906440Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/distutils/core.py", line 108, in setup
2021-03-18T02:05:21.7907510Z     _setup_distribution = dist = klass(attrs)
2021-03-18T02:05:21.7909180Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/dist.py", line 315, in __init__
2021-03-18T02:05:21.7910760Z     self.fetch_build_eggs(attrs['setup_requires'])
2021-03-18T02:05:21.7912560Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
2021-03-18T02:05:21.7913730Z     replace_conflicting=True,
2021-03-18T02:05:21.7915400Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/pkg_resources/__init__.py", line 850, in resolve
2021-03-18T02:05:21.7916670Z     dist = best[req.key] = env.best_match(req, ws, installer)
2021-03-18T02:05:21.7936630Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1122, in best_match
2021-03-18T02:05:21.7937600Z     return self.obtain(req, installer)
2021-03-18T02:05:21.7939450Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1134, in obtain
2021-03-18T02:05:21.7940380Z     return installer(requirement)
2021-03-18T02:05:21.7942170Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
2021-03-18T02:05:21.7943360Z     return cmd.easy_install(req)
2021-03-18T02:05:21.7944870Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 665, in easy_install
2021-03-18T02:05:21.7945920Z     return self.install_item(spec, dist.location, tmpdir, deps)
2021-03-18T02:05:21.7947590Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 695, in install_item
2021-03-18T02:05:21.7948610Z     dists = self.install_eggs(spec, download, tmpdir)
2021-03-18T02:05:21.7950080Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 876, in install_eggs
2021-03-18T02:05:21.7951270Z     return self.build_and_install(setup_script, setup_base)
2021-03-18T02:05:21.7952810Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1115, in build_and_install
2021-03-18T02:05:21.7954220Z     self.run_setup(setup_script, setup_base, args)
2021-03-18T02:05:21.7955890Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1101, in run_setup
2021-03-18T02:05:21.7956830Z     run_setup(setup_script, args)
2021-03-18T02:05:21.7958120Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/sandbox.py", line 251, in run_setup
2021-03-18T02:05:21.7959110Z     raise
2021-03-18T02:05:21.7959790Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/contextlib.py", line 77, in __exit__
2021-03-18T02:05:21.7960610Z     self.gen.throw(type, value, traceback)
2021-03-18T02:05:21.7962060Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/sandbox.py", line 198, in setup_context
2021-03-18T02:05:21.7962850Z     yield
2021-03-18T02:05:21.7963570Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/contextlib.py", line 77, in __exit__
2021-03-18T02:05:21.7964350Z     self.gen.throw(type, value, traceback)
2021-03-18T02:05:21.7965780Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/sandbox.py", line 169, in save_modules
2021-03-18T02:05:21.7966590Z     saved_exc.resume()
2021-03-18T02:05:21.7967890Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/sandbox.py", line 144, in resume
2021-03-18T02:05:21.7968740Z     six.reraise(type, exc, self._tb)
2021-03-18T02:05:21.7970100Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise
2021-03-18T02:05:21.7970970Z     raise value.with_traceback(tb)
2021-03-18T02:05:21.7972340Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/sandbox.py", line 157, in save_modules
2021-03-18T02:05:21.7973140Z     yield saved
2021-03-18T02:05:21.7974460Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/sandbox.py", line 198, in setup_context
2021-03-18T02:05:21.7975230Z     yield
2021-03-18T02:05:21.7976490Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/sandbox.py", line 248, in run_setup
2021-03-18T02:05:21.7977380Z     DirectorySandbox(setup_dir).run(runner)
2021-03-18T02:05:21.7978750Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/sandbox.py", line 278, in run
2021-03-18T02:05:21.7979500Z     return func()
2021-03-18T02:05:21.7980770Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/sandbox.py", line 246, in runner
2021-03-18T02:05:21.7981590Z     _execfile(setup_script, ns)
2021-03-18T02:05:21.7983340Z   File "/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/sandbox.py", line 47, in _execfile
2021-03-18T02:05:21.7984170Z     exec(code, globals, locals)
2021-03-18T02:05:21.7985870Z   File "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/easy_install-qtqq5oq7/pytest-runner-5.3.0/temp/easy_install-ck5s79al/setuptools_scm-6.0.1/setup.py", line 52, in <module>
2021-03-18T02:05:21.7987420Z     ONNX_BUILD_TESTS = bool(os.getenv('ONNX_BUILD_TESTS') == '1')
2021-03-18T02:05:21.7989050Z   File "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/easy_install-qtqq5oq7/pytest-runner-5.3.0/temp/easy_install-ck5s79al/setuptools_scm-6.0.1/setup.py", line 29, in scm_config
2021-03-18T02:05:21.7990530Z     TP_DIR = os.path.join(TOP_DIR, 'third_party')
2021-03-18T02:05:21.7992200Z   File "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/easy_install-qtqq5oq7/pytest-runner-5.3.0/temp/easy_install-ck5s79al/setuptools_scm-6.0.1/src/setuptools_scm/__init__.py", line 15, in <module>
2021-03-18T02:05:21.7994610Z   File "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/easy_install-qtqq5oq7/pytest-runner-5.3.0/temp/easy_install-ck5s79al/setuptools_scm-6.0.1/src/setuptools_scm/version.py", line 42
2021-03-18T02:05:21.7996460Z     trace(f"tag '{tag}' parsed to {result}")
2021-03-18T02:05:21.7996990Z                                           ^
2021-03-18T02:05:21.7997400Z SyntaxError: invalid syntax
2021-03-18T02:05:21.7997720Z 
```
Same code was worked yesterday. Does `setuptools_scm-6.0.1` still support Python 3.5? How can I resolve this issue? Thank you!

**Comment by etechdevai** [comment]
They have removed the support for python3.5 in v6.0.0
https://github.com/pypa/setuptools_scm/blob/main/CHANGELOG.rst#v600

**Comment by RonnyPfannschmidt** [comment]
duplicate of #541 

there will be a better error soon
