### ISSUE TITLE
Use fallback_version if SCM isn't found

### ISSUE THREAD

**Issue by CharlesB2** [pypa/setuptools-scm#549]
I'm in some situation (testing my package in Docker) where git isn't available, and thought I could just use `fallback_version` argument, but it turns out I still get an exception `OSError: 'git' was not found`. 

I found I can overcome this by defining the `SETUPTOOLS_SCM_PRETEND_VERSION` environment variable, but I thought it would be easier to use `fallback_version` in this case as well?

I'm not sure I understood the different cases where one should use `SETUPTOOLS_SCM_PRETEND_VERSION` or `fallback_version`?

**Comment by RonnyPfannschmidt** [comment]
please post the full output of the build process when `export SETUPTOOLS_SCM_DEBUG=1` is used 
also what version is being used
there should not be a error on missing git commands

fallback is supposed to be used when all else fails, so when git fails it should be used
pretend is supposed to be used instead of figuring it, so distros can manage their envs

**Comment by CharlesB2** [comment]
Sorry I wasn't clear, I didn't want to report any error as using `SETUPTOOLS_SCM_PRETEND_VERSION` works when `git` isn't available.

It was more a suggestion to simplify things from a usage point of view, as for me after reading the docs I was thinking that `fallback_version` would work. It can be also completing the docs, e.g. to document the different cases where both `SETUPTOOLS_SCM_PRETEND_VERSION` and `fallback_version` apply

**Comment by RonnyPfannschmidt** [comment]
let me be  clear, if setuptools_scm fails with fallback set, **it is a bug** and needs to be fixed

fallback is something you use more as a author
pretend is something you use as a packager

**Comment by CharlesB2** [comment]
OK then, here's the trace for the error I get when `fallback_version` is defined, and `git` not installed:

```
>>> import setuptools_scm
>>> setuptools_scm.get_version(fallback_version="TEST")
l {'root': '.', 'relative_to': None}
root '/work'
relative_to None
dist name: None
looking for ep setuptools_scm.parse_scm /work
found ep .git = setuptools_scm.git:parse
<class 'FileNotFoundError'> [Errno 2] No such file or directory: 'git' <traceback object at 0x7f15e2a4c5c0>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 169, in get_version
    return _get_version(config)
  File "/usr/local/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 173, in _get_version
    parsed_version = _do_parse(config)
  File "/usr/local/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 127, in _do_parse
    version = _version_from_entrypoints(config) or _version_from_entrypoints(
  File "/usr/local/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 65, in _version_from_entrypoints
    version = _call_entrypoint_fn(root, config, ep.load())
  File "/usr/local/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 46, in _call_entrypoint_fn
    return fn(root, config=config)
  File "/usr/local/lib/python3.9/site-packages/setuptools_scm/git.py", line 115, in parse
    require_command("git")
  File "/usr/local/lib/python3.9/site-packages/setuptools_scm/utils.py", line 142, in require_command
    raise OSError("%r was not found" % name)
OSError: 'git' was not found
```

Version used is 6.0.1, installed from `pip`.

**Comment by RonnyPfannschmidt** [comment]
thanks, the controll flow is indeed incorrect, i'll need to add a test that validates this so i dont introduce it by accident

**Comment by P403n1x87** [comment]
I'm also trying to use `fallback_version` from `setup.py` inside a git submodle and it seems that the configuration argument is completely ignored as I still get a `LookupError` as if I didn't set `fallback_version` at all. 

My `setup.py` has

~~~
use_scm_version={"fallback_version": "0.0.0"},
~~~
and the debug logs give
~~~
    l {'root': '.', 'relative_to': None}
    root '/private/var/folders/zm/3z1wy1b135721pl0l6n61yt00000gn/T/pip-req-build-nc68aatt'
    relative_to None
    dist name: ddtrace
    looking for ep setuptools_scm.parse_scm /private/var/folders/zm/3z1wy1b135721pl0l6n61yt00000gn/T/pip-req-build-nc68aatt
    found ep EntryPoint(name='.git', value='setuptools_scm.git:parse', group='setuptools_scm.parse_scm') in /private/var/folders/zm/3z1wy1b135721pl0l6n61yt00000gn/T/pip-req-build-nc68aatt
    GIT_ASKPASS /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh
    cmd 'git rev-parse --show-prefix'
     in /private/var/folders/zm/3z1wy1b135721pl0l6n61yt00000gn/T/pip-req-build-nc68aatt
    GIT_ASKPASS /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh
    err b'fatal: not a git repository: /private/var/folders/zm/3z1wy1b135721pl0l6n61yt00000gn/T/pip-req-build-nc68aatt/../../.git/modules/prof-probe/slydog-dd-trace-py\n'
    ret 128
    EntryPoint(name='.git', value='setuptools_scm.git:parse', group='setuptools_scm.parse_scm') None
    looking for ep setuptools_scm.parse_scm_fallback /private/var/folders/zm/3z1wy1b135721pl0l6n61yt00000gn/T/pip-req-build-nc68aatt
    found ep EntryPoint(name='setup.py', value='setuptools_scm.hacks:fallback_version', group='setuptools_scm.parse_scm_fallback') in /private/var/folders/zm/3z1wy1b135721pl0l6n61yt00000gn/T/pip-req-build-nc68aatt
    version 0.0.0 -> 0.0.0
    EntryPoint(name='setup.py', value='setuptools_scm.hacks:fallback_version', group='setuptools_scm.parse_scm_fallback') <ScmVersion 0.0.0 d=None n=None d=False b=None>
    scm version <ScmVersion 0.0.0 d=None n=None d=False b=None>
    config {'version_scheme': 'guess-next-dev', 'local_scheme': 'node-and-date'}
    l {'root': '.', 'relative_to': None}
    root '/private/var/folders/zm/3z1wy1b135721pl0l6n61yt00000gn/T/pip-req-build-nc68aatt'
    relative_to None
    dist name: ddtrace
    looking for ep setuptools_scm.parse_scm /private/var/folders/zm/3z1wy1b135721pl0l6n61yt00000gn/T/pip-req-build-nc68aatt
    found ep EntryPoint(name='.git', value='setuptools_scm.git:parse', group='setuptools_scm.parse_scm') in /private/var/folders/zm/3z1wy1b135721pl0l6n61yt00000gn/T/pip-req-build-nc68aatt
    GIT_ASKPASS /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh
    cmd 'git rev-parse --show-prefix'
     in /private/var/folders/zm/3z1wy1b135721pl0l6n61yt00000gn/T/pip-req-build-nc68aatt
    GIT_ASKPASS /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh
    err b'fatal: not a git repository: /private/var/folders/zm/3z1wy1b135721pl0l6n61yt00000gn/T/pip-req-build-nc68aatt/../../.git/modules/prof-probe/slydog-dd-trace-py\n'
    ret 128
    EntryPoint(name='.git', value='setuptools_scm.git:parse', group='setuptools_scm.parse_scm') None
    looking for ep setuptools_scm.parse_scm_fallback /private/var/folders/zm/3z1wy1b135721pl0l6n61yt00000gn/T/pip-req-build-nc68aatt
    found ep EntryPoint(name='setup.py', value='setuptools_scm.hacks:fallback_version', group='setuptools_scm.parse_scm_fallback') in /private/var/folders/zm/3z1wy1b135721pl0l6n61yt00000gn/T/pip-req-build-nc68aatt
    EntryPoint(name='setup.py', value='setuptools_scm.hacks:fallback_version', group='setuptools_scm.parse_scm_fallback') None
    Traceback (most recent call last):
      File "/private/tmp/foo/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
        main()
      File "/private/tmp/foo/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/private/tmp/foo/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 151, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/private/var/folders/zm/3z1wy1b135721pl0l6n61yt00000gn/T/pip-build-env-99xv5rim/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/private/var/folders/zm/3z1wy1b135721pl0l6n61yt00000gn/T/pip-build-env-99xv5rim/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 158, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 150, in <module>
        setup(
      File "/private/var/folders/zm/3z1wy1b135721pl0l6n61yt00000gn/T/pip-build-env-99xv5rim/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/private/var/folders/zm/3z1wy1b135721pl0l6n61yt00000gn/T/pip-build-env-99xv5rim/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 453, in __init__
        _Distribution.__init__(
      File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/private/var/folders/zm/3z1wy1b135721pl0l6n61yt00000gn/T/pip-build-env-99xv5rim/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 831, in finalize_options
        ep(self)
      File "/private/var/folders/zm/3z1wy1b135721pl0l6n61yt00000gn/T/pip-build-env-99xv5rim/overlay/lib/python3.9/site-packages/setuptools_scm/integration.py", line 94, in infer_version
        dist.metadata.version = _get_version(config)
      File "/private/var/folders/zm/3z1wy1b135721pl0l6n61yt00000gn/T/pip-build-env-99xv5rim/overlay/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 177, in _get_version
        parsed_version = _do_parse(config)
      File "/private/var/folders/zm/3z1wy1b135721pl0l6n61yt00000gn/T/pip-build-env-99xv5rim/overlay/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 135, in _do_parse
        raise LookupError(
    LookupError: setuptools-scm was unable to detect version for '/private/var/folders/zm/3z1wy1b135721pl0l6n61yt00000gn/T/pip-req-build-nc68aatt'.
~~~
This seems to be caused by the presence of a `pyproject.toml` file. The first fallback version (from the `setup.py`) is overridden by the `pyproject.toml`, which in my case had no fallback version specified.
