### ISSUE TITLE
Trying to deploy on AWS and the deployment fails

### ISSUE THREAD

**Issue by beamhealthdev** [pypa/setuptools-scm#551]
I'm using Python 2.7.10, and Django 1.11.12. Deploying the application worked fine until yesterday, but it started failing today and throwing me the following error:

Downloading https://files.pythonhosted.org/packages/69/43/3e247b7b2134b48e9a53fb387e191e5e05b5f38f2faf78ca892097c2b441/django-haystack-2.8.1.tar.gz (1.6MB)
      Complete output from command python setup.py egg_info:
      /tmp/easy_install-aBnZy2/setuptools_scm-6.0.1/src
      <pkg_resources.WorkingSet object at 0x7f9fe29650d0>
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-build-fSN3AA/django-haystack/setup.py", line 71, in <module>
          setup_requires=['setuptools_scm'],
        File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
          _setup_distribution = dist = klass(attrs)
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 315, in __init__
          self.fetch_build_eggs(attrs['setup_requires'])
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
          replace_conflicting=True,
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 850, in resolve
          dist = best[req.key] = env.best_match(req, ws, installer)
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1122, in best_match
          return self.obtain(req, installer)
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1134, in obtain
          return installer(requirement)
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
          return cmd.easy_install(req)
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 665, in easy_install
          return self.install_item(spec, dist.location, tmpdir, deps)
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 695, in install_item
          dists = self.install_eggs(spec, download, tmpdir)
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 876, in install_eggs
          return self.build_and_install(setup_script, setup_base)
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1115, in build_and_install
          self.run_setup(setup_script, setup_base, args)
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1101, in run_setup
          run_setup(setup_script, args)
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 251, in run_setup
          raise
        File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
          self.gen.throw(type, value, traceback)
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 198, in setup_context
          yield
        File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
          self.gen.throw(type, value, traceback)
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 169, in save_modules
          saved_exc.resume()
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 144, in resume
          six.reraise(type, exc, self._tb)
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 157, in save_modules
          yield saved
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 198, in setup_context
          yield
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 248, in run_setup
          DirectorySandbox(setup_dir).run(runner)
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 278, in run
          return func()
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 246, in runner
          _execfile(setup_script, ns)
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 47, in _execfile
          exec(code, globals, locals)
        File "/tmp/easy_install-aBnZy2/setuptools_scm-6.0.1/setup.py", line 52, in <module>
          },
        File "/tmp/easy_install-aBnZy2/setuptools_scm-6.0.1/setup.py", line 29, in scm_config
          ]
        File "/tmp/easy_install-aBnZy2/setuptools_scm-6.0.1/src/setuptools_scm/__init__.py", line 8, in <module>
        File "/tmp/easy_install-aBnZy2/setuptools_scm-6.0.1/src/setuptools_scm/config.py", line 6, in <module>
        File "/tmp/easy_install-aBnZy2/setuptools_scm-6.0.1/src/setuptools_scm/utils.py", line 41
          print(*k)
                ^
      SyntaxError: invalid syntax
      
      ----------------------------------------
  Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-fSN3AA/django-haystack/
  You are using pip version 9.0.1, however version 21.0.1 is available.
  You should consider upgrading via the 'pip install --upgrade pip' command.
  2021-03-31 09:36:01,144 ERROR    Error installing dependencies: Command '/opt/python/run/venv/bin/pip install -r /opt/python/ondeck/app/requirements.txt' returned non-zero exit status 1
  Traceback (most recent call last):
    File "/opt/elasticbeanstalk/hooks/appdeploy/pre/03deploy.py", line 22, in main
      install_dependencies()
    File "/opt/elasticbeanstalk/hooks/appdeploy/pre/03deploy.py", line 18, in install_dependencies
      check_call('%s install -r %s' % (os.path.join(APP_VIRTUAL_ENV, 'bin', 'pip'), requirements_file), shell=True)
    File "/usr/lib64/python2.7/subprocess.py", line 186, in check_call
      raise CalledProcessError(retcode, cmd)
  CalledProcessError: Command '/opt/python/run/venv/bin/pip install -r /opt/python/ondeck/app/requirements.txt' returned non-zero exit status 1 (Executor::NonZeroExitStatus)

Please advise.

**Comment by RonnyPfannschmidt** [comment]
python2 is no longer supported, use `setuptools_scm < 6`

**Comment by RonnyPfannschmidt** [comment]
duplicate of #541

**Comment by beamhealthdev** [comment]
> python2 is no longer supported, use `setuptools_scm < 6`

I'm currently using setuptools_scm 5.0.2, but the issue persists.

**Comment by RonnyPfannschmidt** [comment]
based on the output you use a completely outdated pip version (which does the wrong thing) and the version is clearly 6.0.1 based on the egg name in the output

**Comment by RonnyPfannschmidt** [comment]
as far as i can tell haystack didn't pin `setuptools_scm`
you either need to install a working `setuptools_scm` before installing haystack, or fix haystack

**Comment by beamhealthdev** [comment]
I had `setuptools_scm == 5.0.2`. Should it be `setuptools-scm == 5.0.2` instead? With a hyphen instead of underscore.

**Comment by RonnyPfannschmidt** [comment]
the name normalization does not matter, but it does matter if its installed on the server at the time the setup.py of haystack is invoked on the server

**Comment by beamhealthdev** [comment]
Yes I have it being installed before `django-haystack`. Here's a snippet of my `requirements.txt` file:
```
setuptools-scm == 5.0.2
Django==1.11.12
django-appconf==1.0.2
django-celery-beat==1.1.1
django-celery-results==1.0.1
django-compressor==2.2
django-dotenv==1.4.2
django-environ==0.4.5
django-filter==1.1.0
django-haystack==2.8.1
```

**Comment by RonnyPfannschmidt** [comment]
i have no idea about the behavior of pip 9 at this point, but i do vaguely recall that it does dependency scanning and absolutely requires a **separate** install step for build deps

**Comment by beamhealthdev** [comment]
You mean specifically running `pip install setuptools-scm==5.0.2`? I did do that as well.

**Comment by RonnyPfannschmidt** [comment]
yes, it seems required to update your pip as well
