### ISSUE TITLE
setuptools-scm 6.2.0 has no such extra feature 'toml

### ISSUE THREAD

**Issue by Kyle-Verhoog** [pypa/setuptools-scm#611]
:wave: we just started seeing this in our docs build: https://readthedocs.org/projects/ddtrace/builds/14573515/

`/home/docs/checkouts/readthedocs.org/user_builds/ddtrace/envs/latest/bin/python ./setup.py install --force`

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/ddtrace/envs/latest/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2739, in requires
    deps.extend(dm[safe_extra(ext)])
KeyError: 'toml'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./setup.py", line 150, in <module>
    setup(
  File "/home/docs/checkouts/readthedocs.org/user_builds/ddtrace/envs/latest/lib/python3.8/site-packages/setuptools/__init__.py", line 152, in setup
    _install_setup_requires(attrs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ddtrace/envs/latest/lib/python3.8/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ddtrace/envs/latest/lib/python3.8/site-packages/setuptools/dist.py", line 785, in fetch_build_eggs
    resolved_dists = pkg_resources.working_set.resolve(
  File "/home/docs/checkouts/readthedocs.org/user_builds/ddtrace/envs/latest/lib/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/home/docs/checkouts/readthedocs.org/user_builds/ddtrace/envs/latest/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2741, in requires
    raise UnknownExtra(
pkg_resources.UnknownExtra: setuptools-scm 6.2.0 has no such extra feature 'toml'
```

haven't gotten a chance to dig in further - will update if I get the chance!

**Comment by RonnyPfannschmidt** [comment]
i identified a setuptools bug about provides_extra not being added when using `setup.cfg`, only when using `setup.py`

**Comment by vss888** [comment]
Is there any work around the bug?

**Comment by sagrawal-code** [comment]
> Is there any work around

Downgrading helped, for now: https://github.com/mehcode/python-xmlsec/issues/194 @vss888

**Comment by satya-rajesh** [comment]
I observed this issue while building python3-configparser:

Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.4BlTyo
+ umask 022
+ cd /usr/src/BUILD
+ cd configparser-5.0.1
+ python3 setup.py build
WARNING: The pip package is not available, falling back to EasyInstall for handling setup_requires/test_requires; this is deprecated and will be removed in a future version.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2750, in requires
    deps.extend(dm[safe_extra(ext)])
KeyError: 'toml'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/BUILD/configparser-5.0.1/setup.py", line 4, in <module>
    setuptools.setup()
  File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 164, in setup
    _install_setup_requires(attrs)
  File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 159, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 699, in fetch_build_eggs
    resolved_dists = pkg_resources.working_set.resolve(
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 793, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2752, in requires
    raise UnknownExtra(
pkg_resources.UnknownExtra: setuptools-scm 6.2.0 has no such extra feature 'toml'
error: Bad exit status from /var/tmp/rpm-tmp.4BlTyo (%build)

2 days back it was working, observing this error from yesterday.

**Comment by RonnyPfannschmidt** [comment]
@satya-rajesh your build setup is incomplete and thus breaks, the next release of setuptools_scm will raise a error hinting how to fix this

You will need a preinstall of setuptools_scm as build dependency

**Comment by satya-rajesh** [comment]
> @satya-rajesh your build setup is incomplete and thus breaks, the next release of setuptools_scm will raise a error hinting how to fix this
> 
> You will need a preinstall of setuptools_scm as build dependency

Thanks it worked with this change.
