### ISSUE TITLE
6.2.0 is breaking the installations that used the [toml] extra

### ISSUE THREAD

**Issue by pombredanne** [pypa/setuptools-scm#613]
My CI just started to fail with this https://dev.azure.com/nexB/4eb352bc-8a86-4498-a724-5745a81d1439/_apis/build/builds/4475/logs/94
```
2021-08-27T14:53:45.6675983Z     The above exception was the direct cause of the following exception:
2021-08-27T14:53:45.6676454Z     
2021-08-27T14:53:45.6676845Z     Traceback (most recent call last):
2021-08-27T14:53:45.6677288Z       File "<string>", line 1, in <module>
2021-08-27T14:53:45.6677737Z       File "/home/vsts/work/1/s/setup.py", line 6, in <module>
2021-08-27T14:53:45.6678178Z         setuptools.setup()
2021-08-27T14:53:45.6678906Z       File "/home/vsts/work/1/s/tmp/lib/python3.6/site-packages/setuptools/__init__.py", line 152, in setup
2021-08-27T14:53:45.6679434Z         _install_setup_requires(attrs)
2021-08-27T14:53:45.6680360Z       File "/home/vsts/work/1/s/tmp/lib/python3.6/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
2021-08-27T14:53:45.6680947Z         dist.fetch_build_eggs(dist.setup_requires)
2021-08-27T14:53:45.6681713Z       File "/home/vsts/work/1/s/tmp/lib/python3.6/site-packages/setuptools/dist.py", line 788, in fetch_build_eggs
2021-08-27T14:53:45.6682239Z         replace_conflicting=True,
2021-08-27T14:53:45.6682991Z       File "/home/vsts/work/1/s/tmp/lib/python3.6/site-packages/pkg_resources/__init__.py", line 780, in resolve
2021-08-27T14:53:45.6683769Z         new_requirements = dist.requires(req.extras)[::-1]
2021-08-27T14:53:45.6684841Z       File "/home/vsts/work/1/s/tmp/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2743, in requires
2021-08-27T14:53:45.6685638Z         ) from e
2021-08-27T14:53:45.6686677Z     pkg_resources.UnknownExtra: setuptools-scm 6.2.0 has no such extra feature 'toml'
```

**Comment by RonnyPfannschmidt** [comment]
closing as duplicate of #611 

the release was yanked

**Comment by pombredanne** [comment]
Thanks!
