### ISSUE TITLE
Running into version parsing error when used with check-manifest

### ISSUE THREAD

**Issue by zobayer1** [pypa/setuptools-scm#630]
Setuptools scm 6.3.1 running into parse error when used with tools like check-manifest. Error logs:
```
['/home/zobayer/.cache/pre-commit/repoijtr5gb3/py_env-python3/bin/python', '-m', 'build', '--sdist', '.', '--outdir', '/tmp/check-manifest-vu_vghoe-sdist'] failed (status 1):
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools>=45, setuptools_scm[toml]>=6.2, wheel)
* Getting dependencies for sdist...

ERROR Backend subproccess exited when trying to invoke get_requires_for_build_sdist
Traceback (most recent call last):
  File "/home/zobayer/.cache/pre-commit/repoijtr5gb3/py_env-python3/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 349, in <module>
    main()
  File "/home/zobayer/.cache/pre-commit/repoijtr5gb3/py_env-python3/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 331, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/home/zobayer/.cache/pre-commit/repoijtr5gb3/py_env-python3/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 284, in get_requires_for_build_sdist
    return hook(config_settings)
  File "/tmp/build-env-s1dvnzu0/lib/python3.8/site-packages/setuptools/build_meta.py", line 159, in get_requires_for_build_sdist
    return self._get_build_requires(config_settings, requirements=[])
  File "/tmp/build-env-s1dvnzu0/lib/python3.8/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
    self.run_setup()
  File "/tmp/build-env-s1dvnzu0/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 8, in <module>
    setup(
  File "/tmp/build-env-s1dvnzu0/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.8/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/tmp/build-env-s1dvnzu0/lib/python3.8/site-packages/setuptools/dist.py", line 453, in __init__
    _Distribution.__init__(
  File "/usr/local/lib/python3.8/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/tmp/build-env-s1dvnzu0/lib/python3.8/site-packages/setuptools/dist.py", line 831, in finalize_options
    ep(self)
  File "/tmp/build-env-s1dvnzu0/lib/python3.8/site-packages/setuptools_scm/integration.py", line 94, in infer_version
    dist.metadata.version = _get_version(config)
  File "/tmp/build-env-s1dvnzu0/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 185, in _get_version
    dump_version(
  File "/tmp/build-env-s1dvnzu0/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 90, in dump_version
    parsed_version = Version(version)
  File "/tmp/build-env-s1dvnzu0/lib/python3.8/site-packages/packaging/version.py", line 266, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'extras-0.3.0.dev3+g4d323bc.d20210909'
```

My module's name is [logging-extras](https://github.com/zobayer1/logging-extras). I have noticed that the `-extras` part of the name got pulled into version tags.

**This error did not occur with setuptools-scm 6.0.1**

When I tested the version by this, I got the expected version string:
```
>>> from importlib.metadata import version
>>> print(version("logging-extras"))
0.3.0.dev0+gf5fea17.d20210909
```

Or, when I tested it with setup.py:
```
(venv) $ python setup.py --version
0.2.0b1.dev3+g4d323bc
```
The differences in output are understandable as one of them is probably using the default version scheme.

The error persists even if I pass  a version string like this:
```
(venv) $ SETUPTOOLS_SCM_PRETEND_VERSION=0.2.0 check-manifest
```

Error logs:
```
... truncated ...
  File "/tmp/build-env-g2x9k5sz/lib/python3.8/site-packages/setuptools/dist.py", line 831, in finalize_options
    ep(self)
  File "/tmp/build-env-g2x9k5sz/lib/python3.8/site-packages/setuptools_scm/integration.py", line 94, in infer_version
    dist.metadata.version = _get_version(config)
  File "/tmp/build-env-g2x9k5sz/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 185, in _get_version
    dump_version(
  File "/tmp/build-env-g2x9k5sz/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 90, in dump_version
    parsed_version = Version(version)
  File "/tmp/build-env-g2x9k5sz/lib/python3.8/site-packages/packaging/version.py", line 266, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'extras-0.2.0'
```

Relevant information:
- environment: Python3.8 on Fedora 34 Workstation
- check-manifest version 0.46

`pyproject.toml`:
```
[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "logging_/version.py"
write_to_template = "# -*- coding: utf-8 -*-\n\n__version__ = '{version}'\n"
version_scheme = "release-branch-semver"

[tool.check-manifest]
ignore = ["logging_/version.py"]
```

Distribution packages still can be generated without any problem, for example with `python setup.py sdist bdist_wheel`.

I could not find a similar reported issue from the issues log. My sincere apologies if this was discussed somewhere else.  Please steer me in the right direction.

**Comment by RonnyPfannschmidt** [comment]
Can you gather the output when using the `SETUPTOOLS_SCM_DEBUG` ENV var

**Comment by zobayer1** [comment]
Do you want to see the output from a specific command? I ran `check-manifest` with the debug flag and got this output (I have truncated the big README texts from `long_description` field.

```
(venv) [zobayer@banana logging-extras] (main +)$ SETUPTOOLS_SCM_DEBUG=true check-manifest
['/home/zobayer/Projects/oss/logging-extras/venv/bin/python3.8', '-m', 'build', '--sdist', '.', '--outdir', '/tmp/check-manifest-l3pdvpst-sdist'] failed (status 1):
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (setuptools>=42, setuptools_scm[toml]>=3.4, wheel)
* Getting dependencies for sdist...
* Installing packages in isolated environment... (setuptools-scm==6.3.1)
* Building sdist...

ERROR Backend subproccess exited when trying to invoke build_sdist
version keyword {'name': 'logging-extras', 'version': None, 'author': 'Zobayer Hasan', 'author_email': 'zobayer1@gmail.com', 'maintainer': None, 'maintainer_email': None, 'url': 'https://github.com/zobayer1/logging-extras', 'license': 'MIT', 'description': 'Python logging extensions', 'long_description': '', 'keywords': 'python logging logger handler custom config dictconfig yaml', 'platforms': ['any'], 'classifiers': ['Development Status :: 4 - Beta', 'Environment :: Console', 'Intended Audience :: Developers', 'License :: OSI Approved :: MIT License', 'Operating System :: POSIX', 'Operating System :: MacOS', 'Operating System :: Unix', 'Operating System :: Microsoft :: Windows', 'Programming Language :: Python :: 3.6', 'Programming Language :: Python :: 3.7', 'Programming Language :: Python :: 3.8', 'Programming Language :: Python :: 3.9', 'Topic :: Software Development :: Libraries :: Python Modules'], 'download_url': None, 'provides': None, 'requires': None, 'obsoletes': None}
l {'root': '.', 'relative_to': None}
root '/tmp/check-manifest-fsa20m75-sources'
relative_to None
dist name: logging-extras
version extras-0.3.0.dev3+g4d323bc.d20210911 -> extras-0.3.0.dev3+g4d323bc.d20210911
scm version <ScmVersion extras-0.3.0.dev3+g4d323bc.d20210911 d=None n=None d=False b=None>
config {'version_scheme': 'guess-next-dev', 'local_scheme': 'node-and-date'}
finalize hook {'name': 'logging-extras', 'version': 'extras-0.3.0.dev3+g4d323bc.d20210911', 'author': 'Zobayer Hasan', 'author_email': 'zobayer1@gmail.com', 'maintainer': None, 'maintainer_email': None, 'url': 'https://github.com/zobayer1/logging-extras', 'license': 'MIT', 'description': 'Python logging extensions', 'long_description': '', 'keywords': ['python logging logger handler custom config dictconfig yaml'], 'platforms': ['any'], 'classifiers': ['Development Status :: 4 - Beta', 'Environment :: Console', 'Intended Audience :: Developers', 'License :: OSI Approved :: MIT License', 'Operating System :: POSIX', 'Operating System :: MacOS', 'Operating System :: Unix', 'Operating System :: Microsoft :: Windows', 'Programming Language :: Python :: 3.6', 'Programming Language :: Python :: 3.7', 'Programming Language :: Python :: 3.8', 'Programming Language :: Python :: 3.9', 'Topic :: Software Development :: Libraries :: Python Modules'], 'download_url': None, 'provides': None, 'requires': None, 'obsoletes': None}
l {'root': '.', 'relative_to': None}
root '/tmp/check-manifest-fsa20m75-sources'
relative_to None
dist name: logging-extras
version extras-0.3.0.dev3+g4d323bc.d20210911 -> extras-0.3.0.dev3+g4d323bc.d20210911
scm version <ScmVersion extras-0.3.0.dev3+g4d323bc.d20210911 d=None n=None d=False b=None>
config {'version_scheme': 'release-branch-semver', 'local_scheme': 'node-and-date'}
Traceback (most recent call last):
  File "/home/zobayer/Projects/oss/logging-extras/venv/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 349, in <module>
    main()
  File "/home/zobayer/Projects/oss/logging-extras/venv/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 331, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/home/zobayer/Projects/oss/logging-extras/venv/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 301, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
  File "/tmp/build-env-xrc3qwg9/lib/python3.8/site-packages/setuptools/build_meta.py", line 225, in build_sdist
    return self._build_with_temp_dir(['sdist', '--formats', 'gztar'],
  File "/tmp/build-env-xrc3qwg9/lib/python3.8/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
    self.run_setup()
  File "/tmp/build-env-xrc3qwg9/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 8, in <module>
    setup(
  File "/tmp/build-env-xrc3qwg9/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.8/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/tmp/build-env-xrc3qwg9/lib/python3.8/site-packages/setuptools/dist.py", line 453, in __init__
    _Distribution.__init__(
  File "/usr/local/lib/python3.8/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/tmp/build-env-xrc3qwg9/lib/python3.8/site-packages/setuptools/dist.py", line 831, in finalize_options
    ep(self)
  File "/tmp/build-env-xrc3qwg9/lib/python3.8/site-packages/setuptools_scm/integration.py", line 94, in infer_version
    dist.metadata.version = _get_version(config)
  File "/tmp/build-env-xrc3qwg9/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 185, in _get_version
    dump_version(
  File "/tmp/build-env-xrc3qwg9/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 90, in dump_version
    parsed_version = Version(version)
  File "/tmp/build-env-xrc3qwg9/lib/python3.8/site-packages/packaging/version.py", line 266, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'extras-0.3.0.dev3+g4d323bc.d20210911'

```

Output from `python setup.py --version`

```
(venv) [zobayer@banana logging-extras] (main +)$ SETUPTOOLS_SCM_DEBUG=true python setup.py --version
version keyword {'name': 'logging-extras', 'version': None, 'author': 'Zobayer Hasan', 'author_email': 'zobayer1@gmail.com', 'maintainer': None, 'maintainer_email': None, 'url': 'https://github.com/zobayer1/logging-extras', 'license': 'MIT', 'description': 'Python logging extensions', 'long_description': '', 'keywords': 'python logging logger handler custom config dictconfig yaml', 'platforms': ['any'], 'classifiers': ['Development Status :: 4 - Beta', 'Environment :: Console', 'Intended Audience :: Developers', 'License :: OSI Approved :: MIT License', 'Operating System :: POSIX', 'Operating System :: MacOS', 'Operating System :: Unix', 'Operating System :: Microsoft :: Windows', 'Programming Language :: Python :: 3.6', 'Programming Language :: Python :: 3.7', 'Programming Language :: Python :: 3.8', 'Programming Language :: Python :: 3.9', 'Topic :: Software Development :: Libraries :: Python Modules'], 'download_url': None, 'provides': None, 'requires': None, 'obsoletes': None}
l {'root': '.', 'relative_to': None}
root '/home/zobayer/Projects/oss/logging-extras'
relative_to None
dist name: logging-extras
looking for ep setuptools_scm.parse_scm /home/zobayer/Projects/oss/logging-extras
found ep EntryPoint(name='.git', value='setuptools_scm.git:parse', group='setuptools_scm.parse_scm') in /home/zobayer/Projects/oss/logging-extras
GIT_PS1_SHOWDIRTYSTATE 1
cmd 'git rev-parse --show-prefix'
 in /home/zobayer/Projects/oss/logging-extras
GIT_PS1_SHOWDIRTYSTATE 1
out b'\n'
real root /home/zobayer/Projects/oss/logging-extras
GIT_PS1_SHOWDIRTYSTATE 1
cmd 'git describe --dirty --tags --long --match *[0-9]*'
 in /home/zobayer/Projects/oss/logging-extras
GIT_PS1_SHOWDIRTYSTATE 1
out b'v0.2.0-beta-3-g4d323bc-dirty\n'
cmd 'git rev-parse --abbrev-ref HEAD'
 in /home/zobayer/Projects/oss/logging-extras
GIT_PS1_SHOWDIRTYSTATE 1
out b'main\n'
cmd 'git log -n 1 HEAD --format=%cI'
 in /home/zobayer/Projects/oss/logging-extras
GIT_PS1_SHOWDIRTYSTATE 1
out b'2021-09-09T17:53:12+06:00\n'
tag v0.2.0-beta
tag 'v0.2.0-beta' parsed to {'version': 'v0.2.0-beta', 'prefix': '', 'suffix': ''}
version pre parse v0.2.0-beta
version <Version('0.2.0b0')>
version v0.2.0-beta -> 0.2.0b0
EntryPoint(name='.git', value='setuptools_scm.git:parse', group='setuptools_scm.parse_scm') <ScmVersion 0.2.0b0 d=3 n=g4d323bc d=True b=main>
scm version <ScmVersion 0.2.0b0 d=3 n=g4d323bc d=True b=main>
config {'version_scheme': 'guess-next-dev', 'local_scheme': 'node-and-date'}
ep found: guess-next-dev
version 0.2.0b1.dev3
ep found: node-and-date
local_version +g4d323bc.d20210911
finalize hook {'name': 'logging-extras', 'version': '0.2.0b1.dev3+g4d323bc.d20210911', 'author': 'Zobayer Hasan', 'author_email': 'zobayer1@gmail.com', 'maintainer': None, 'maintainer_email': None, 'url': 'https://github.com/zobayer1/logging-extras', 'license': 'MIT', 'description': 'Python logging extensions', 'long_description': '', 'keywords': ['python logging logger handler custom config dictconfig yaml'], 'platforms': ['any'], 'classifiers': ['Development Status :: 4 - Beta', 'Environment :: Console', 'Intended Audience :: Developers', 'License :: OSI Approved :: MIT License', 'Operating System :: POSIX', 'Operating System :: MacOS', 'Operating System :: Unix', 'Operating System :: Microsoft :: Windows', 'Programming Language :: Python :: 3.6', 'Programming Language :: Python :: 3.7', 'Programming Language :: Python :: 3.8', 'Programming Language :: Python :: 3.9', 'Topic :: Software Development :: Libraries :: Python Modules'], 'download_url': None, 'provides': None, 'requires': None, 'obsoletes': None}
l {'root': '.', 'relative_to': None}
root '/home/zobayer/Projects/oss/logging-extras'
relative_to None
dist name: logging-extras
looking for ep setuptools_scm.parse_scm /home/zobayer/Projects/oss/logging-extras
found ep EntryPoint(name='.git', value='setuptools_scm.git:parse', group='setuptools_scm.parse_scm') in /home/zobayer/Projects/oss/logging-extras
GIT_PS1_SHOWDIRTYSTATE 1
cmd 'git rev-parse --show-prefix'
 in /home/zobayer/Projects/oss/logging-extras
GIT_PS1_SHOWDIRTYSTATE 1
out b'\n'
real root /home/zobayer/Projects/oss/logging-extras
GIT_PS1_SHOWDIRTYSTATE 1
cmd 'git describe --dirty --tags --long --match *[0-9]*'
 in /home/zobayer/Projects/oss/logging-extras
GIT_PS1_SHOWDIRTYSTATE 1
out b'v0.2.0-beta-3-g4d323bc-dirty\n'
cmd 'git rev-parse --abbrev-ref HEAD'
 in /home/zobayer/Projects/oss/logging-extras
GIT_PS1_SHOWDIRTYSTATE 1
out b'main\n'
cmd 'git log -n 1 HEAD --format=%cI'
 in /home/zobayer/Projects/oss/logging-extras
GIT_PS1_SHOWDIRTYSTATE 1
out b'2021-09-09T17:53:12+06:00\n'
tag v0.2.0-beta
tag 'v0.2.0-beta' parsed to {'version': 'v0.2.0-beta', 'prefix': '', 'suffix': ''}
version pre parse v0.2.0-beta
version <Version('0.2.0b0')>
version v0.2.0-beta -> 0.2.0b0
EntryPoint(name='.git', value='setuptools_scm.git:parse', group='setuptools_scm.parse_scm') <ScmVersion 0.2.0b0 d=3 n=g4d323bc d=True b=main>
scm version <ScmVersion 0.2.0b0 d=3 n=g4d323bc d=True b=main>
config {'version_scheme': 'release-branch-semver', 'local_scheme': 'node-and-date'}
ep found: release-branch-semver
tag 'main' parsed to None
version 0.3.0.dev3
ep found: node-and-date
local_version +g4d323bc.d20210911
0.3.0.dev3+g4d323bc.d20210911
```

I'd be happy to provide further information.

**Comment by RonnyPfannschmidt** [comment]
Something goes wrong when building the sdist, it's not clear to me where the extras is coming from, I suspect a fallback hook order issue + a bug in the folder name variant

**Comment by RonnyPfannschmidt** [comment]
the sdist is created correctly, will need more debugging with the other tools

**Comment by RonnyPfannschmidt** [comment]
ok, this is a compound issue about having both pyproject.toml setting and use_scm_version

this needs a little more detailed test/bugfix

**Comment by RonnyPfannschmidt** [comment]
@zobayer1 its a upstream bug check-manifest unconditionally sets it to a wrong value
