### ISSUE TITLE
Build breaks for pypi downloaded tar.gz

### ISSUE THREAD

**Issue by zerothi** [pypa/setuptools-scm#652]
I am trying to install `lmfit-1.0.3` using pip and encounters scm errors.

Basically I download `lmfit-1.0.3.tar.gz` from pythonhosted [here](https://files.pythonhosted.org/packages/8c/2f/8af90d45e585692eca1922c53e239c7aa97a904d9254df5b08f2f32520ac/lmfit-1.0.3.tar.gz).

I then continue to issue this command:
```shell
SETUPTOOLS_SCM_DEBUG=true python3 -m pip install --user -vvv lmfit-1.0.3.tar.gz
```
And get this output:
```
Using pip 21.3.1 from /opt/gnu/11.2.0/python/3.9.7/lib/python3.9/site-packages/pip (python 3.9)
User install by explicit request
Created temporary directory: /tmp/pip-ephem-wheel-cache-rft2xce6
Created temporary directory: /tmp/pip-req-tracker-abmaqkiu
Initialized build tracking at /tmp/pip-req-tracker-abmaqkiu
Created build tracker: /tmp/pip-req-tracker-abmaqkiu
Entered build tracker: /tmp/pip-req-tracker-abmaqkiu
Created temporary directory: /tmp/pip-install-564kdikb
Processing ./lmfit-1.0.3.tar.gz
  Created temporary directory: /tmp/pip-req-build-utognwbz
  Added file:///home/software/bash-build/.archives/lmfit-1.0.3.tar.gz to build tracker '/tmp/pip-req-tracker-abmaqkiu'
  Running setup.py (path:/tmp/pip-req-build-utognwbz/setup.py) egg_info for package from file:///home/software/bash-build/.archives/lmfit-1.0.3.tar.gz
  Created temporary directory: /tmp/pip-pip-egg-info-hpenmkau
  Running command python setup.py egg_info
  version keyword {'name': 'lmfit', 'version': None, 'author': 'LMFit Development Team', 'author_email': 'matt.newville@gmail.com', 'maintainer': None, 'maintainer_email': None, 'url': 'https://lmfit.github.io/lmfit-py/', 'license': 'BSD-3', 'description': 'Least-Squares Minimization with Bounds and Constraints', 'long_description': "A library for least-squares minimization and data fitting in\nPython.  Built on top of scipy.optimize, lmfit provides a Parameter object\nwhich can be set as fixed or free, can have upper and/or lower bounds, or\ncan be written in terms of algebraic constraints of other Parameters.  The\nuser writes a function to be minimized as a function of these Parameters,\nand the scipy.optimize methods are used to find the optimal values for the\nParameters.  The Levenberg-Marquardt (leastsq) is the default minimization\nalgorithm, and provides estimated standard errors and correlations between\nvaried Parameters.  Other minimization methods, including Nelder-Mead's\ndownhill simplex, Powell's method, BFGS, Sequential Least Squares, and\nothers are also supported.  Bounds and constraints can be placed on\nParameters for all of these methods.\n\nIn addition, methods for explicitly calculating confidence intervals are\nprovided for exploring minmization problems where the approximation of\nestimating Parameter uncertainties from the covariance matrix is\nquestionable. ", 'keywords': 'curve-fitting, least-squares minimization', 'platforms': ['Windows', 'Linux', 'Mac OS X'], 'classifiers': ['Development Status :: 5 - Production/Stable', 'Intended Audience :: Science/Research', 'License :: OSI Approved :: BSD License', 'Operating System :: OS Independent', 'Programming Language :: Python :: 3.6', 'Programming Language :: Python :: 3.7', 'Programming Language :: Python :: 3.8', 'Programming Language :: Python :: 3.9', 'Programming Language :: Python :: 3.10', 'Topic :: Scientific/Engineering'], 'download_url': 'https://lmfit.github.io//lmfit-py/', 'provides': None, 'requires': None, 'obsoletes': None}
  l {'root': '.', 'relative_to': None}
  root '/tmp/pip-req-build-utognwbz'
  relative_to None
  dist name: lmfit
  looking for ep setuptools_scm.parse_scm /tmp/pip-req-build-utognwbz
  looking for ep setuptools_scm.parse_scm_fallback /tmp/pip-req-build-utognwbz
  found ep EntryPoint(name='setup.py', value='setuptools_scm.hacks:fallback_version', group='setuptools_scm.parse_scm_fallback') in /tmp/pip-req-build-utognwbz
  EntryPoint(name='setup.py', value='setuptools_scm.hacks:fallback_version', group='setuptools_scm.parse_scm_fallback') None
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-utognwbz/setup.py", line 23, in <module>
      setup(name='lmfit',
    File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/distutils/core.py", line 108, in setup
      _setup_distribution = dist = klass(attrs)
    File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/site-packages/setuptools/dist.py", line 453, in __init__
      _Distribution.__init__(
    File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/distutils/dist.py", line 292, in __init__
      self.finalize_options()
    File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/site-packages/setuptools/dist.py", line 831, in finalize_options
      ep(self)
    File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/site-packages/setuptools/dist.py", line 852, in _finalize_setup_keywords
      ep.load()(self, ep.name, value)
    File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/site-packages/setuptools_scm/integration.py", line 65, in version_keyword
      dist.metadata.version = _get_version(config)
    File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 177, in _get_version
      parsed_version = _do_parse(config)
    File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 135, in _do_parse
      raise LookupError(
  LookupError: setuptools-scm was unable to detect version for '/tmp/pip-req-build-utognwbz'.

  Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

  For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
  Preparing metadata (setup.py) ... error
WARNING: Discarding file:///home/software/bash-build/.archives/lmfit-1.0.3.tar.gz. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 338, in run
    requirement_set = resolver.resolve(
  File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 468, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 445, in _make_requirement_from_install_req
    raise self._build_failures[ireq.link]
  File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 201, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 281, in __init__
    super().__init__(
  File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 292, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 546, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 58, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 49, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 561, in prepare_metadata
    self.metadata_directory = generate_metadata_legacy(
  File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 59, in generate_metadata
    call_subprocess(
  File "/opt/gnu/11.2.0/python/3.9.7/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py", line 254, in call_subprocess
    raise InstallationSubprocessError(proc.returncode, command_desc)
pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Removed file:///home/software/bash-build/.archives/lmfit-1.0.3.tar.gz from build tracker '/tmp/pip-req-tracker-abmaqkiu'
Removed build tracker: '/tmp/pip-req-tracker-abmaqkiu'
```

What is weird is that this is not reproducible by the package owner (see [here](https://github.com/lmfit/lmfit-py/issues/769#issuecomment-982816141)

I really have no clue how to debug this...

**Comment by RonnyPfannschmidt** [comment]
this is a upstream issue - as no minimal versions are defined, it seems that depending on the install path/mechanism and the packages in use will see different issuers/versions

i strongly recommend adding a pyproject.toml to set up minimal requirements in that project

alternatively preinstalling recent setuptools/setuptools_scm will also help

this is also possibly related to old setuptools/importlib_metadata having a odering/reordering issues with the oder of parsing fallbacks

the setup.py one should trigger *after* the one for PKG-INFO

the involved version numbers would be a big help

**Comment by zerothi** [comment]
Sorry for not providing the versions of the installation packages:

I am using:
- pip 21.3.1
- setuptools_scm 6.3.2
- setuptools 59.4.0 (also tested with 58.4.0)

Is there a way to see how the metadata is perceived and parsed to track this down?

**Comment by zerothi** [comment]
PS. I have suggested the package owners to follow here as well, and also forwarded the pyproject.toml suggestion.

**Comment by RonnyPfannschmidt** [comment]
closing as upstream issue
