### ISSUE TITLE
setuptools objects to generated version string

### ISSUE THREAD

**Issue by brianmay** [pypa/setuptools-scm#74]
```
pip install -e .                     
Obtaining file:///home/brian/tree/sshuttle
  Running setup.py (path:/home/brian/tree/sshuttle/setup.py) egg_info for package from file:///home/brian/tree/sshuttle

Cleaning up...
Exception:
Traceback (most recent call last):
  File "/tmp/bbb/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/tmp/bbb/local/lib/python2.7/site-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/tmp/bbb/local/lib/python2.7/site-packages/pip/req.py", line 1146, in prepare_files
    req_to_install.run_egg_info()
  File "/tmp/bbb/local/lib/python2.7/site-packages/pip/req.py", line 331, in run_egg_info
    "%(Name)s==%(Version)s" % self.pkg_info())
  File "/tmp/bbb/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/pkg_resources.py", line 2793, in parse
    reqs = list(parse_requirements(s))
  File "/tmp/bbb/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/pkg_resources.py", line 2721, in parse_requirements
    "version spec")
  File "/tmp/bbb/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/pkg_resources.py", line 2697, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ("Expected ',' or end-of-list in", u'sshuttle==0.76.dev1+ng629c386.d20160113', 'at', u'+ng629c386.d20160113')

Storing debug log for failure in /home/brian/.pip/pip.log
```

It seems to object to the '+' sign. This is with setuptools version 19.2

**Comment by RonnyPfannschmidt** [comment]
Your traceback very clearly has setuptools 5.5.1, which is simply too old

**Comment by brianmay** [comment]
Ok, that is weird as version 5.5.1 works fine.

The above stack trace happened after running the following command, which I assumed should have resulted in the latest version being installed in the virtualenv.

```
# pip install -U setuptools    
Downloading/unpacking setuptools from https://pypi.python.org/packages/3.5/s/setuptools/setuptools-19.2-py2.py3-none-any.whl#md5=7bdac510b6bc1675a2a149eb3f81af77
  Downloading setuptools-19.2-py2.py3-none-any.whl (463kB): 463kB downloaded
Installing collected packages: setuptools
  Found existing installation: setuptools 5.5.1
    Uninstalling setuptools:
      Successfully uninstalled setuptools
Successfully installed setuptools
Cleaning up...
```

Will continue investigating. Wonder if this is a setuptools bug.

**Comment by brianmay** [comment]
Looks like the above pip command leaves behind `/tmp/bbb/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl` which needs to be manually deleted.

**Comment by brianmay** [comment]
Closing as not a setuptools_scm bug.
