### ISSUE TITLE
not enough values to unpack when using git-archive of a tag

### ISSUE THREAD

**Issue by Jackenmen** [pypa/setuptools-scm#758]
To reproduce:
```
python -m venv repro
. repro/bin/activate
python -m pip install https://github.com/jack1142/test_setuptools_scm/archive/1.1.0.zip
```

Repository here (it's just a very simple project with only setuptools_scm and an almost empty package, nothing special):
https://github.com/jack1142/test_setuptools_scm

I used `%(describe)` instead of `%(describe:tags=true)` because GitHub doesn't seem to support the latter yet and I wanted to simplify the reproduction steps.

If you want a repro with `%(describe:tags=true)`, you can run this locally:
```
git clone https://github.com/jack1142/test_setuptools_scm
cd test_setuptools_scm
python -m venv .venv
. .venv/bin/activate
git archive --format=zip 1.2.0 > test_setuptools_scm-1.2.0.zip
python -m pip install ./test_setuptools_scm-1.2.0.zip
```

`%(describe)` is the equivalent of running `git describe` without `--long` option which is why this doesn't work.

Output from `pip install https://github.com/jack1142/test_setuptools_scm/archive/1.1.0.zip`:
```
Collecting https://github.com/jack1142/test_setuptools_scm/archive/1.1.0.zip
  Using cached https://github.com/jack1142/test_setuptools_scm/archive/1.1.0.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      Traceback (most recent call last):
        File "/tmp/test_setuptools_scm/.venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/tmp/test_setuptools_scm/.venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/tmp/test_setuptools_scm/.venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-0pw31b1o/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/tmp/pip-build-env-0pw31b1o/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-0pw31b1o/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/tmp/pip-build-env-0pw31b1o/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-0pw31b1o/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/tmp/pip-build-env-0pw31b1o/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 476, in __init__
          _Distribution.__init__(
        File "/tmp/pip-build-env-0pw31b1o/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 280, in __init__
          self.finalize_options()
        File "/tmp/pip-build-env-0pw31b1o/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 900, in finalize_options
          ep(self)
        File "/tmp/pip-build-env-0pw31b1o/overlay/lib/python3.10/site-packages/setuptools_scm/integration.py", line 123, in infer_version
          _assign_version(dist, config)
        File "/tmp/pip-build-env-0pw31b1o/overlay/lib/python3.10/site-packages/setuptools_scm/integration.py", line 59, in _assign_version
          maybe_version = _get_version(config)
        File "/tmp/pip-build-env-0pw31b1o/overlay/lib/python3.10/site-packages/setuptools_scm/__init__.py", line 154, in _get_version
          parsed_version = _do_parse(config)
        File "/tmp/pip-build-env-0pw31b1o/overlay/lib/python3.10/site-packages/setuptools_scm/__init__.py", line 101, in _do_parse
          version = _version_from_entrypoints(config) or _version_from_entrypoints(
        File "/tmp/pip-build-env-0pw31b1o/overlay/lib/python3.10/site-packages/setuptools_scm/_entrypoints.py", line 66, in _version_from_entrypoints
          version: ScmVersion | None = _call_entrypoint_fn(root, config, ep.load())
        File "/tmp/pip-build-env-0pw31b1o/overlay/lib/python3.10/site-packages/setuptools_scm/_entrypoints.py", line 40, in _call_entrypoint_fn
          return fn(root, config=config)
        File "/tmp/pip-build-env-0pw31b1o/overlay/lib/python3.10/site-packages/setuptools_scm/git.py", line 312, in parse_archival
          return archival_to_version(data, config=config)
        File "/tmp/pip-build-env-0pw31b1o/overlay/lib/python3.10/site-packages/setuptools_scm/git.py", line 286, in archival_to_version
          tag, number, node, _ = _git_parse_describe(archival_describe)
        File "/tmp/pip-build-env-0pw31b1o/overlay/lib/python3.10/site-packages/setuptools_scm/git.py", line 245, in _git_parse_describe
          tag, number, node = describe_output.rsplit("-", 2)
      ValueError: not enough values to unpack (expected 3, got 1)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by Jackenmen** [comment]
One more note - when a repository has no tags (or as documentation phrases it, when the commit is "undescribable"), `%(describe:tags=true)` will be substituted for an empty string:
https://git-scm.com/docs/git-log#Documentation/git-log.txt-emdescribeoptionsem

From the quick look at the source, it doesn't appear to be handled either.

**Comment by pp-mo** [comment]
HINT: we had something like this when deploying iris (https://github.com/SciTools/[iris](https://github.com/SciTools/iris) to a conda channel.
We fixed it by installing from PyPI instead of GitHub.

It appears that you can't install from a github artefact download, since setuptools-scm then fails to work out the version and install fails.  But you _can_ install from the equivalent PyPI artefact, since there setuptools-scm already processed the version during the build  process (i.e. they are not the same).

Or something like that, better explanation @trexfeathers ?

**Comment by trexfeathers** [comment]
>Or something like that, better explanation @trexfeathers ?

A good explanation, thanks @pp-mo. PyPI requires a built wheel, and building a wheel invokes setuptools_scm. My instinct is that it wouldn't be possible to get a version straight from the GitHub artifact, but I might have misunderstood.

**Comment by pp-mo** [comment]
> My instinct is that it wouldn't be possible to get a version straight from the GitHub artifact

Me too. 
My instinct is that it needs a repo, not just the file content -- it seems the logic uses branch-names and tags ?

However, I guess this **_could_** be changed/"fixed" in future 
E.G. could it get version from the filename of the artifact (i.e. a compressed download file, like `https://github.com/SciTools/iris/archive/refs/tags/v3.2.1.zip` --> `v3.2.1.zip`) ?

**Comment by Jackenmen** [comment]
It doesn't seem to me like this is closely related to my issue? This is specifically about a bug in support for git-archives, not for arbitrary archives. I know that in case of source distributions `setuptools_scm` falls back to `PKG-INFO` in the `.tar.gz` and in case of a built distribution, there's no build backend involved since the distribution is already built and it has the version metadata inside.

Arbitrarily archiving contents of the repository without any metadata can't work since there's no place to take the version from.

If you're uploading source distribution or built distribution as artifacts then you should be able to install from that too. Either way though, I'm unsure how it's related to this issue? Are you getting the same error or something?

**Comment by RonnyPfannschmidt** [comment]
Recent git has better support in export subst, but that needs export files

**Comment by trexfeathers** [comment]
>Are you getting the same error or something?

Yes, we were getting the same error when attempting to install from a GitHub artefact, like your example. Of course our switching to using an alternative artefact is merely a workaround.

**Comment by Jackenmen** [comment]
> Yes, we were getting the same error when attempting to install from a GitHub artefact, like your example.

Oh, I see. I got confused by the wording you used, when you were referring to GitHub artifacts I thought you were talking about GitHub Actions artifacts *or* some sort of built artifacts attached to the GitHub release, *not* the git-archive that you can get with the "Source code" link on the release page *or* using the `https://github.com/repo_owner/repo_name/archive/tag_name.zip` URL format.

**Comment by ashwinvis** [comment]
I get the same issue after supplying git_archival.txt. For example:

https://github.com/eX-Mech/pymech/archive/refs/tags/1.5.0rc3.zip

seems to have the correct tag generated

```sh
 ❯ cat .git_archival.txt 
node: d075abdc1fed9cd29d050cd4cd1931b0245dd37b
node-date: 2022-11-25T13:01:37+01:00
describe-name: 1.5.0rc3
ref-names: HEAD -> main, tag: 1.5.0rc3
```

but `pip install ./pymech-1.5.0rc3.zip` throws the same error. It seems to me that #772 has fixed this, but I am unable to test this in an isolated build since the fix in setuptools_scm has not been released.

**Comment by RonnyPfannschmidt** [comment]
This should be fixed by the 7.1.0 release

**Comment by ashwinvis** [comment]
@RonnyPfannschmidt Yes it is fixed now.

**Comment by RonnyPfannschmidt** [comment]
Thanks
