### ISSUE TITLE
Using setuptools 44, build fails with `pkg_resources.DistributionNotFound`

### ISSUE THREAD

**Issue by silaswaxter** [pypa/setuptools-scm#763]
Hello, I'm working on a packaging a python library with `setuptools` and want to use `setuptools-scm`;  however, I'm running into an issue that seems to be based on the fact that I'm working with `setuptools~=44` (necessary to support python 2.7).  In the `README` for this project, it says that `setuptools > 42`, so I think what I'm doing should work.  Here is what I have:

---

#### `pyproject.toml`
```
[build-system]
requires = [
    "setuptools > 44, <45",         # target old version of setuptools for python 2.7 support
    "setuptools-scm[toml]>=6.2",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

# `[project]` section is not supported with setuptools 44.x (required for python 2.7 support);  
# tested by comparing builds of `setuptools latest` vs `setuptools 44.x`.  The current workaround 
# is to define the same information in `setup.cfg`.
```

#### log from `pip list`
```
Package Version
------- -------
pip     22.2.2
wheel   0.37.1 
```

#### log from `pip install .`
```
Processing /home/sbsu/Workspace/meter_serial_tools
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/home/sbsu/Workspace/meter_serial_tools/setuptoolsv44/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/sbsu/Workspace/meter_serial_tools/setuptoolsv44/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/sbsu/Workspace/meter_serial_tools/setuptoolsv44/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-bxswwg0m/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-bxswwg0m/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-bxswwg0m/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 142, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 1, in <module>
        File "/tmp/pip-build-env-bxswwg0m/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 162, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.10/distutils/core.py", line 108, in setup
          _setup_distribution = dist = klass(attrs)
        File "/tmp/pip-build-env-bxswwg0m/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 447, in __init__
          _Distribution.__init__(self, {
        File "/usr/lib/python3.10/distutils/dist.py", line 292, in __init__
          self.finalize_options()
        File "/tmp/pip-build-env-bxswwg0m/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 739, in finalize_options
          for ep in sorted(eps, key=by_order):
        File "/tmp/pip-build-env-bxswwg0m/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 738, in <lambda>
          eps = map(lambda e: e.load(), pkg_resources.iter_entry_points(group))
        File "/tmp/pip-build-env-bxswwg0m/overlay/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2442, in load
          self.require(*args, **kwargs)
        File "/tmp/pip-build-env-bxswwg0m/overlay/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2465, in require
          items = working_set.resolve(reqs, env, installer, extras=self.extras)
        File "/tmp/pip-build-env-bxswwg0m/overlay/lib/python3.10/site-packages/pkg_resources/__init__.py", line 786, in resolve
          raise DistributionNotFound(req, requirers)
      pkg_resources.DistributionNotFound: The 'importlib-metadata; python_version < "3.8"' distribution was not found and is required by the application
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

#### `pyproject.toml`
```
[build-system]
requires = [
    "setuptools",
    "setuptools-scm[toml]>=6.2",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

# `[project]` section is not supported with setuptools 44.x (required for python 2.7 support);  
# tested by comparing builds of `setuptools latest` vs `setuptools 44.x`.  The current workaround 
# is to define the same information in `setup.cfg`.
```

#### log from `pip list`
```
Package Version
------- -------
pip     22.2.2
wheel   0.37.1
```

#### log from `pip install .`
```
Processing /home/sbsu/Workspace/meter_serial_tools
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyserial>=3.5
  Using cached pyserial-3.5-py2.py3-none-any.whl (90 kB)
Building wheels for collected packages: meterserialtools
  Building wheel for meterserialtools (pyproject.toml) ... done
  Created wheel for meterserialtools: filename=meterserialtools-0.1.dev6+gdbcbe40.d20220819-py3-none-any.whl size=6675 sha256=083f8eee39c33a7b162753a809d42bf060ee4e8e56dbd71ccc9850538cb89282
  Stored in directory: /tmp/pip-ephem-wheel-cache-qdros25_/wheels/81/45/2d/59dc82fe4cf8b901a5520dae6ce40904f0856a1e1c55ff020b
Successfully built meterserialtools
Installing collected packages: pyserial, meterserialtools
Successfully installed meterserialtools-0.1.dev6+gdbcbe40.d20220819 pyserial-3.5
```

**Comment by RonnyPfannschmidt** [comment]
It seems there was a missed case when testing against dead setuptools versions

Picking much older setuptools_scm should work

Current versions cannot even run on python 3.6

Closing as won't fix due to bandwidth
