### ISSUE TITLE
Can't determine why setuptools_scm behaves different in similar systems

### ISSUE THREAD

**Issue by jfernandz** [pypa/setuptools-scm#782]
Hi everyone, not sure if this is a setuptools_scm bug or some packaging issue (I'm using the `python3-setuptools-scm` package provided in bullseye repos) but I hope you can help me to determine where this different behavior comes from:

First I've got two debian bullseye virtual machines, one over LXC and the other through KVM/QEMU (not sure if this has something to do ... but it's the only difference I can find between both). As you can see the KVM/QEMU one is perfectly able to determine the version from the git tags (I'm also providing more info, like `setuptools`/`setuptools_scm` versions or evidences about the git project is clean and I'm not inside of any venv)

```
❯ echo $VIRTUAL_ENV

❯ git clean -fdx
❯ neofetch
       _,met$$$$$gg.          packager@deb-packages 
    ,g$$$$$$$$$$$$$$$P.       --------------------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 11 (bullseye) x86_64 
 ,$$P'              `$$$.     Host: KVM/QEMU (Standard PC (i440FX + PIIX, 1996) pc-i440fx-6.2) 
',$$P       ,ggs.     `$$b:   Kernel: 5.10.0-19-amd64 
`d$$'     ,$P"'   .    $$$    Uptime: 3 days, 35 mins 
 $$P      d$'     ,    $$P    Packages: 890 (dpkg) 
 $$:      $$.   -    ,d$$'    Shell: zsh 5.8 
 $$;      Y$b._   _,d$P'      Resolution: 1024x768 
 Y$$.    `.`"Y$$$$P"'         Terminal: /dev/pts/0 
 `$$b      "-.__              CPU: Common KVM (1) @ 2.493GHz 
  `Y$$                        GPU: 00:02.0 Vendor 1234 Device 1111 
   `Y$$.                      Memory: 254MiB / 3931MiB 
     `$$b.                    Disk (/): 23G / 31G (79%) 
       `Y$$b.                  
          `"Y$b._
              `"""

❯ sudo dpkg -l "*setuptools*"
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                   Version      Architecture Description
+++-======================-============-============-================================================================
un  python-setuptools-doc  <none>       <none>       (no description available)
ii  python3-setuptools     52.0.0-4     all          Python3 Distutils Enhancements
ii  python3-setuptools-scm 5.0.1-1      all          blessed package to manage your versions by scm tags for Python 3
❯ python3 -m setuptools_scm
Guessed Version 0.2.7.dev1+g8b10055
❯ python3 setup.py sdist
running sdist
running egg_info
creating cwdisplay.egg-info
writing cwdisplay.egg-info/PKG-INFO
writing dependency_links to cwdisplay.egg-info/dependency_links.txt
writing requirements to cwdisplay.egg-info/requires.txt
writing top-level names to cwdisplay.egg-info/top_level.txt
writing manifest file 'cwdisplay.egg-info/SOURCES.txt'
writing manifest file 'cwdisplay.egg-info/SOURCES.txt'
warning: sdist: standard file not found: should have one of README, README.rst, README.txt, README.md

running check
creating cwdisplay-0.2.7.dev1+g8b10055
.
.
.
copying systemd/stress-cwdisplay.service -> cwdisplay-0.2.7.dev1+g8b10055/systemd
Writing cwdisplay-0.2.7.dev1+g8b10055/setup.cfg
creating dist
Creating tar archive
removing 'cwdisplay-0.2.7.dev1+g8b10055' (and everything under it)
❯
```

However, the second one system ... (LXC) is not able to determine the version despite `python3 -m setuptools_scm` is apparently able!

```❯ echo $VIRTUAL_ENV

❯ git clean -xfd
❯ neofetch
       _,met$$$$$gg.          admin@yocto-builds 
    ,g$$$$$$$$$$$$$$$P.       ------------------ 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 11 (bullseye) x86_64 
 ,$$P'              `$$$.     Host: ProLiant DL380p Gen8 
',$$P       ,ggs.     `$$b:   Kernel: 5.15.39-3-pve 
`d$$'     ,$P"'   .    $$$    Uptime: 22 mins 
 $$P      d$'     ,    $$P    Packages: 443 (dpkg) 
 $$:      $$.   -    ,d$$'    Shell: zsh 5.8 
 $$;      Y$b._   _,d$P'      Resolution: 1024x768 
 Y$$.    `.`"Y$$$$P"'         Terminal: /dev/pts/3 
 `$$b      "-.__              CPU: Intel Xeon E5-2696 v2 (4) @ 3.500GHz 
  `Y$$                        Memory: 103MiB / 8192MiB 
   `Y$$.                      Disk (/): 66G / 125G (56%) 
     `$$b.                     
       `Y$$b.
          `"Y$b._
              `"""

❯ sudo dpkg -l "*setuptools*"
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                   Version      Architecture Description
+++-======================-============-============-================================================================
un  python-setuptools-doc  <none>       <none>       (no description available)
ii  python3-setuptools     52.0.0-4     all          Python3 Distutils Enhancements
ii  python3-setuptools-scm 5.0.1-1      all          blessed package to manage your versions by scm tags for Python 3
❯ python3 -m setuptools_scm
Guessed Version 0.2.7.dev1+g8b10055
❯ python3 setup.py sdist
running sdist
running egg_info
creating cwdisplay.egg-info
writing cwdisplay.egg-info/PKG-INFO
writing dependency_links to cwdisplay.egg-info/dependency_links.txt
writing requirements to cwdisplay.egg-info/requires.txt
writing top-level names to cwdisplay.egg-info/top_level.txt
writing manifest file 'cwdisplay.egg-info/SOURCES.txt'
writing manifest file 'cwdisplay.egg-info/SOURCES.txt'
warning: sdist: standard file not found: should have one of README, README.rst, README.txt, README.md

running check
creating cwdisplay-0.0.0
.
.
.
copying systemd/stress-cwdisplay.service -> cwdisplay-0.0.0/systemd
Writing cwdisplay-0.0.0/setup.cfg
creating dist
Creating tar archive
removing 'cwdisplay-0.0.0' (and everything under it)
❯
```

I've omitted part of the `python3 setup.py sdist` output because of convenience. I know the `5.0.1` version is maybe too old ... but I'm still interestend in figuring out why it's working properly in the KVM/QEMU system :thinking:

**Comment by RonnyPfannschmidt** [comment]
please rerun those commands using `SETUPTOOLS_SCM_DEBUG=1 ...`

**Comment by jfernandz** [comment]
Thank you very much, I think I found it :blush:. It seems to be a packaging problem, because `python3-setuptools-scm` debian package should depend on `python3-toml` ... I think I'm going to talk to Debian python packaging group to see what they think about.
```
❯ SETUPTOOLS_SCM_DEBUG=1 python3 setup.py sdist
finalize hook {'name': None, 'version': None, 'author': None, 'author_email': None, 'maintainer': None, 'maintainer_email': None, 'url': None, 'license': None, 'description': None, 'long_description': None, 'keywords': None, 'platforms': None, 'classifiers': None, 'download_url': None, 'provides': None, 'requires': None, 'obsoletes': None}
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools_scm/integration.py", line 58, in infer_version
    config = Configuration.from_file(dist_name=dist_name)
  File "/usr/lib/python3/dist-packages/setuptools_scm/config.py", line 138, in from_file
    defn = __import__("toml").load(strm)
ModuleNotFoundError: No module named 'toml'
running sdist
running egg_info
writing cwdisplay.egg-info/PKG-INFO
writing dependency_links to cwdisplay.egg-info/dependency_links.txt
writing requirements to cwdisplay.egg-info/requires.txt
writing top-level names to cwdisplay.egg-info/top_level.txt
find files toplevel /home/admin/builds/led-display-controller

/home/admin/builds/led-display-controller ['']
writing manifest file 'cwdisplay.egg-info/SOURCES.txt'
warning: sdist: standard file not found: should have one of README, README.rst, README.txt, README.md

running check
creating cwdisplay-0.0.0
.
.
.
```

Thank you very much and I should had consider to use that envvar but I forgot it exists despite that you point it out in your README :disappointed:

**Comment by jfernandz** [comment]
I think the problem comes from you actually didn't have the dependency in `install_requires` into your `setup.cfg` for `5.0.1` version, 

https://github.com/pypa/setuptools_scm/blob/v5.0.1/setup.cfg#L33

So I'm guessing the debian helper for python didn't resolve this dependency :disappointed:, probably that's because of they have a newer version in [bullseye-backports](https://packages.debian.org/bullseye-backports/python3-setuptools-scm)

Anyway ... thank you a lot for your help.
