### ISSUE TITLE
Please, pip install without a .git folder

### ISSUE THREAD

**Issue by rharder** [pypa/setuptools-scm#805]
I've found lots of issues online with "LookupError: setuptools-scm was unable to detect version" resolved by including the .git folder when doing a "pip install -e ." but I haven't found how to make the installer work without the .git folder.  

Including the .git folder is not an option for what we are doing (please don't argue that point), so why can't "pip install" install code without the .git folder?  Or perhaps I should ask, is there some piece of information that the installer is getting "for free" from the .git folder that I need to make available in some other way, perhaps in setup.py?

-Rob

**Comment by RonnyPfannschmidt** [comment]
It's unclear what you are asking for, sdists work fine without git

And there are multiple ways to override and provide a version differently

**Comment by rharder** [comment]
Yes, yes!  Surely there's a way to do an install with git, and my apologies if it's clear to everyone else, but I'm not even sure what version information I'm supplying.  In my setup.py, I'm reading __version__ from a _version.py file that, as I've seen recommended by others.  

I can't see from my setup.py file what could even be reaching into a .git directory:

```python
# -*- coding: utf-8 -*-
import pathlib
from setuptools import setup
import re


VERSIONFILE = "src/pyobs/_version.py"
verstrline = open(VERSIONFILE, "rt").read()
VSRE = r"^__version__ = ['\"]([^'\"]*)['\"]"
mo = re.search(VSRE, verstrline, re.M)
if mo:
    __version__ = mo.group(1)
else:
    raise RuntimeError("Unable to find version string in %s." % (VERSIONFILE,))


here = pathlib.Path(__file__).parent.resolve()

# Get the long description from the README file
long_description = (here / 'README.md').read_text(encoding='utf-8')

setup(
    name='pyobs',
    version=__version__,
    use_scm_version=True,
    setup_requires=['setuptools_scm'],
    description='Extract satellite observations from FITS images',
    long_description=long_description,
    long_description_content_type='text/markdown',
    url='https://gitlab.redacted.org',
    author='redacted',
    author_email='redacted',
    packages=['pyobs'],
    package_dir={"": "src"},
    package_data={
        'pyobs': ['etc/*', 'etc/se/*'],
    },
    include_package_data=True,
    python_requires='>=3.5, <4',
    install_requires=[
        'numpy',
        'scipy',
        'astropy',
        'sgp4',
        'pandas',
        'opencv-python',
        'filterpy',
        'scikit-learn',
        'starmatch',
    ],
    entry_points={
        'console_scripts': [
            'observe=pyobs.observe:main',
        ],
    },
)
```

**Comment by rharder** [comment]
And for what it's worth, the error I see, in this example from a Docker build:

```shell
 > [15/16] RUN echo "Installing PyObs..." &&   python3 -m pip install  ./:
#0 0.137 Installing PyObs...
#0 0.457 Processing /app/pyobs
#0 0.458   Preparing metadata (setup.py): started
#0 5.100   Preparing metadata (setup.py): finished with status 'error'
#0 5.106   error: subprocess-exited-with-error
#0 5.106
#0 5.106   × python setup.py egg_info did not run successfully.
#0 5.106   │ exit code: 1
#0 5.106   ╰─> [30 lines of output]
#0 5.106       /usr/lib/python3/dist-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
#0 5.106         warnings.warn(
#0 5.106       Traceback (most recent call last):
#0 5.106         File "<string>", line 2, in <module>
#0 5.106         File "<pip-setuptools-caller>", line 34, in <module>
#0 5.106         File "/app/pyobs/setup.py", line 27, in <module>
#0 5.106           setup(
#0 5.106         File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
#0 5.106           return distutils.core.setup(**attrs)
#0 5.106         File "/usr/lib/python3.10/distutils/core.py", line 108, in setup
#0 5.106           _setup_distribution = dist = klass(attrs)
#0 5.106         File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 459, in __init__
#0 5.106           _Distribution.__init__(
#0 5.106         File "/usr/lib/python3.10/distutils/dist.py", line 292, in __init__
#0 5.106           self.finalize_options()
#0 5.106         File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 837, in finalize_options
#0 5.106           ep(self)
#0 5.106         File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 858, in _finalize_setup_keywords
#0 5.106           ep.load()(self, ep.name, value)
#0 5.106         File "/app/pyobs/.eggs/setuptools_scm-7.1.0-py3.10.egg/setuptools_scm/integration.py", line 91, in version_keyword
#0 5.106           _assign_version(dist, config)
#0 5.106         File "/app/pyobs/.eggs/setuptools_scm-7.1.0-py3.10.egg/setuptools_scm/integration.py", line 63, in _assign_version
#0 5.106           _version_missing(config)
#0 5.106         File "/app/pyobs/.eggs/setuptools_scm-7.1.0-py3.10.egg/setuptools_scm/__init__.py", line 108, in _version_missing
#0 5.106           raise LookupError(
#0 5.106       LookupError: setuptools-scm was unable to detect version for /app/pyobs.
#0 5.106
#0 5.106       Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
#0 5.106
#0 5.106       For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
#0 5.106       [end of output]
#0 5.106
#0 5.106   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 5.108 error: metadata-generation-failed
#0 5.108
#0 5.108 × Encountered error while generating package metadata.
#0 5.108 ╰─> See above for output.
#0 5.108
#0 5.108 note: This is an issue with the package mentioned above, not pip.
#0 5.108 hint: See above for details.
```

**Comment by RonnyPfannschmidt** [comment]
I would recommend to use the env var for passing a pretended version

No need to put the git into a docker build


My personal preference these days would be to build a wheel, then install that in the docker file as to keep build time stuff out of the final image

**Comment by rharder** [comment]
OBE.  I switched over to pyproject.toml/setuptools and dumped setup.py.  Somewhere in that process, I'm no longer dependent on a .git repo underneath.
