### ISSUE TITLE
Installing this repo via Git archive URL tracebacks

### ISSUE THREAD

**Issue by webknjaz** [pypa/setuptools-scm#824]
It might be related to the recent Hatch migration. I haven't checked if this worked before...
```python-traceback
$ python3.11 -m pip install install https://github.com/pypa/setuptools_scm/archive/main.tar.gz
Collecting https://github.com/pypa/setuptools_scm/archive/main.tar.gz
  Downloading https://github.com/pypa/setuptools_scm/archive/main.tar.gz
     - 61.1 kB 2.4 MB/s 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [83 lines of output]
      dist name: None
      abs root {'root': '.', 'relative_to': '/tmp/pip-req-build-8gugsdjr/_own_version_helper.py'}
      file /tmp/pip-req-build-8gugsdjr/_own_version_helper.py
      pkginfo /tmp/pip-req-build-8gugsdjr/PKG-INFO
      out:
           usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]
                     [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
                     [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
                     [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
                     [--super-prefix=<path>] [--config-env=<name>=<envvar>]
                     <command> [<args>]
      
          These are common Git commands used in various situations:
      
          start a working area (see also: git help tutorial)
             clone     Clone a repository into a new directory
             init      Create an empty Git repository or reinitialize an existing one
      
          work on the current change (see also: git help everyday)
             add       Add file contents to the index
             mv        Move or rename a file, a directory, or a symlink
             restore   Restore working tree files
             rm        Remove files from the working tree and from the index
      
          examine the history and state (see also: git help revisions)
             bisect    Use binary search to find the commit that introduced a bug
             diff      Show changes between commits, commit and working tree, etc
             grep      Print lines matching a pattern
             log       Show commit logs
             show      Show various types of objects
             status    Show the working tree status
      
          grow, mark and tweak your common history
             branch    List, create, or delete branches
             commit    Record changes to the repository
             merge     Join two or more development histories together
             rebase    Reapply commits on top of another base tip
             reset     Reset current HEAD to the specified state
             switch    Switch branches
             tag       Create, list, delete or verify a tag object signed with GPG
      
          collaborate (see also: git help workflows)
             fetch     Download objects and refs from another repository
             pull      Fetch from and integrate with another repository or a local branch
             push      Update remote refs along with associated objects
      
          'git help -a' and 'git help -g' list available subcommands and some
          concept guides. See 'git help <command>' or 'git help <concept>'
          to read about a specific subcommand or concept.
          See 'git help git' for an overview of the system.
      err:
           fatal: not a git repository: '/tmp/pip-req-build-8gugsdjr/.git'
      
      ret: 128
      abs root {'root': '.', 'relative_to': '/tmp/pip-req-build-8gugsdjr/_own_version_helper.py'}
      file /tmp/pip-req-build-8gugsdjr/_own_version_helper.py
      <class 'FileNotFoundError'> [Errno 2] No such file or directory: 'hg' <traceback object at 0x7fa708e50180>
      Traceback (most recent call last):
        File "venv/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "venv/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "venv/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 148, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-aba6qmth/overlay/lib/python3.11/site-packages/hatchling/build.py", line 56, in build_wheel
          return os.path.basename(next(builder.build(wheel_directory, ['standard'])))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-aba6qmth/overlay/lib/python3.11/site-packages/hatchling/builders/plugin/interface.py", line 93, in build
          self.metadata.validate_fields()
        File "/tmp/pip-build-env-aba6qmth/overlay/lib/python3.11/site-packages/hatchling/metadata/core.py", line 243, in validate_fields
          _ = self.version
              ^^^^^^^^^^^^
        File "/tmp/pip-build-env-aba6qmth/overlay/lib/python3.11/site-packages/hatchling/metadata/core.py", line 128, in version
          self._version = self._get_version()
                          ^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-aba6qmth/overlay/lib/python3.11/site-packages/hatchling/metadata/core.py", line 226, in _get_version
          version = self.hatch.version.cached
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-aba6qmth/overlay/lib/python3.11/site-packages/hatchling/metadata/core.py", line 1412, in cached
          raise type(e)(message) from None
      OSError: Error getting the version from source `code`: 'hg' was not found
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python3.11 -m pip install --upgrade pip
```

Based on the above, I'd guess that the problems are following:
1. `.git_archival.txt` is not used to get the version.
2. Some `git` command is failing.
3. There's an `hg` fallback that errors out because I don't have mercurial on my machine.

My expectation is that it shouldn't attempt calling either of `git`/`hg`.

**Comment by RonnyPfannschmidt** [comment]
self-install never supported archival before

i'll add it on top of the cleanups later today
