### ISSUE TITLE
LookupError: setuptools-scm was unable to detect version for C:\...*\duckdb-master

### ISSUE THREAD

**Issue by BlackXargon** [pypa/setuptools-scm#865]
Hi, I've read couple similar issues but it didn't resolve my problem.

duckdb-master
......\tools\pythonpkg\setup.py

inside setup.py:
use_scm_version = setuptools_scm_conf

not sure what absolute path to use. I have tried
use_scm_version = {'root':'../..'}

and 

use_scm_version = {
"relative_to": __file__,
'root':'../..'
}

got same error

**Comment by RonnyPfannschmidt** [comment]
Based on the given information it's hard to guess,

**Comment by BlackXargon** [comment]
Apologies, below complete error log:

(.env) PS C:\Users\BlackXargon\Downloads\python packages> pip install --find-links=./ "C:\Users\BlackXargon\Downloads\python packages\duckdb-master\tools\pythonpkg"
Looking in links: ./
Processing c:\users\BlackXargon\downloads\python packages\duckdb-master\tools\pythonpkg
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      C:\Users\BlackXargon\00-My-Dev\.env\lib\site-packages\setuptools\__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.      !!
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      WARNING: The wheel package is not available.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\BlackXargon\Downloads\python packages\duckdb-master\tools\pythonpkg\setup.py", line 280, in <module>
          setup(
        File "C:\Users\BlackXargon\00-My-Dev\.env\lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\BlackXargon\00-My-Dev\.env\lib\site-packages\setuptools\_distutils\core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "C:\Users\BlackXargon\00-My-Dev\.env\lib\site-packages\setuptools\dist.py", line 496, in __init__
          _Distribution.__init__(
        File "C:\Users\BlackXargon\00-My-Dev\.env\lib\site-packages\setuptools\_distutils\dist.py", line 283, in __init__
          self.finalize_options()
        File "C:\Users\BlackXargon\00-My-Dev\.env\lib\site-packages\setuptools\dist.py", line 935, in finalize_options
          ep(self)
        File "C:\Users\BlackXargon\00-My-Dev\.env\lib\site-packages\setuptools\dist.py", line 955, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "C:\Users\BlackXargon\00-My-Dev\.env\lib\site-packages\setuptools_scm\integration.py", line 75, in version_keyword
          _assign_version(dist, config)
        File "C:\Users\BlackXargon\00-My-Dev\.env\lib\site-packages\setuptools_scm\integration.py", line 51, in _assign_version
          _version_missing(config)
        File "C:\Users\BlackXargon\00-My-Dev\.env\lib\site-packages\setuptools_scm\__init__.py", line 106, in _version_missing
          raise LookupError(


      **LookupError: setuptools-scm was unable to detect version for C:\Users\BlackXargon\Downloads\python packages\duckdb-master.**



      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


Please note that I am trying to manually do the installation in my office computer / no connection to PyPi.
(.env) PS C:\Users\BlackXargon\Downloads\python packages> pip list
Package            Version
------------------ -------
importlib-metadata 6.6.0
packaging          23.1
pip                22.0.4
pybind11           2.10.4
setuptools         67.8.0
setuptools-scm     6.4.2
tomli              2.0.1
typing_extensions  4.6.3
zipp               3.15.0

**Comment by RonnyPfannschmidt** [comment]
It Looks like you downloaded a archive off the master branch of duckdb and the error message is absolutely correct

**Comment by RonnyPfannschmidt** [comment]
closing due to lack of further feedback
