### ISSUE TITLE
Setuptools scm reads version string from readme

### ISSUE THREAD

**Issue by qw8z5fUB** [pypa/setuptools-scm#883]
Hello, I originally posted this as a bug under `setuptools`, but discussion there suggests the bug is `setuptools-scm` related.

Here's my original issue report: https://github.com/pypa/setuptools/issues/4010

The gist of it is that setuptools-scm appears to pull a version string out of my readme instead of using git tag info. This results in an invalid version string, and my package fails to build. 

Minimal reproducer script:
```
> docker run --rm -it python:3.8-bullseye /bin/bash
mkdir /tmp/myproj
cd /tmp/myproj
echo "Version: x.x.x" > README.md
touch mypkg.py
cat <<EOF > setup.cfg
[metadata]
long_description = file: README.md
EOF
cat <<EOF > pyproject.toml
[build-system]
requires = ["setuptools==68.0.0", "setuptools_scm[toml]>=7.1"]
build-backend = "setuptools.build_meta"
[tool.setuptools_scm]
write_to = "_version.py"
EOF
git init
python -m venv .venv
.venv/bin/python -m pip install -U 'pip==23.2' 
.venv/bin/python -m pip install -U 'build==0.10.0'
.venv/bin/python -m build -C--verbose
# ...
# setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'x.x.x'
```

I believe the issue can be traced to the `data_from_mime` function, which creates a dictionary from all lines containing a colon. That mime file must contain the actual version string, and also the one from my readme, and in this case the one from my readme overwrites the correct string in the returned dictionary.
https://github.com/pypa/setuptools_scm/blob/v7.1.0/src/setuptools_scm/utils.py#L144

I don't understand what that mime file is exactly, how it is created, or what it contains, but ideally `data_from_mime` would not be looking within the `long_description` field for version information.

**Comment by RonnyPfannschmidt** [comment]
thanks for the report

its indeed a mime data reading bug

basically after about >10 years you are the first person to have that type of metadata setup that fails and report it

i believe this was created around the time where multi-line long descriptions where still escaped in a gruesome manner
(prefixed with ` |` in a mime field)

the bug-fix will require to stop after the first blank line 
it seems like a good idea to just go for the HeadersParsers in the stdlib these days

## suggested workaround 

```
echo "Current Version: x.x.x" >  README.md
```


## relevant long problem log
```
found ep EntryPoint(name='PKG-INFO', value='setuptools_scm.hacks:parse_pkginfo', group='setuptools_scm.parse_scm_fallback') in /tmp/build-via-sdist-r4lqkqlj/mypkg-0.1.dev0
pkginfo /tmp/build-via-sdist-r4lqkqlj/mypkg-0.1.dev0/PKG-INFO
content 'Metadata-Version: 2.1\nName: mypkg\nVersion: 0.1.dev0\n\nVersion: x.x.x\n'
data {'Metadata-Version': '2.1', 'Name': 'mypkg', 'Version': 'x.x.x'}
```
## full output
```console

root@17136cac5829:/tmp/myproj# SETUPTOOLS_SCM_DEBUG=1 .venv/bin/python -m build 
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools==68.0.0, setuptools_scm[toml]>=7.1)
* Getting build dependencies for sdist...
finalize hook {'name': None, 'version': None, 'author': None, 'author_email': None, 'maintainer': None, 'maintainer_email': None, 'url': None, 'license': None, 'description': None, 'long_description': None, 'keywords': None, 'platforms': None, 'classifiers': None, 'download_url': None, 'provides': None, 'requires': None, 'obsoletes': None}
abs root {'root': '.', 'relative_to': 'pyproject.toml'}
file pyproject.toml
root '/tmp/myproj'
relative_to 'pyproject.toml'
dist name: None
version_from_ep setuptools_scm.parse_scm /tmp/myproj
looking for ep setuptools_scm.parse_scm /tmp/myproj
found ep EntryPoint(name='.git', value='setuptools_scm.git:parse', group='setuptools_scm.parse_scm') in /tmp/myproj
----
cmd:
     git --git-dir /tmp/myproj/.git rev-parse --show-prefix
 in: /tmp/myproj
out:
 

real root /tmp/myproj
----
cmd:
     git --git-dir /tmp/myproj/.git describe --dirty --tags --long --match "*[0-9]*"
 in: /tmp/myproj
err:
     fatal: No names found, cannot describe anything.

ret: 128
----
cmd:
     git --git-dir /tmp/myproj/.git rev-parse --verify --quiet HEAD
 in: /tmp/myproj
ret: 1
----
cmd:
     git --git-dir /tmp/myproj/.git status --porcelain --untracked-files=no
 in: /tmp/myproj
----
cmd:
     git --git-dir /tmp/myproj/.git rev-parse --abbrev-ref HEAD
 in: /tmp/myproj
out:
     HEAD

err:
     fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
    Use '--' to separate paths from revisions, like this:
    'git <command> [<revision>...] -- [<file>...]'

ret: 128
branch err HEAD fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]' 128
----
cmd:
     git --git-dir /tmp/myproj/.git symbolic-ref --short HEAD
 in: /tmp/myproj
out:
     master

----
cmd:
     git --git-dir /tmp/myproj/.git -c log.showSignature=false log -n 1 HEAD --format=%cI
 in: /tmp/myproj
err:
     fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
    Use '--' to separate paths from revisions, like this:
    'git <command> [<revision>...] -- [<file>...]'

ret: 128
timestamp err  fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]' 128
tag 0.0
tag '0.0' parsed to {'version': '0.0', 'prefix': '', 'suffix': ''}
version pre parse 0.0
version <Version('0.0')>
version 0.0 -> 0.0
EntryPoint(name='.git', value='setuptools_scm.git:parse', group='setuptools_scm.parse_scm') <ScmVersion 0.0 dist=0 node=None dirty=False branch=master>
scm version <ScmVersion 0.0 dist=0 node=None dirty=False branch=master>
config {'version_scheme': 'guess-next-dev', 'local_scheme': 'node-and-date'}
ep found: guess-next-dev
version 0.1.dev0
ep found: node-and-date
local_version 
running egg_info
writing mypkg.egg-info/PKG-INFO
writing dependency_links to mypkg.egg-info/dependency_links.txt
writing top-level names to mypkg.egg-info/top_level.txt
----
cmd:
     git rev-parse HEAD
 in: /tmp/myproj
out:
     HEAD

err:
     fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
    Use '--' to separate paths from revisions, like this:
    'git <command> [<revision>...] -- [<file>...]'

ret: 128
listing git files failed - pretending there aren't any
reading manifest file 'mypkg.egg-info/SOURCES.txt'
writing manifest file 'mypkg.egg-info/SOURCES.txt'
* Building sdist...
finalize hook {'name': None, 'version': None, 'author': None, 'author_email': None, 'maintainer': None, 'maintainer_email': None, 'url': None, 'license': None, 'description': None, 'long_description': None, 'keywords': None, 'platforms': None, 'classifiers': None, 'download_url': None, 'provides': None, 'requires': None, 'obsoletes': None}
abs root {'root': '.', 'relative_to': 'pyproject.toml'}
file pyproject.toml
root '/tmp/myproj'
relative_to 'pyproject.toml'
dist name: None
version_from_ep setuptools_scm.parse_scm /tmp/myproj
looking for ep setuptools_scm.parse_scm /tmp/myproj
found ep EntryPoint(name='.git', value='setuptools_scm.git:parse', group='setuptools_scm.parse_scm') in /tmp/myproj
----
cmd:
     git --git-dir /tmp/myproj/.git rev-parse --show-prefix
 in: /tmp/myproj
out:
 

real root /tmp/myproj
----
cmd:
     git --git-dir /tmp/myproj/.git describe --dirty --tags --long --match "*[0-9]*"
 in: /tmp/myproj
err:
     fatal: No names found, cannot describe anything.

ret: 128
----
cmd:
     git --git-dir /tmp/myproj/.git rev-parse --verify --quiet HEAD
 in: /tmp/myproj
ret: 1
----
cmd:
     git --git-dir /tmp/myproj/.git status --porcelain --untracked-files=no
 in: /tmp/myproj
----
cmd:
     git --git-dir /tmp/myproj/.git rev-parse --abbrev-ref HEAD
 in: /tmp/myproj
out:
     HEAD

err:
     fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
    Use '--' to separate paths from revisions, like this:
    'git <command> [<revision>...] -- [<file>...]'

ret: 128
branch err HEAD fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]' 128
----
cmd:
     git --git-dir /tmp/myproj/.git symbolic-ref --short HEAD
 in: /tmp/myproj
out:
     master

----
cmd:
     git --git-dir /tmp/myproj/.git -c log.showSignature=false log -n 1 HEAD --format=%cI
 in: /tmp/myproj
err:
     fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
    Use '--' to separate paths from revisions, like this:
    'git <command> [<revision>...] -- [<file>...]'

ret: 128
timestamp err  fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]' 128
tag 0.0
tag '0.0' parsed to {'version': '0.0', 'prefix': '', 'suffix': ''}
version pre parse 0.0
version <Version('0.0')>
version 0.0 -> 0.0
EntryPoint(name='.git', value='setuptools_scm.git:parse', group='setuptools_scm.parse_scm') <ScmVersion 0.0 dist=0 node=None dirty=False branch=master>
scm version <ScmVersion 0.0 dist=0 node=None dirty=False branch=master>
config {'version_scheme': 'guess-next-dev', 'local_scheme': 'node-and-date'}
ep found: guess-next-dev
version 0.1.dev0
ep found: node-and-date
local_version 
running sdist
running egg_info
writing mypkg.egg-info/PKG-INFO
writing dependency_links to mypkg.egg-info/dependency_links.txt
writing top-level names to mypkg.egg-info/top_level.txt
----
cmd:
     git rev-parse HEAD
 in: /tmp/myproj
out:
     HEAD

err:
     fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
    Use '--' to separate paths from revisions, like this:
    'git <command> [<revision>...] -- [<file>...]'

ret: 128
listing git files failed - pretending there aren't any
reading manifest file 'mypkg.egg-info/SOURCES.txt'
writing manifest file 'mypkg.egg-info/SOURCES.txt'
running check
creating mypkg-0.1.dev0
creating mypkg-0.1.dev0/mypkg.egg-info
copying files to mypkg-0.1.dev0...
copying README.md -> mypkg-0.1.dev0
copying mypkg.py -> mypkg-0.1.dev0
copying pyproject.toml -> mypkg-0.1.dev0
copying setup.cfg -> mypkg-0.1.dev0
copying mypkg.egg-info/PKG-INFO -> mypkg-0.1.dev0/mypkg.egg-info
copying mypkg.egg-info/SOURCES.txt -> mypkg-0.1.dev0/mypkg.egg-info
copying mypkg.egg-info/dependency_links.txt -> mypkg-0.1.dev0/mypkg.egg-info
copying mypkg.egg-info/top_level.txt -> mypkg-0.1.dev0/mypkg.egg-info
Writing mypkg-0.1.dev0/setup.cfg
Creating tar archive
removing 'mypkg-0.1.dev0' (and everything under it)
* Building wheel from sdist
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools==68.0.0, setuptools_scm[toml]>=7.1)
* Getting build dependencies for wheel...
finalize hook {'name': None, 'version': None, 'author': None, 'author_email': None, 'maintainer': None, 'maintainer_email': None, 'url': None, 'license': None, 'description': None, 'long_description': None, 'keywords': None, 'platforms': None, 'classifiers': None, 'download_url': None, 'provides': None, 'requires': None, 'obsoletes': None}
abs root {'root': '.', 'relative_to': 'pyproject.toml'}
file pyproject.toml
root '/tmp/build-via-sdist-r4lqkqlj/mypkg-0.1.dev0'
relative_to 'pyproject.toml'
dist name: None
version_from_ep setuptools_scm.parse_scm /tmp/build-via-sdist-r4lqkqlj/mypkg-0.1.dev0
looking for ep setuptools_scm.parse_scm /tmp/build-via-sdist-r4lqkqlj/mypkg-0.1.dev0
version_from_ep setuptools_scm.parse_scm_fallback /tmp/build-via-sdist-r4lqkqlj/mypkg-0.1.dev0
looking for ep setuptools_scm.parse_scm_fallback /tmp/build-via-sdist-r4lqkqlj/mypkg-0.1.dev0
found ep EntryPoint(name='PKG-INFO', value='setuptools_scm.hacks:parse_pkginfo', group='setuptools_scm.parse_scm_fallback') in /tmp/build-via-sdist-r4lqkqlj/mypkg-0.1.dev0
pkginfo /tmp/build-via-sdist-r4lqkqlj/mypkg-0.1.dev0/PKG-INFO
content 'Metadata-Version: 2.1\nName: mypkg\nVersion: 0.1.dev0\n\nVersion: x.x.x\n'
data {'Metadata-Version': '2.1', 'Name': 'mypkg', 'Version': 'x.x.x'}
version x.x.x -> x.x.x
EntryPoint(name='PKG-INFO', value='setuptools_scm.hacks:parse_pkginfo', group='setuptools_scm.parse_scm_fallback') <ScmVersion x.x.x dist=None node=None dirty=False branch=None>
scm version <ScmVersion x.x.x dist=None node=None dirty=False branch=None>
config {'version_scheme': 'guess-next-dev', 'local_scheme': 'node-and-date'}
failed to parse version x.x.x
Traceback (most recent call last):
  File "/tmp/build-env-osod1yci/lib/python3.8/site-packages/setuptools_scm/_version_cls.py", line 36, in _version_as_tuple
    parsed_version = Version(version_str)
  File "/tmp/build-env-osod1yci/lib/python3.8/site-packages/packaging/version.py", line 198, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'x.x.x'
/tmp/build-env-osod1yci/lib/python3.8/site-packages/setuptools/dist.py:510: SetuptoolsDeprecationWarning: Invalid version: 'x.x.x'.
!!

        ********************************************************************************
        The version specified is not a valid version according to PEP 440.
        This may not work as expected with newer versions of
        setuptools, pip, and PyPI.

        By 2023-Sep-26, you need to update your project and remove deprecated calls
        or your builds will no longer be supported.

        See https://peps.python.org/pep-0440/ for details.
        ********************************************************************************

!!
  self._validate_version(self.metadata.version)
running egg_info
/tmp/build-env-osod1yci/lib/python3.8/site-packages/setuptools/command/egg_info.py:131: SetuptoolsDeprecationWarning: Invalid version: 'x.x.x'.
!!

        ********************************************************************************
        Version 'x.x.x' is not valid according to PEP 440.

        Please make sure to specify a valid version for your package.
        Also note that future releases of setuptools may halt the build process
        if an invalid version is given.

        By 2023-Sep-26, you need to update your project and remove deprecated calls
        or your builds will no longer be supported.

        See https://peps.python.org/pep-0440/ for details.
        ********************************************************************************

!!
  return _normalization.best_effort_version(tagged)
Traceback (most recent call last):
  File "/tmp/myproj/.venv/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/tmp/myproj/.venv/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/tmp/myproj/.venv/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/tmp/build-env-osod1yci/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/tmp/build-env-osod1yci/lib/python3.8/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
    self.run_setup()
  File "/tmp/build-env-osod1yci/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in run_setup
    exec(code, locals())
  File "<string>", line 1, in <module>
  File "/tmp/build-env-osod1yci/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/tmp/build-env-osod1yci/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/tmp/build-env-osod1yci/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/tmp/build-env-osod1yci/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/tmp/build-env-osod1yci/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/tmp/build-env-osod1yci/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.ensure_finalized()
  File "/tmp/build-env-osod1yci/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/tmp/build-env-osod1yci/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 218, in finalize_options
    parsed_version = packaging.version.Version(self.egg_version)
  File "/tmp/build-env-osod1yci/lib/python3.8/site-packages/setuptools/_vendor/packaging/version.py", line 198, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'x.x.x'

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
```

**Comment by qw8z5fUB** [comment]
Hello, thank you for the comment/background. My workaround for now is to not use the readme as the long_description.

Yes given the obscurity of the bug I'd understand if this gets closed as "wont fix", just thought I'd report it in case it's of interest, or in case others encounter it in future. 

I don't plan to look into implementing a proper fix, my workaround is fine for my use case. I'll leave it up to you whether to leave the ticket open, address it, or close it as "wont fix". Thanks again!

**Comment by RonnyPfannschmidt** [comment]
it will get fixed, its a real bug and unlike 10 years ago, all the apis i need are in the stdlib :)
