### ISSUE TITLE
`FileNotFoundError`: version file found with `pip` but not with `build`

### ISSUE THREAD

**Issue by quentin-ag** [pypa/setuptools-scm#928]
First thanks for this very useful tool!

I have an issue with my use of `setuptools-scm` and I don't know if something is wrong in my configuration, or if something in my use case is not supported by `setuptools-scm`. I hope to get some advice here.

Althouth there are many past issues related to similar problems, I have found no solutions there. Most are about problems that have been fixed since (which is great).

<a id="org1dc9717"></a>

# Problem

I can install my Python package from source with `pip` but I cannot build it from the same source with `build`. The issue is `setuptools-scm` failing to find its version file.

Running the following (from `repo/`)

```shell
    python -m pip install mypkg
```

works but

```shell
    python -m pip build mypkg
```

fails with

    * Creating venv isolated environment...
    * Installing packages in isolated environment... (setuptools-scm>=8.0, setuptools>=64.*)
    * Getting build dependencies for sdist...
    Traceback (most recent call last):
      File "/home/user/.local/share/python/env/project/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
        main()
      File "/home/user/.local/share/python/env/project/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/user/.local/share/python/env/project/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 287, in get_requires_for_build_sdist
        return hook(config_settings)
      File "/tmp/build-env-wr7m1q9h/lib/python3.10/site-packages/setuptools/build_meta.py", line 358, in get_requires_for_build_sdist
        return self._get_build_requires(config_settings, requirements=[])
      File "/tmp/build-env-wr7m1q9h/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
        self.run_setup()
      File "/tmp/build-env-wr7m1q9h/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
        exec(code, locals())
      File "<string>", line 1, in <module>
      File "/tmp/build-env-wr7m1q9h/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
        return distutils.core.setup(**attrs)
      File "/tmp/build-env-wr7m1q9h/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 147, in setup
        _setup_distribution = dist = klass(attrs)
      File "/tmp/build-env-wr7m1q9h/lib/python3.10/site-packages/setuptools/dist.py", line 303, in __init__
        _Distribution.__init__(self, dist_attrs)
      File "/tmp/build-env-wr7m1q9h/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
        self.finalize_options()
      File "/tmp/build-env-wr7m1q9h/lib/python3.10/site-packages/setuptools/dist.py", line 680, in finalize_options
        ep(self)
      File "/tmp/build-env-wr7m1q9h/lib/python3.10/site-packages/setuptools_scm/_integration/setuptools.py", line 125, in infer_version
        _assign_version(dist, config)
      File "/tmp/build-env-wr7m1q9h/lib/python3.10/site-packages/setuptools_scm/_integration/setuptools.py", line 54, in _assign_version
        maybe_version = _get_version(config, force_write_version_files=True)
      File "/tmp/build-env-wr7m1q9h/lib/python3.10/site-packages/setuptools_scm/_get_version_impl.py", line 102, in _get_version
        write_version_files(config, version=version_string, scm_version=parsed_version)
      File "/tmp/build-env-wr7m1q9h/lib/python3.10/site-packages/setuptools_scm/_get_version_impl.py", line 63, in write_version_files
        dump_version(
      File "/tmp/build-env-wr7m1q9h/lib/python3.10/site-packages/setuptools_scm/_integration/dump_version.py", line 40, in dump_version
        write_version_to_path(
      File "/tmp/build-env-wr7m1q9h/lib/python3.10/site-packages/setuptools_scm/_integration/dump_version.py", line 76, in write_version_to_path
        target.write_text(content, encoding="utf-8")
      File "/usr/lib/python3.10/pathlib.py", line 1154, in write_text
        with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
      File "/usr/lib/python3.10/pathlib.py", line 1119, in open
        return self._accessor.open(self, mode, buffering, encoding, errors,
    FileNotFoundError: [Errno 2] No such file or directory: '../src/mypkg/_version.py'
    
    ERROR Backend subprocess exited when trying to invoke get_requires_for_build_sdist

<a id="orgac78c41"></a>

# Configuration

I have typical `src` layout, but the package root directory is one level below the root of the repository. That last point is probably the problem.
Example:

    repo
    ├── mypkg
    │  ├── pyproject.toml
    │  └── src
    │     └── mypkg
    │        ├── __init__.py
    │        ├── _version.py

Relevant configuration in `repo/mypkg/pyproject.toml`:

```toml
    [project]
    name = "mypkg"
    dynamic = ["version"]
    
    [build-system]
    requires = [
        "setuptools>=64.*",
        "setuptools-scm>=8.0",
    ]
    build-backend = "setuptools.build_meta"
    
    [tool.setuptools_scm]
    root = ".."
    write_to = "mypkg/src/mypkg/_version.py"          
```

<a id="orgb2f08c1"></a>

# Troubleshooting

If I remove `write_to` or set its value to `"_version.py"`, then the build works as expected.

Running `python -m setuptools_scm` from `repo/mypkg/` works fine too. When running commands from `repo/`, I get the following results.

```shell
    # from repo/
    python -m setuptools_scm -c mypkg/pyproject.toml
```

fails with:

    Traceback (most recent call last):
      File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "/home/user/.local/share/python/env/project/lib/python3.10/site-packages/setuptools_scm/__main__.py", line 6, in <module>
        main()
      File "/home/user/.local/share/python/env/project/lib/python3.10/site-packages/setuptools_scm/_cli.py", line 35, in main
        version = _get_version(config)
      File "/home/user/.local/share/python/env/project/lib/python3.10/site-packages/setuptools_scm/__init__.py", line 162, in _get_version
        dump_version(
      File "/home/user/.local/share/python/env/project/lib/python3.10/site-packages/setuptools_scm/__init__.py", line 77, in dump_version
        with open(target, "w") as fp:
    FileNotFoundError: [Errno 2] No such file or directory: '../mypkg/src/mypkg/_version.py'

EDIT: disregard the command and error above, it actually works with `setuptools-scm>=8.0` (same version as used for the build). I was using version `7.1`.

On the other hand
```shell
    # from repo/
    python -m setuptools_scm -c mypkg/pyproject.toml -r .
```

gives the correct output with the following warning:

    /home/user/.local/share/python/env/project/lib/python3.10/site-packages/setuptools_scm/_integration/pyproject_reading.py:90: UserWarning: root .. is overridden by the cli arg /home/user/project/repo
       warnings.warn(

**Comment by RonnyPfannschmidt** [comment]
That's a issue with write-up, 8.x added version-file to fix that

**Comment by quentin-ag** [comment]
Thanks for such a fast answer. I checked the versions again. 

The error reported in 'Troubleshooting' was indeed caused by my using version `7.1.0`. There is no issue with version `8.0.2`. I added that comment to the issue description.

However, the build configuration in `pyproject.toml` explicitly requires `setuptools-scm>=8.0`. I even tried `setuptools-scm>=8.0.2` to be sure. The error with `python -m pip build mypkg` is still there. Perhaps I misunderstood your meaning.

>  8.x added version-file to fix that

Do you mean that there is something to change in my configuration?

**Comment by RonnyPfannschmidt** [comment]
Yes,write-tois now deprecated as fixing the behavior would break people's configuration in a horrendous manner

**Comment by quentin-ag** [comment]
Ah yes, I have found it in `docs/config.md`! The solution was actually in the documentation.

For anyone else slow/tired like me, the solution is to replace `write_to` with `version_file` and adjust the path: `version_file` is relative to the directory containing `pyproject.toml` (as far as I can tell) while `write_to` is relative to `root`.
In my case:

```toml
    [tool.setuptools_scm]
    root = ".."
    # write_to = "mypkg/src/mypkg/_version.py" # fails with 'python -m build mypkg'
    version_file = "src/mypkg/_version.py" # fixed
```

Thanks again for the quick help!
