### ISSUE TITLE
SETUPTOOLS_SCM_PRETEND_VERSION not working when .hg folder does not exist

### ISSUE THREAD

**Issue by Stefanhg** [pypa/setuptools-scm#984]
Hello,

When `SETUPTOOLS_SCM_PRETEND_VERSION` is set but the project does not have the required .hg files it fails.
It means in order to run tests or install the package before a hg repo has been made then you cannot run any tests using Tox.
I could not reproduce the issue while just installing using PIP.  

**reproduce:**
* `pip install tox`
* Create the two files from **required files** section 
* set environment variable `SETUPTOOLS_SCM_PRETEND_VERSION=0.0.0`
* Open folder where the two files created earlier are and run `tox`

**required files:**

**pyproject.toml:**
```
[project]
name = 'my_test_package'

dependencies = [
]


# Allows for version to be pulled from __version__ in package
dynamic = ["version"]

[tool.setuptools_scm]
write_to = "__version__.py"

# Everything below is for testing
[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"
```

**toi.ini:** 
```
[tox]

```

**Output:**
 ```
   File "C:\Users\shg\AppData\Local\Temp\pip-build-env-1v2mrxes\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\shg\AppData\Local\Temp\pip-build-env-1v2mrxes\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 147, in setup
      _setup_distribution = dist = klass(attrs)
    File "C:\Users\shg\AppData\Local\Temp\pip-build-env-1v2mrxes\overlay\Lib\site-packages\setuptools\dist.py", line 303, in __init__
      _Distribution.__init__(self, dist_attrs)
    File "C:\Users\shg\AppData\Local\Temp\pip-build-env-1v2mrxes\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 283, in __init__
      self.finalize_options()
    File "C:\Users\shg\AppData\Local\Temp\pip-build-env-1v2mrxes\overlay\Lib\site-packages\setuptools\dist.py", line 654, in finalize_options
      ep(self)
    File "C:\Users\shg\AppData\Local\Temp\pip-build-env-1v2mrxes\overlay\Lib\site-packages\setuptools_scm\_integration\setuptools.py", line 121, in infer_version
      _assign_version(dist, config)
    File "C:\Users\shg\AppData\Local\Temp\pip-build-env-1v2mrxes\overlay\Lib\site-packages\setuptools_scm\_integration\setuptools.py", line 56, in _assign_version
      _version_missing(config)
    File "C:\Users\shg\AppData\Local\Temp\pip-build-env-1v2mrxes\overlay\Lib\site-packages\setuptools_scm\_get_version_impl.py", line 112, in _version_missing
      raise LookupError(
  LookupError: setuptools-scm was unable to detect version for C:\Users\shg\AppData\Local\Temp\pytest-of-shg\pytest-667\test_docs_build0\cookies\bake00\my_project
```

**Comment by RonnyPfannschmidt** [comment]
User error,tox cleans the environment

Add the env var to passenv of tox

**Comment by Stefanhg** [comment]
Oh yes you are right! 
Tried again and still able to reproduced with Tox file:
```
[tox]
passenv = *
```
Can also reproduce this with `passenv = SETUPTOOLS_SCM_PRETEND_VERSION`

**Comment by Stefanhg** [comment]
It does create a `__version__.py` file with version == 0.0.0 so it almost worked!

**Comment by RonnyPfannschmidt** [comment]
More context needed then

What's the output with debugging enabled

Does the same issue happen with build,or tox only

**Comment by Stefanhg** [comment]
Are you not able to reproduce it?
I have tried on 2 different machines, one does not even have THG installed and can reproduce it.

I tried enabling debugging in my tox.ini but I am unsure if this is enough to do it.  I am a bit unsure about my tox.ini config.
Both configs are also set in my command prompt so they should get passed correctly.
tox.ini:
```
[tox]
passenv=*
[testenv]
deps=pytest
commands=py.test
setenv =
    SETUPTOOLS_SCM_DEBUG=1
    SETUPTOOLS_SCM_PRETEND_VERSION = 0.0.0
```

Output:
```
py: find interpreter for spec PythonSpec(path=C:\Program Files\Python311\python.exe)
py: proposed PythonInfo(spec=CPython3.11.5.final.0-64, exe=C:\Program Files\Python311\python.exe, platform=win32, version='3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]', encoding_fs_io=utf-8-utf-8)
.pkg: find interpreter for spec PythonSpec(path=C:\Program Files\Python311\python.exe)
.pkg: proposed PythonInfo(spec=CPython3.11.5.final.0-64, exe=C:\Program Files\Python311\python.exe, platform=win32, version='3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]', encoding_fs_io=utf-8-utf-8)
.pkg: _optional_hooks> python C:\Users\stefa\AppData\Roaming\Python\Python311\site-packages\pyproject_api\_backend.py True setuptools.build_meta
.pkg: exit None (0.31 seconds) C:\Users\stefa\Downloads\test_tox\test2> python C:\Users\stefa\AppData\Roaming\Python\Python311\site-packages\pyproject_api\_backend.py True setuptools.build_meta pid=13360
.pkg: get_requires_for_build_sdist> python C:\Users\stefa\AppData\Roaming\Python\Python311\site-packages\pyproject_api\_backend.py True setuptools.build_meta
.pkg: exit None (0.06 seconds) C:\Users\stefa\Downloads\test_tox\test2> python C:\Users\stefa\AppData\Roaming\Python\Python311\site-packages\pyproject_api\_backend.py True setuptools.build_meta pid=13360
py: packaging backend failed (code=1), with LookupError: setuptools-scm was unable to detect version for C:\Users\stefa\Downloads\test_tox\test2.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
Traceback (most recent call last):
  File "C:\Users\stefa\AppData\Roaming\Python\Python311\site-packages\pyproject_api\_backend.py", line 90, in run
    outcome = backend_proxy(parsed_message["cmd"], **parsed_message["kwargs"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stefa\AppData\Roaming\Python\Python311\site-packages\pyproject_api\_backend.py", line 32, in __call__
    return getattr(on_object, name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stefa\Downloads\test_tox\test2\.tox\.pkg\Lib\site-packages\setuptools\build_meta.py", line 358, in get_requires_for_build_sdist
    return self._get_build_requires(config_settings, requirements=[])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stefa\Downloads\test_tox\test2\.tox\.pkg\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
    self.run_setup()
  File "C:\Users\stefa\Downloads\test_tox\test2\.tox\.pkg\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
    exec(code, locals())
  File "<string>", line 1, in <module>
  File "C:\Users\stefa\Downloads\test_tox\test2\.tox\.pkg\Lib\site-packages\setuptools\__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stefa\Downloads\test_tox\test2\.tox\.pkg\Lib\site-packages\setuptools\_distutils\core.py", line 147, in setup
    _setup_distribution = dist = klass(attrs)
                                 ^^^^^^^^^^^^
  File "C:\Users\stefa\Downloads\test_tox\test2\.tox\.pkg\Lib\site-packages\setuptools\dist.py", line 303, in __init__
    _Distribution.__init__(self, dist_attrs)
  File "C:\Users\stefa\Downloads\test_tox\test2\.tox\.pkg\Lib\site-packages\setuptools\_distutils\dist.py", line 283, in __init__
    self.finalize_options()
  File "C:\Users\stefa\Downloads\test_tox\test2\.tox\.pkg\Lib\site-packages\setuptools\dist.py", line 680, in finalize_options
    ep(self)
  File "C:\Users\stefa\Downloads\test_tox\test2\.tox\.pkg\Lib\site-packages\setuptools_scm\_integration\setuptools.py", line 121, in infer_version
    _assign_version(dist, config)
  File "C:\Users\stefa\Downloads\test_tox\test2\.tox\.pkg\Lib\site-packages\setuptools_scm\_integration\setuptools.py", line 56, in _assign_version
    _version_missing(config)
  File "C:\Users\stefa\Downloads\test_tox\test2\.tox\.pkg\Lib\site-packages\setuptools_scm\_get_version_impl.py", line 112, in _version_missing
    raise LookupError(
LookupError: setuptools-scm was unable to detect version for C:\Users\stefa\Downloads\test_tox\test2.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
Backend: run command get_requires_for_build_sdist with args {'config_settings': None}
Backend: Wrote response {'code': 1, 'exc_type': 'LookupError', 'exc_msg': "setuptools-scm was unable to detect version for C:\\Users\\stefa\\Downloads\\test_tox\\test2.\n\nMake sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.\n\nFor example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj"} to C:\Users\stefa\AppData\Local\Temp\pep517_get_requires_for_build_sdist-xzez1upo.json
.pkg: _exit> python C:\Users\stefa\AppData\Roaming\Python\Python311\site-packages\pyproject_api\_backend.py True setuptools.build_meta
.pkg: exit None (0.00 seconds) C:\Users\stefa\Downloads\test_tox\test2> python C:\Users\stefa\AppData\Roaming\Python\Python311\site-packages\pyproject_api\_backend.py True setuptools.build_meta pid=13360
  py: FAIL code 1 (0.48 seconds)
  evaluation failed :( (0.64 seconds)
```

**Comment by RonnyPfannschmidt** [comment]
the packaging env has a extra configuration, as no debug details where printed it seems that you need to configure it separately

this is a tox issue

**Comment by RonnyPfannschmidt** [comment]
closing due to lack of followup and the current implication for a tox issue
